### ISSUE TITLE
Last updates of cockatrice changed the pictures in database.

### ISSUE THREAD

**Issue by danyfire** [Cockatrice/Cockatrice#1025]
Hello,

I was wondering if someone could help me out with the last cockatrice Updates.
I updated the software, and now all images are set to most recent editions.
I did try to disable some sets, and clear the cache pics, but it's not helping.
For instance for the basics lands, I keep getting the tempest remastered pictures, when I want the guru lands, moving the edition top or bottom or disabling it won't change anything. 

I guess I could trick them by downloading the other pics and renaming them and replacing them in the recent folders, but that would be a pain to do. 
And it's not just about the lands, it's about all the other alternate pics from recent extensions that I don't want to use.

Can someone help me out ?

**Comment by tooomm** [comment]
sets on top have higher priority than lower sets.
since oracle now includes all cards in the cards.xml database file, you need to set it up once. that's why it pops up when you open cockatrice the first time.
- disable unused and unwanted sets, promo and dual decks for example
- move sets with preferred card art above other sets which include the same card (that's the reason why you need to place the guru set on position 1, because every set has lands...)

**Comment by danyfire** [comment]
@tooomm I did exactly what you said, I even re-installed from scratch deleting my cockatrice pics folder to make sure there was no cache images. 
I made sure on the first popup to select the extensions I did not want and moved the guru lands to top, Yet it still not working ! :-(.
Something is wrong with last version I even get the duel deck pictures even though I did not checked them !

![capture](https://cloud.githubusercontent.com/assets/7409924/7338505/096b527c-ec4e-11e4-899e-99636aee134e.JPG)

**Comment by tooomm** [comment]
Oh, Guru is a promo set. Didn't know that...
Gatherer doesn't have this special sets (they all start with a lowercase "p").
So there is no way Cockatrice can fetch and display them.

You saw them before, because HQ images worked and they included several special sets too!
Even when the old image source for HQ images got shut down, you still had them cached on your pc.

**Comment by danyfire** [comment]
Thank you for the explanation about the guru lands. I guess I'll have to go through the process of custom pictures.
But that doesn't explain the fact that I still get pictures from unchecked sets :
 
![image](https://cloud.githubusercontent.com/assets/7409924/7338784/2fbc6f34-ec57-11e4-9aef-7266594265c1.png)

**Comment by tooomm** [comment]
Maybe @ctrlaltca knows...

**Comment by ctrlaltca** [comment]
With the current behavior, cards from unchecked sets won't be shown in the deck editor, but they will still be used to show card images if they're sorted before of other sets. 
Fetching cards from disabled sets will ensure that if you play or spectate a game where someone is using a card that only exists in sets that you disabled, you still will be able to see the card's image.
Anyway, i agree with your doubts, and i think that it could be more intuitive if disabled sets are only used to fetch images when it doesn't exists in no enabled set.

**Comment by danyfire** [comment]
Ok I get it, in that case if I want to get rid of all duel decks images for example, I'll have to move them all down to the bottom...
It actually worked for the annihilation I moved it to the bottom and now I get the commander picture : 
![image](https://cloud.githubusercontent.com/assets/7409924/7339297/229250c2-ec6a-11e4-863f-e50d54dfee58.png)

But here is an other problem, I can't select multiple sets at the same time.
If I want to move them to the bottom I need to select them 1 by 1 and say move to bottom then save again the XML.
We didn't have those issues before, I don't want to sound annoying with such details.
I mean I don't think it's just me who must be struggling with this, all my friend also try to keep the oldest pictures when they can, with previous versions of cockatrice. 
They haven't upgraded yet, and they don't want to since I told them about this issue.

**Comment by Daenyth** [comment]
Can't you sort by column now though and sort by time to put the oldest ones
at the top?

**Comment by ZeldaZach** [comment]
Yes @Daenyth

**Comment by danyfire** [comment]
Ho that works :-) thank you for that trick.

**Comment by Daenyth** [comment]
A lot of people prefer new on top, but we could put it in the wiki's FAQ. In fact, you could as well ;)

Is there anything we can help you with at this point?

**Comment by tooomm** [comment]
I see reasons for both orderings (recent sets on top and recent sets on bottom), default should stay as it is.

When I have set the ordering to be oldest sets on top. And Cockatrice realizes that there are new sets available in the database and asks me if I want to enable them. If I hit "yes" without opening and reordering sets in `edit sets...`:
Will they appear on top because they got added last, or do they go to the bottom because the list was sorted with oldest sets on top the last time it was saved.

Another good thing with showing pictures of sets that are not enabled is that Cockatrice shows cards that get linked in chat with [[cardname]] for example.

But yes, there could be more information about the behavior in the wiki or even in the `edit sets...` dialog window.

**Comment by danyfire** [comment]
@Daenyth I'm good about that subject, thank you very much for your help. 
As for the wiki I don't know how to update it. I'll let you guys handle that :)

You guys are doing an amazing job keeping that software up to date and adding new stuff all the time. The recent notification bubbles in the task-bar are really useful as well.
Thank you very much for the hard work.

The only other feature I've been wondering about is the replay function, when it will be updated so that it's usable to go directly to one point in the game, fast forward, recording to videos, etc...
I asked in that topic a while ago : https://github.com/Cockatrice/Cockatrice/issues/383
I'm was just wondering, it's not really an issue just a feature that I would enjoy using some day.

**Comment by ZeldaZach** [comment]
Glad we could help!

The replay function, I know, @poixen did some work on to make it a little better working, but we haven't looked into it further as of this point. Why don't you start a discussion back up on your other ticket? :)
