### ISSUE TITLE
After the 11/5/15 update, no sound plays

### ISSUE THREAD

**Issue by Bull3tM0nk3y** [Cockatrice/Cockatrice#1070]
All settings for sound are turned on, and it was working the hour before I updated the client.

**Comment by tooomm** [comment]
Your operating system?

There is no longer sound for that many actions than before. Have a look here: #1055

**Comment by Bull3tM0nk3y** [comment]
"no more shuffle / draw / notification / play card sounds? ;(

just join / tap+untap / end step?"

"Correct. This feels the most comfortable to use. If there is enough demand for them, I might put something in. Right now, this feels good."

Ah, okay, that makes sense. I'm a bit sad that there's no shuffle and draw sound. The notification one was nice too, but I think it needed to be changed.

Thanks for the help! I thought I broke something.

**Comment by ZeldaZach** [comment]
Just adding to this quickly, @Bull3tM0nk3y you said the "test sound" button didn't work.

@poixen Is there a sound file for the test button?

**Comment by ctrlaltca** [comment]
How did #1055 got in? I see several problems:
 * a todo here: https://github.com/Cockatrice/Cockatrice/pull/1055/files#diff-130f09b6f6b9f4347838d51e2596054bR741
 * the "test system sound engine" doesn't work anymore (calling the no-more-existing cuckoo() slot)
 * sounds file got renamed. This is a problem under osx (new sound files needs to be copied in the user's data directory) and for everyone who's using a custom directory for sounds.
 * it removes a previously existing feature (shuffle / draw / notification / play card sounds). We'd better add an option to enable/disable each sound and tune the default values to our taste.

**Comment by Daenyth** [comment]
We should have sound themes, directories of sound files, and if the file
isn't in the theme, don't play it. That would be a lot less work than
configs for each

**Comment by poixen** [comment]
+ Removed todo
+ Fixed test button
+ removed additional sounds as this was a reworking of the system. I dont want a million sounds for fast games. How it was, was horrible. You would try it, laugh, then turn it off. How it feels now, I want it on all the time.
+ The mac issue, isnt this an issue with the sound path being set wrong for new installs? (Example, under windows it points to the appdata/local folder, rather than the install location.)

**Comment by ctrlaltca** [comment]
Under osx at the first run (or whenever the sound path is empty and the sounds/ directory doesn't exists  in the user's profile directory) sounds and images will get copied to the user profile:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/main.cpp#L189 ; the same applies for zone images.
This was an attempt to permit per-user profile settings of sounds and images. The current method used on windows and linux (choosing another path in the config) doesn't work nice on osx, since choosing a path inside the application bundle is not exactly userfriendly.
Dropping that behavior and forcing the default sounds path to be inside the application bundle could make it easier for us to update default sounds (and images), but it presents two downsides:
 * if i share my pc with somebody else, we'll have to use the same sounds/images;
 * custom sounds/images will be lost when updating the app, since the whole applicatin bundle will be replaced.

**Comment by ctrlaltca** [comment]
I think @Daenyth 's idea of handling this with "themes" is the definitive solution,but we'll need to handle both bundled themes (eg. the default one) and per-user themes from the user's profile.

**Comment by tooomm** [comment]
>The mac issue, isnt this an issue with the sound path being set wrong for new installs? **(Example, under windows it points to the appdata/local folder, rather than the install location.)**

Why is this set wrong under windows?
Did the sound file placement change?

wrong default location = no sound

**Comment by ctrlaltca** [comment]
So, #1071 got merged fixing the first two issues i reported.
About the other two issues, i propose to:
 * fix windows's nsis setup script to use "$INSTDIR\sounds" instead of "$LOCALAPPDATA\sounds". This reverts a single line of commit https://github.com/Cockatrice/Cockatrice/commit/f1e6aebabae4669652b6c5f03b7305b1be2c6306 that had a specific meaning (taking cards.xml and pictures out of c:\program files, where users can't write anymore since windows vista), but it's currently breaking sounds under windows
 * make sounds under osx works the same, pointing them to the plication bundle's Resources/sounds directory
 * postpone the user-resources in user-profiles idea to a later ticket: when properly implementing themes we'll be able to drop the "choose the xxx folder" pattern and adopt a "choose a theme from the available ones (both bundled and in user profile)". This relates to #792, where this has already been partially implemented.

**Comment by Bull3tM0nk3y** [comment]
Just got on my computer, and updated Cockatrice. Works for me now, thanks!
