### ISSUE TITLE
Disabling a set in the "order sets" window has no effect

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1072]
Unchecking a set's checkbox in the order sets window doesn't do anything - the images from that set will still be displayed. To truly disable images from a certain set, you have to put it at the bottom of the order sets window.

**Comment by ctrlaltca** [comment]
Disabling a set in the "edit sets" window is not supposed to disable image loading from that set, just to hide its cards from the deck editor.
This has already been discussed here: https://github.com/Cockatrice/Cockatrice/issues/1025 , and i agree it's hard to understand. I'm currently waiting to get another related change (#1039) in, and the address this problem.

**Comment by anoda9** [comment]
>Disabling a set in the "edit sets" window is not supposed to disable image loading from that set, just to hide its cards from the deck editor.

Wouldn't it be waaay more useful if that *was* how it functioned? It's much easier to uncheck the sets that you don't want to see (in terms of image loading) than to have to move them to the bottom of the ordering. I don't understand how hiding cards from the deck editor is useful.

**Comment by anoda9** [comment]
I feel like the main use of the edit sets window, by the majority of people, is to adjust which versions of card art are displayed. So the fact that this is not as easy as it could be is frustrating.

**Comment by anoda9** [comment]
Making the checkbox control which version of art is displayed would make it much easier to deprioritize certain kinds of sets in the image loading order. e.g. Suppose a user did not want to see any of the "From the Vault" card art - they could sort the sets by "Set Type", then easily uncheck all sets of that type. However, with the current system (priority based on order), there is no way to find all the "From the Vault" sets and easily disable all of them. 

>I don't understand how hiding cards from the deck editor is useful.

Thinking about this a bit more, I'm guessing it's meant for users to be able to search the database and only see cards from a certain format, for deckbuilding purposes? If so, that's a nice feature, but this seems like the wrong place to implement it. This should just be an option in the deckbuilder's search function.

**Comment by ctrlaltca** [comment]
I hope to answer to your points trying to explain the rationale behind these changes.

Previously, the oracle card updater was not really comfortable, because:
 1. we had sets selection in it, but since it never reminded which sets you wanted to import, it was forcing users to spend some time every time they updated cards, ticking they favorite sets.
 2. if you missed to import all the sets containing a specific card, you wont' be able to use it. The bad part of this is that maybe when playing or spectating a game with other people, if they used this card, you had no way to se it contents or its image.

So, instead of adding more features in oracle (which is a toll for just a specific game), i preferred to add more functionality inside cockatrice's sets handling, so:
 * oracle now always import all the cards, so cockatrice will always know all of them (fix point 2);
 * cockatrice's sets can be enabled/disabled, mimicking what you could previously do from inside oracle; but now cockatrice remembers these settings (fix point 1).

Disabled sets are still used to load images because:
 * if you don't load images from disabled sets, you could end up again in problem similar to number 2: no enabled set containing a specific card would lead to no image at all for that card;
 * the images sources are often incomplete, and i suppose it was better to show an image, even if not the one coming from the preferred set, instead of not showing an image at all;

Moreover, we discussed about making disabled sets always "low priority" for image loading, but we ended up thinking that having to explain users the behavior of a sortable list of two-priority items (enabled and disabled sets) was even more difficult than telling them just to sort sets.

If you have suggestions on how to make this userfriendly, keeping the good points, i'm glad to ear and discuss your opinions.

**Comment by tooomm** [comment]
>if you don't load images from disabled sets, you could end up again in problem similar to number 2: no enabled set containing a specific card would lead to no image at all for that card;

That's typically very useful for spectating or clickable card references in main chat with [[cardname]]! You always see that "unknown" card, no matter what your sets selection or your deck editor settings looks like :+1: 

<br>
Talking about further improvements...
The dialog window is still the same as before with the same functionality, isn't it?
You chose the sets with card art you like and pull them to the top... it just got expanded with the ability to show/hide (and adjust on the fly!) which sets get shown in the deck editor.
This has some general positive effects to the oracle updater and the general user experience (spectating e.g.) as ctrlaltca pointed out, while offering on-the-fly in-client customization and keeping them across card database updates.

Do you have all/most sets enabled?
If yes I can understand you, it's a bit misleading and inconvenient at first, that's right.
For this people the edit sets window expanded in functionality (and complexity) and they need to rethink once. From a picture pulling priority list before, to a picture priority list which let's you additionally+independently adjust single sets that get shown in the deck editor. To stick with the old behavior they just need to ignore the enable/disable button and sort the sets like they are used to - sets with pictures they like on top, exactly the same as before. (Or do I miss someting? Can't remember for sure how it worked before anymore. ;P )
But I think for everyone else it's pretty nice if you try to understand it - it's very logical constructed.
I like two-in-one "Edit sets" window very much, you need to get the idea of it and get used to it a bit for sure. At first it might look complicated, though...

*Think of all that limited or standard only players who just use/enable the most recent 0-5/6 sets.
You might not be aware, but e.g. Standard [is by far the most widely sanctioned constructed format at all levels of organized play (27th April 2015)](http://magic.wizards.com/en/articles/archive/level-one/introduction-popular-constructed-formats-2015-04-27).*

**Anyway, I'm working on improving the description for the window and how to use it.**

**Comment by anoda9** [comment]
My main issue is this: As a user, I want to have my sets sorted by release date (most recent sets first), but I also want to disable certain categories of images (e.g. all images in the FTV sets). In the current system, there is no easy way to do this. (You could sort by expansion type to find all the FTV sets and move them to the bottom, but then you've lost the order of sets by release date). This is the problem I'm trying to solve - I want there to be an easy way to do this. 

One solution might be this: if a set is unchecked, it is always sorted to the bottom of the set order. (i.e. there are 2 sorts applied to the lists of sets - first the sets are sorted by checked/unchecked, (putting checked sets first, unchecked sets second), then you sort each group (checked/unchecked) by the criteria specified by the user (name, release date, set code, expansion type, etc.)). This lets the client implement two tiers of priority, but in a way that works intuitively within the "sequential ordering" system that we currently have. (i.e. the rule that "the set that is highest on the list gets loaded first" is the only rule you have to know to understand the system). 

The client could do two sorts automatically, or their could be a checkbox with "sort all unchecked sets to the bottom" to the give the user the option.

**Comment by ctrlaltca** [comment]
> I want to have my sets sorted by release date (most recent sets first), but I also want to disable certain categories of images

We are currently using the sets order to determine the order images will be chosen from sets. We can't both keep this behavior and let sets always be sorted by release date, too.

> This seems like a good solution to me, let me know what you think.

Discussing with @tooomm we ended up on a similar solution, that is quite reasonable due to the current problems. But think for a moment of being a first time user, trying to quickly get trice up and working, having to understand the double-priority ordered list of enabled and disabled sets.. it's far from being userfriendly.

**Comment by Daenyth** [comment]
I like the idea of disable moving sets to the bottom of sort order

**Comment by anoda9** [comment]
>We are currently using the sets order to determine the order images will be chosen from sets. We can't both keep this behavior and let sets always be sorted by release date, too.

Right, that's why I made the suggestion (unchecking -> moved to bottom) that I did....

> it's far from being user friendly.

Most new users aren't going to immediately start fiddling with the set order, though, and it's not something you have to learn about if you don't want to. The client is perfectly usable without ever touching the set order. It's ok for more advanced features to be slightly more complex, as the users that are interested in them are generally more advanced/able to understand naunced features as well. 

But I really don't think it's that complicated - it seems very simple to just have two sentences explaining how the order sets window works. "When loading a card image, sets higher up on the list are used first. Unchecking a set's checkbox moves it to the bottom of the list, regardless of other sorting." The current system is not completely intuitive either - it actually took me some experimenting to figure out how the current order sets window worked, because I assumed that unchecking a set would stop its images from loading.
