### ISSUE TITLE
client eraser

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1117]
I downloaded the newest build today. and after installing it did some things. 

1. it deleted all my decks.
2. it deleted all my settings.
3. it restored an old issue i used to have that I do not know how I fixed in the first place. Let me explain. I have my taskbar up a few notches from the bottom of my screen. When I open cockatrice it opens with the text box under my taskbar. So I have to minimize it first then max it. After that it stays where I can see it. 

On another note i like the new sound for turns. much better. Have not tested other ones yet.

**Comment by Daenyth** [comment]
Was your old version older than summer 2014? It may have just changed the
location for your settings, we haven't heard of any deletion problems since
last year

**Comment by LestatTheDarkPrince** [comment]
No, it was a recent build from about 3 weeks ago. Also when I say my settings I mean the backgrounds and stuff. like hand area pictures etc.

**Comment by ctrlaltca** [comment]
I suppose the files are still there, it's just the settings that have been cleared.
This is probably due to the behavior introduced in #1062 (the installer triggers an uninstall if an old version is detected), and by the fact that the uninstaller calls: DeleteRegKey HKCU "Software\Cockatrice".
The uninstaller should be improved not to delete settings by default, implementing #876.
Also, it would be nice to take settings out from the registry and save them as an ini file inside the user profile, so that the the user profile is self-contained in a single folder enabling the creation of a portable version.

**Comment by ZeldaZach** [comment]
I'm a fan of @ctrlaltca's idea on having settings in a human readable/editable file locally to allow for trice to be used on something like a USB

**Comment by LestatTheDarkPrince** [comment]
Also the Screen issue happens at the end of Every game now. it puts my voice box under the taskbar.

**Comment by Daenyth** [comment]
+1 for ini > registry

**Comment by woogerboy21** [comment]
@LestatTheDarkPrince whats the "voice box" under the taskbar?  Is it an external app of some sort.  Also by chance do you have the windows task bar setup to hide?

**Comment by ctrlaltca** [comment]
I suppose he means the inputbar of the chat box on the bottom right side of game tabs

**Comment by LestatTheDarkPrince** [comment]
thats what I mean yes the space where I type. Also i do not have "auto hide" checked as i find it annoying to try and get the bar back when i want it.
