### ISSUE TITLE
Customizable User Ranks

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1177]
Currently, user levels are defined strictly within the codebase.
There should be a way to allow server operators to alter what the pawn icons are and who has access to modTools and/or adminTools based on the rank.

```
./cockatrice/src/pixmapgenerator.cpp
QSvgRenderer svg(QString(":/resources/userlevels/" + levelString + ".svg"));
```

In our initial discussion, I suggested using something similar to a modding system of file:

```
int levelString = 0;
if (isRegistered) levelString += 2;
if (isModerator) levelString += 4;
if (isAdmin) levelString += 8;
if (isDonator) levelString += 16;
etc...
```

In addition, it seems like the current system relies on `ServerInfo_User` for getting the `levelString` and would need a cleanup/rewrite in order to allow for custom ranks/changes to be done.

By moving everything to the servatrice INI file, it would allow for custom ranks/pawns with powers to be easier to track:

```
level_1=greenPawn
level_2=bluePawn
level_4=bwPawn;modTools
level_8=redPawn;adminTools
etc...
```

Adding a ticket so more people can help discuss it and it won't get lost in the chat rooms.

**Comment by woogerboy21** [comment]
I like the idea of being customizable by the server owner/operator but the biggest problem I see is the svg icons get rolled into the client during compiling so though you could make custom ranks, having them show different images in some place like the user list would be problematic if the levels were not defined in code some place.  Any idea's around that?

**Comment by ZeldaZach** [comment]
What if the server owner could make a custom folder, `pictures`, where he/she could store icons and such.

In the INI file portion, instead of saying maybe `greenPawn` they can define a path such as `~/servatrice/pictures/customGreenPawn.svg`

**Comment by woogerboy21** [comment]
Isnt the svg actually stored client side though?  Its not pushed down by the server to the client.  The client is simply told what user level the user is and generates a pixmap in client based on the local svg pixmap files that are included in the client folder path.

**Comment by ZeldaZach** [comment]
There's nothing saying we can't call in an outside URL to do work, such as with the card downloads

**Comment by woogerboy21** [comment]
Thats true.  If I were to make a recommendations.  The checks for users being registered should simply be changed to something like IsRegistered > 0 and at that point you can define any type of registered user level.  And have the client look up svg icons by Boolean values rather than string names.  That way you can update the database fields to be any value you want and the client download / grab / have included the svg icons by simple request based on the same user level Boolean value used through out the entire code logic.

**Comment by ZeldaZach** [comment]
Can you give an example of what you're getting at? I don't think I follow you @woogerboy21

**Comment by poixen** [comment]
Sounds good wooger. Svgs are just massive XMLs, so they can be sent to the client and reconstructed. Although, svgs are added to the dll files on compilation right? So the svgs would need to be external

**Comment by woogerboy21** [comment]
@ZeldaZach : in a nutshell.  In the current code logic a test is sent to see if the user is registered and a lookup is done to see if the value of "IsRegistered" is matched.  If so the svg icon used is named registered.svg.  I simply propose that we change the testing to be a test of > 0 (rather than expecting a hard 2) and instead of doing a number to name conversion for svg name simply keep the svg icon names a Boolean value.  So its a test for isuserregister > 0 ... return user level value from db (say 15 as an example) and then instead of having some hard defined number to name.svg the client looks for a 15.svg.  (does that make more since?)

**Comment by woogerboy21** [comment]
@poixen : yes, but getting the code in place to pass the data between server / client is beyond my level of understanding at this point :(

**Comment by ZeldaZach** [comment]
@woogerboy21 I think I get you.

You're saying that the system currently only checks if the user is registered, and if true returns 2.

You want it to be that the system will return a status (isRegistered would return a 3, isMod would return 4, isAdmin 5, isDonator 15, etc) and then it would load that from a specific location (maybe in the file system, maybe from an outside source) with the name equal to the int value of the level

**Comment by woogerboy21** [comment]
@ZeldaZach correct

**Comment by woogerboy21** [comment]
Here is a snippet of the pixmapgenerater:
```
else if (userLevel.testFlag(ServerInfo_User::IsRegistered))
        levelString = "registered";
```

So what is happening is its doing a userlevel check.  the db is quried and if the value in the db returns 2 the user is considered registered and then the levelstring is set to "registered" which is what happens to be used for the actual icon lookup.  If we want to be able to use  other values than the ones hard defined in the  proto file we need to change the checks to be a simple greater than value verification (cause unregistered users will never show up in the database and never have a value returned) and from there can build on how to handle each user level.  I have yet to look at the scope of making such a change and how it affects the code logic on determining if a user is a higher privileged user (such as admin or mod)

**Comment by ZeldaZach** [comment]
It's possible we can have an additional flag/string with "bonusPowers" or something that can return "mod" or "admin"

**Comment by woogerboy21** [comment]
I was thinking more along the lines that moderator will always be a specific value and admin will always be a specific value.  So you may have 0 for an unreg.  1 for admin, 2 for mod and then anything else is a registered user level.  we may want to start with something like 10 to allow for additional privileged levels that we have yet to think about.   (something along those lines)

**Comment by ZeldaZach** [comment]
That's fine by me, just throwing in some ideas. My idea could also be thrown along the lines of a secret moderator. Similar to how phpbb forums work, you have "visibleRank" and "hiddenRank" which both use the same levels. If your visibleRank is, lets say, unregistered and your hiddenRank is moderator, you'd look like an unregistered person but have mod tools. Maybe some server owners would like something along the lines of that potentially.

Otherwise, I'm fine with starting at like 10 or so for custom ranks. Seems like a good idea :)

**Comment by woogerboy21** [comment]
So you want spy's? :smile:

**Comment by ZeldaZach** [comment]
Problem? :smirk_cat: :smirk_cat:

**Comment by woogerboy21** [comment]
So would it be advisable to revamp the current code logic or extend the user db table and add a field for user levels?  Thoughts.... opinions...

**Comment by woogerboy21** [comment]
So before digging into this to deep lets make sure we are all on the same page when it comes to terminology (as this was pointed out to me).  The goal of this is to first determine what user role the user should be and then from there understand what privileges the users role should have.

Does that clear things up for everyone?

I've been asked or heard mention that we are wanting to decouple users from role's and I don't believe that is an accurate statement thinking through this.  As I would want different role levels and under those roles different role rights.  So you could have something like a user with customized settings or a admin with customized settings. Since there is not a definition as to what "settings" mean as it is unclear what settings are available should we try and focus on figuring that out and defining that first?

**Comment by woogerboy21** [comment]
So the more I think about this, the more I am leaning against the idea of breaking protocol and sticking with keeping the existing enum's in place and creating something like a database table that contains the ranks and the associated users with those ranks.

**Comment by woogerboy21** [comment]
@poixen : to your svg point, i think including the default svg's in the DLLs would still be necessary.  Since the idea is to allow operators to define there own there still needs to be a set of base svg's that are used in the event no customization occurs.

**Comment by ZeldaZach** [comment]
I'd consider the base of this done.
