### ISSUE TITLE
Servatrice Dock Status on OSX doesn't respond as expected

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1195]
When you run servatrice from the application on OS X 10.10+ it seems as if the application continues to bounce on the dock and when you right click it shows the "Application not responding" message, even though the server is up and fully functional.

In addition, it seems that whenever I start the application, it asks me to allow incoming connections and won't remember my choice. Firewall doesn't seem to give servatrice a chance to "always allow incoming connections," like, for example, Skype.

**Comment by ctrlaltca** [comment]
Running servatrice from the GUI is suboptimal anyway, since you can't pass parameters to it.
About the first issue, we could make it open a terminal window when starting, or add to servatrice a very small, optional GUI for starting/stopping the service.

About the second issue, you need to codesign servatrice to permit it to always open the firewall: https://developer.apple.com/library/mac/technotes/tn2206/_index.html

**Comment by ZeldaZach** [comment]
I don't think this really matters anymore
