### ISSUE TITLE
Cards with commas do not appear

### ISSUE THREAD

**Issue by altf4** [Cockatrice/Cockatrice#1266]
Using default settings for the custom image download URL, any magic card with a comma in the name does not load. Such as "Urborg, Tomb of Yawgmoth" and "Nissa, Worldwaker".

If I manually download an image and name it "Nissa, Worldwaker.png" and stick it in ~/.local/share/data/Cockatrice/Cockatrice/pics/downloadedPics/TK then the image does successfully load into Cockatrice. So the problem seems to be in the downloading.

I'm on version: Version 4cf92de (2015-07-06) on Ubuntu 15.04 x64

Thanks!

**Comment by altf4** [comment]
Running in terminal with the -v flag on, I get error messages that say:

```
Trying to load picture (set:  "TK"  card:  "Xenagos, God of Revels" ) 
Picture NOT found, trying to download (set:  "TK"  card:  "Xenagos, God of Revels" ) 
starting picture download: "Xenagos, God of Revels" Url:  QUrl( "http://gatherer.wizards.com/Handlers/Image.ashx?name=Xenagos%2C God of Revels&type=card" )  
Reading ras files from sequential devices not supported
Reading ras files from sequential devices not supported
Reading ras files from sequential devices not supported
Reading ras files from sequential devices not supported
```

You can see that manually copying in the URL "http://gatherer.wizards.com/Handlers/Image.ashx?name=Xenagos%2C God of Revels&type=card" into a browser works, so maybe there's some encoding issue? (The browser will URL encode it for you)

**Comment by altf4** [comment]
Actually, perhaps that's the problem. Notice that the comma is already URL encoded to %2C above in the URL. Cockatrice might be trying to URL encode it AGAIN when actually loading the URL, malforming it. Notice that the spaces are not encoded in the above links, and are shown as spaces. They must be getting encoded, implying that the percent would, too.

**Comment by altf4** [comment]
I think the double encoding comes from here:

https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabase.cpp#L343

That function encodes the URL, which is then fed into Qurl and and QNetworkRequest. According to a quick Google search, Qurl and QNetworkRequest do the encoding for you:

http://stackoverflow.com/questions/13239235/qnetworkrequest-and-qurl-encoding-c

So that would double-encode it.

**Comment by ctrlaltca** [comment]
Thank you for the report and the analysis of the problem.

The first thing that i notice is that your cards/tokens database is somehow borked, since those cards are present in the TK (tokens) set, instead of their correct one (eg, M15 for Nissa).
The second thing is that Cockatrice tries to load card images using their "multiverse id" by default, while your log shows that cockatrice is fallbacking to using the card name; this means that the card has no muid set, or has an invalid muid. This is a second symptom of a problem in the card database.

So, i've tried to corrupt my database to force cockatrice into loading that card image using its name, and it worked: the image was loaded successfully. Not sure why it doesn't for you, but maybe the "Reading ras files from sequential devices not supported" warning could be a hint.

About QUrl being able to encode query parameters by itself, this is true, but we're not adding parameters to a QUrl object, we are creating a full url string and then feeding a QUrl with it. In this case, if we don't percent encode the parameters before putting them in to the string, a card name containing eg. = or & would break the url.

One last thing: if the download failed, you should see a "Download failed" message in the console.

**Comment by altf4** [comment]
Yup, that was the problem!

Somehow I didn't have a card database. The location of it was just blank in the general settings screen. I deleted the whole ~/.local/share/data/Cockatrice/ folde, restarted Cockatrice, made an empty cards.xml file somewhere, gave that path as the cards database location, reloaded card images, and it worked!

Though perhaps you could still call this a bug in the "search by name" fallback mechanism. Up to you.

Thanks!
