### ISSUE TITLE
Update for C++11 compatibility 

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#127]
Currently the project mandates C++98 mode. 13 years is a long time...

**Comment by Daenyth** [comment]
We should revisit this and see whether compiler support is still an issue given that we're on Qt5 and (only sort of) Qt4.

I'm probably ok with dropping Qt4 support if that means we can do modern C++

**Comment by VanNostrand** [comment]
The first g++ that is nearly feature complete for C++11 is version 4.7 (https://www.gnu.org/software/gcc/gcc-4.7/cxx0x_status.html) and it is the first g++ that allows the switch -std=c++11 instead of -std=c++0x. It has some quirks though (it needs some additional motivation to enable the std::chrono namespace to name one example).
The first clang compiler that is feature complete is clang 3.3. (http://clang.llvm.org/cxx_status.html)
On the Windows side the requirement should be increased to Visual C++ 13 (it lacks some features: http://blogs.msdn.com/b/vcblog/archive/2014/08/21/c-11-14-features-in-visual-studio-14-ctp3.aspx but at the same time it can use clang as compiler with some issues: http://clang.llvm.org/docs/MSVCCompatibility.html)

It might be interesting to go to C++14 instead (https://en.wikipedia.org/wiki/C%2B%2B14), because I never understood why make_unique did not make it into C++11, just to name one example.
That would require clang 3.4 (http://clang.llvm.org/cxx_status.html#cxx14) and g++ 4.9 (https://www.gnu.org/software/gcc/projects/cxx1y.html) - though generally: the newer the clang version the better the features, especially in the additional tools like scan-build and clang-modernize to name two.

clang-modernize is a tool that can convert parts of the code to modern C++: http://clang.llvm.org/extra/clang-modernize.html and scan-build is a tool for static code analysis to help find bugs: http://clang-analyzer.llvm.org/scan-build.html

If you want to get into modern C++ I recommend all videos from Herb Sutter and Scott Meyers about modern C++ C++11/14, e.g.
https://channel9.msdn.com/Events/Build/BUILD2011/TOOL-835T (good starting talk)
https://www.youtube.com/watch?v=TJHgp1ugKGM
https://www.youtube.com/watch?v=xnqTKD8uD64
https://www.youtube.com/playlist?list=PLmxXlAVb5hkyq5njldMEPYdOqTAQPLChR (the very best series; one video lost 30 minutes, sadly)

A good migration strategy would be for all the graphical programs
1. Let clang-modernize do it's job and test if the source still works
2. "auto" everything on the left side of the = symbol while the source compiles (C++ is going to move the type to the right side, don't worry, it is not misuse of auto)
3. get rid of all new and delete occurances and use make_shared instead
4. use the <algorithm> header to get rid of old style loops (use for_each, find_if and such now)

The server code should probably stay a bit backwards because if someone is using an enterprise(-derived) distribution to host a server than the compiler is probably really old. Same goes for the build tools. I would have been forced by a project to use a more recent cmake on SLES11 some time ago (don't know, maybe it was 2.8 even) to compile a stupid library and of course this does not work at all on an enterprise system.

**Comment by Daenyth** [comment]
@woogerboy21 runs servatrice on centos but he should be able to get it working however is needed.

**Comment by Daenyth** [comment]
Does it make sense to at least move to C++0x first? Would that help us migrate?

**Comment by VanNostrand** [comment]
C++0x is the pre-standard of C++11. There should be no reason to use the compiler switch with the same name because if the compiler does not know the c++11 switch, then it also does not support C++11 completely. The interesting question is rather if the C++14 extension should be used.

**Comment by tooomm** [comment]
(There had been thoughts about C++11 in a shuffle thread as well: https://github.com/Cockatrice/Cockatrice/pull/59#issuecomment-37120928)
