### ISSUE TITLE
Change reveal top card from ctrl + n to something not next to mull..

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1278]

**Comment by Daenyth** [comment]
ctrl+n seems very unintuitive for this anyway

**Comment by ZeldaZach** [comment]
When I get back I plan on getting shortcut overrides into place to change defaults to what you want them to be

**Comment by anoda9** [comment]
Another idea would be to assign mulligan to Control-Shift-M to reduce the chance of hitting it accidentally. Since it's only used a few times each match, the added key complexity wouldn't matter too much, but it would reduce the number of "accidental mulligan" situations.

**Comment by ZeldaZach** [comment]
I like the idea @anoda9

**Comment by Daenyth** [comment]
I like the concept but migrating is hard for people who have combos
memorized

**Comment by anoda9** [comment]
There's certainly a cost to this change, but it's a very small cost, and I think the benefits definitely outweigh it. I really don't think it will be very hard for people to adjust, as the change from Control-M to Control-Shift-M is pretty intuitive. We can add a notice in the opening server announcement to educate users, and players can educate each other as well. I understand that the "we did it wrong the first time, but we can't change it now because the userbase is too used to it being the other way" argument is often a necessary concession to practicality, but in cases where the cost of changing is so small, I think it loses a lot of validity.

**Comment by ZeldaZach** [comment]
I'm all in with @anoda9's plan personally. @Daenyth Let em struggle for a bit ;P

**Comment by ctrlaltca** [comment]
I cast my vote against changing the hotkey, even if its' better, for these reasons:
 * long time players will feel like we pissed them off, and since they won't have a way to roll back the change we'll hear the usual screaming that it always worked with ctrl+m, there was no need to change it, their shift button is broken and now the can't prepare for the next GP, their cat died because of this, their gf left home, aliens, grasshoppers anywhere, etc..
 * the (long time planned) solution is implementing a preference page where the user can change the hotkeys. Once this is implemented, we can also change the default, but at least people will be able to use the old keys if they want.

**Comment by ZeldaZach** [comment]
What if we change it and leave a note on the <kbd>CTRL+M</kbd> command that adds a message to the chat (Mulligans can now be accessed by hitting <kbd>CTRL+SHIFT+M</kbd>)

**Comment by anoda9** [comment]
@ZeldaZach that's a great idea. 

>long time players will feel like we pissed them off

I might be out of touch, but I can't really imagine users being that upset over such a minor change. If we remapped every shortcut to something new, sure, I would certainly expect a big reaction, but adding a single shift to one shortcut? I don't really see it.

**Comment by Daenyth** [comment]
We usually get some "shit's broken" bug tickets whenever we make a change,
plus people grumbling for a few weeks in the chat until the upgrade reaches
wide penetration.

I'm not opposed in principle.

I'd dearly like have time to work on the keyboard shortcuts. KDE's shortcut
configuration panel is pretty awesome. I think intellij uses a similar
model.

Unfortunately it's going to be a metric shit-ton of grunt work that no one
really wants to do

**Comment by ZeldaZach** [comment]
An idea could be this:
> While I do agree a mid-game mulligan ends the game essentially, maybe we can look into preventing the mulligan command from being called if there are cards in play?

If there are any cards on the battle field, the Mulligan command should be disabled and return "Mulligans can not take place when cards are on the table" or something similar. Thoughts?

**Comment by poixen** [comment]
I usually mull if someone plays time twister or days undoing to draw an initial hand.

**Comment by anoda9** [comment]
>If there are any cards on the battle field, the Mulligan command should be disabled and return "Mulligans can not take place when cards are on the table" or something similar. Thoughts?

That's a good idea/direction to go in. Perhaps instead of being completely disabled once the game has started, it just requires a confirmation message to use it? i.e. a pop up with "are you sure you want to mulligan?" 

I actually like that solution better than remapping the original shortcut. The only tricky part is deciding what criteria to use for determining when a game has started or not. Having cards in play might be an issue for EDH, as players usually pull their general out of their deck before mulliganing (as well as creating tokens for their initial die rolls and general damage.) 

Maybe the criteria could be - both plays have hit "end step" at least once? People use crtl-enter to pass the turn back and forth before the game has begun a lot, but the "end step" phase usually only gets hit once the game has actually started. 

Or critera could be - any player has hit "end step". Or - any player has changed the phase (to something other than untap).

**Comment by Daenyth** [comment]
We could just avoid the confusion and make undo easier as well. Though it's
more of a burden on the server. Not ideal still, dunno. I think checking
for each player padding turns and then if they do it then perform a popup

**Comment by ZeldaZach** [comment]
A new ticket related to "Add popup to mulligans if there are cards on the field" can be created by someone.
