### ISSUE TITLE
Ban Timer not displaying correct unban dates

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1283]
In the Web UI, I set a ban for 6 months, however, when I go to log into the server in-client, it says I am only banned for a little over a month.
![untitled](https://cloud.githubusercontent.com/assets/10480542/8808699/cb1578fa-2fa9-11e5-9447-14e1333a8244.jpg)

The entry in the Web UI looks like:
![untitled2](https://cloud.githubusercontent.com/assets/10480542/8808713/dc3073ec-2fa9-11e5-8adb-441cfa418bf5.jpg)

(262974 minutes is 6 months, by the way)

**Comment by woogerboy21** [comment]
Just a note:  The DB field is showing the correct time (as also sen in the web ui).  So chances are this is a calculation issue with the client error display.

**Comment by ctrlaltca** [comment]
The date reported to the client is correct when the user is banned. When the client tries to reconnect, the returned time is wrong.
The problem is due to the query in ```Servatrice_DatabaseInterface::checkUserIsNameBanned()``` use of the timediff() function; from https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_timediff:
```
The result returned by TIMEDIFF() is limited to the range allowed for TIME values...
TIME values may range from '-838:59:59' to '838:59:59'
```
So, the function is limited to returning values up to 34 days (839 / 24 hours).
