### ISSUE TITLE
If a user is ignoring me, should I be able to see their game in the lobby?

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1314]

**Comment by MassCraziness** [comment]
I think, by default, they should be hidden. However, I think there should be a toggle to be able to view them so a moderator can close the room if need be (if they're on ignorelist).

That poses a question, can moderators join rooms of people who ignorelist them if they have moderator functions on?

**Comment by Daenyth** [comment]
You don't know who is ignoring you and I'd like to keep it that way

**Comment by poixen** [comment]
You do, you click to enter a game, and the client tells you "the creator of this game is ignoring you".

Well, if I cant join the game, why do I need to see it?

**Comment by Daenyth** [comment]
You don't know a priori who is ignoring you, only on an as-needed basis. I
don't think it's a benefit to the community as a whole to make ignore lists
public. It's going to lead to trolls having extra ammo for harassing people.

**Comment by ctrlaltca** [comment]
I agree with @Daenyth

**Comment by anoda9** [comment]
Imo they should be hidden (except if you're a moderator). Since you can't join them, there's no reason for you to see them. 

@Daenyth I can't tell if you are for or against hiding the rooms. To me it seems like preemptively hiding the rooms accomplishes the "You don't know who is ignoring you" goal better than not hiding them. Also, how would ignore lists become public?

**Comment by Daenyth** [comment]
In order for the client to hide rooms that are created by someone ignoring
them, the server needs to tell them that they are being ignored before they
try to join. If the server doesn't tell the client that the game exists,
then they'd be unable to join it even if they are taken off the ignore list.

I suppose we could consider not sending the game to the client, but I'm not
sure if it's worthwhile

**Comment by woogerboy21** [comment]
I didn't think the code actually sends the game list on a user by user basis does it?  I thought it is a room event that is broadcast to everyone in the room.

**Comment by Daenyth** [comment]
It's a room event

**Comment by FrozenSlave** [comment]
Actually you can know who is ignoring you by checking and pming people, then you return the favor and ignore them.

**Comment by FrozenSlave** [comment]
also i wonder how Ctrlalt is i do not recognize his name as a user on cockatrice

**Comment by Nightfirecat** [comment]
@FrozenSlave Please do not spam unrelated issues with separate concerns. We have already addressed the issue you raised - please follow up with the advice there.

**Comment by FrozenSlave** [comment]
was very related he asked about people ignoring him.

**Comment by woogerboy21** [comment]
@FrozenSlave The discussion here is not on how to find out who is ignoring you.  Its about the code and how a users client is told who is ignoring them and when.  The client itself has no knowledge on who is ignoring the logged in user till an action is attempted and the server processes the action returning the desired results.  For example, if you see a game in the game list and attempt to join it or if you private message a user, the command is sent to the server which in turn determines if the user is being ignored and if so is returned the ignore results.  Contrary to the original question being asked of "should the game be presented in the games list if a user is being ignored by the creator".  Which is not possible at this time since the game listing is sent as a room event by the server and is not tailored to each individual user and as such would require the list of ignored users to be sent along with it so that the client side code could filter out the game listing based on the user logged into the client.

As stated by others (and I agree) we should not be sending the list of ignored users to the client for processing.

**Comment by Daenyth** [comment]
@woogerboy21 I do this it's relevant, it's not just about the code.

@FrozenSlave yes you can PM to check but again it's not a priori knowledge. You need to message everyone you suspect of ignoring you. We could even change it to not tell you that your message wasn't delivered. You're not going to message every user on the server to see who is ignoring you.

I'd like to restrict this to the minimum level needed - which it is at right now. I don't think it serves the community to make lists public.
