### ISSUE TITLE
Game created in cockatrice

### ISSUE THREAD

**Issue by Crovax58** [Cockatrice/Cockatrice#1319]
It's me again I saw that I needed the latest version of cockatrice to play and uninstall the old I would get back all my decks created. What file do they find? Thanks for your help.

Best regards

**Comment by Daenyth** [comment]
What was your old version? Was it older than June 2014? If it was, and if you stored your decks in Program Files/Cockatrice/, then the files are deleted and can't be recovered - we've posted warnings about this with every update since we found the issue.

I don't understand what question you're asking.

**Comment by Crovax58** [comment]
Euh I'm french I understand I have a old version and I got the latest version and my games that I created are now without me to do anything. Thank you for your help anyway. Good day !
