### ISSUE TITLE
Alternative way of brewing (including cooperative deck building)

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1368]
Apparently my other topic/issue got locked but here we go again. Can we have an option in the "settings....Deck editor section" that allow us to have a 1 player game with unlimited card stacking on a table like surface. Allow this room to be "viewed by other players, whom we can invite even" that would allow for "teams" to be able to adjust deck better. it would put the huge game library away and you just type a card name and you get the card to put on the filed you can copy/clone the copies so that lay them out in CMC order and figure out stuff lie mana curve, removal/creature ratio, color ratio, and many other things. Putting it in deck editor would make it an offline feature so that people do not need to use deck.stats, not everyone is always online. I think the introduction to this kind of tool would be confusing yes but over time it would make use all into better players.

**Comment by Daenyth** [comment]
So to summarize:

An alternative deck view,
- table style layout instead of deck listing
- Make it visible like a game room to show people
- Offline version of deck stats

To address in order:
- table layout: This is doable but I'm not sure it would benefit a lot of people
- Making it visible - this would require some large structural changes across the entire application and server, it's a ton of work
- Offline version of deck stats: I'm not sure I'd like to add this. It's a fairly complex operation that the website does quite well. It's also extremely magic-specific and I'd like to move us in a direction that supports more games in general ways rather than more game-specific peripheral things (not related to gameplay mechanics). While people aren't online all the time, I don't think it's unreasonable to expect people to be online most of the time, or at least often enough to make the feature useful. We don't run deckstats.net, they're unrelated to us - we just have the ability to submit a deck list to their site. We'd have to write a lot of features that we don't have right now

This does sound a bit interesting, but it's a large amount of work and in my eyes gives very little benefit. Of these ideas, the table layout view for decks is most interesting but even by itself, as an offline feature, it would be a lot of work. 

Frankly given the work/reward ratio on this I don't expect that anyone currently working on the project will take it on. You're welcome to work on it yourself and submit a PR with the changes, which we can then review. If you'd like to work on that I recommend treating the 3 points separately and starting with the table layout deck view offline.

**Comment by LestatTheDarkPrince** [comment]
If i had any clue how to do it i would already have done it. I only suggested it mainly because building decks in that mater has helped me become a better player and i figured that would be a good thing to spread.

**Comment by Psithief** [comment]
I think most of the benefit of this is already achieved through online deck-building apps. I think the major problem is that *they* haven't attempted to make their apps offline compatible.

**Comment by tooomm** [comment]
This has similar follow up tickets:
Like https://github.com/Cockatrice/Cockatrice/issues/1732 and https://github.com/Cockatrice/Cockatrice/issues/2883

In comparison this is also includes the aspect of cooperative deck building with other people, which is very interesting!

**Comment by ZeldaZach** [comment]
This seems too complicated for what it is unfortunately. Might be left better to an external service.
