### ISSUE TITLE
Remembering last game values

### ISSUE THREAD

**Issue by Shomotion** [Cockatrice/Cockatrice#1396]
In one of the recent updates, you guys added a feature where the client remembers what you put in for the last game you made but there's no place in the settings to disable this if we don't like it. It would be great if this could become a checkbox somewhere in the settings.

**Comment by ZeldaZach** [comment]
You're free to use the "clear" button to reset the information, but yes I do agree this should be configurable.

**Comment by tooomm** [comment]
I would like to see this most inside the game creation dialog as `Remember settings for next game` checkbox, because that's a feature you don't want to enable or disable totally in general. (You still could if you just leave the checkbox unchecked all the time)

Most of the time you just want to create one particular game without overriding your creation settings. Then you could create a fast game for testing something or play a draft game in between your modern deck sessions (which settings are stored and you would like to keep) for example.

A store/load feature with simple buttons or a "history list or profiles" like in the `connect...` dialog are imaginable as well.

**Comment by Daenyth** [comment]
I don't want to make it too complicated; adding new workflows has a cost associated with it. Too many multi step processes make the software confusing for more basic users.

I think the proposal of the "Remember settings for next game" checkbox on the create game modal is a good sweet spot in terms of feature value vs UX weight

**Comment by ZeldaZach** [comment]
cc: @Fizztastic
