### ISSUE TITLE
Create issue from the client

### ISSUE THREAD

**Issue by marcofernandezheras** [Cockatrice/Cockatrice#1413]
Implement a dialog to make an issue here, using [github api](https://developer.github.com/v3/issues/#create-an-issue).
We can create a github account just to post these issues allowing people without a github account create an issue.
Also that way we can append client version (and, maybe, check if it's an updated one) , OS... to the issue text rather than asking every time to the issuer.

**Comment by ctrlaltca** [comment]
First, sorry for the 5 years it took to look up this issue :)
Anyway, I think this is not a good idea because:
 * hardcoding the account informations inside the client would make them public;
 * the credentials cold be used to spam this and any other repository on github.
 * we would have no way to ensure the quality of the issues;

While having to create a github account is a barrier for users willing to report an issue, it also filters out all the dummy reports where an user just needs some help. In those cases, using one of the other support channels (internal chat / gitter / discord) is probably a better idea anyway.
