### ISSUE TITLE
Open Cockatrice on .dec/.cod Double Click

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1453]
On Macs, if you double click on a deck file, it will say no program is able to open it. I propose we update Cockatrice to allow for it to open these deck files and show them directly into the Deck Editor screen.

I'm assuming Windows/Linux can follow the same protocol.

**Comment by Daenyth** [comment]
And probably platform-specific code.

**Comment by LPGhatguy** [comment]
This can be solved on Windows _solely_ with #1450.

**Comment by skwerlman** [comment]
on linux, you can use `xdg-open` which is provided by most distros

**Comment by ctrlaltca** [comment]
This needs some form of inter process communication. When an use double clicks on deck.dec and wemake the operating system execute "cockatrice.exe -f deck.dec", we need to check if cockatrice is already running and open the deck in that instance of the application, instead of opening a new instance.

**Comment by mpalmujoki** [comment]
Guess this is not happening?

**Comment by ZeldaZach** [comment]
This is gonna be a dupe of #1450 but I still want this to happen!
