### ISSUE TITLE
Keyboard shortcuts not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by catmanjan** [Cockatrice/Cockatrice#1477]
When I press ctrl+i to roll the dice it types an "i" in the chat box, even if the chat box does not have focus.

May be stealing focus per some Ubuntu user preference, but this was a fresh install (of Ubuntu).

**Comment by ctrlaltca** [comment]
Your cockatrice version is? Can you check if in the settings window the key is binded correctly?

**Comment by catmanjan** [comment]
I built from source just before I made the issue, so whichever version that was. The bindings appeared correct in settings - the binding is even displayed in the context menu, but is still not triggering.

**Comment by Daenyth** [comment]
Run `git status` to get the version from the source directory.

**Comment by catmanjan** [comment]
jan@u31sd:~/Cockatrice$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

Just replicated it on another Ubuntu VM

**Comment by Daenyth** [comment]
Blah, I meant to say `git show HEAD`.

Either way if it's a recent commit it should just be in the client's about
menu as we mentioned before.

**Comment by catmanjan** [comment]
@Daenyth Where was that mentioned? Are you sure you're responding to the right issue?

commit dd4900b038668078467648d3787de9ebc51919fc
Merge: 15e8121 e50d0c6
Author: woogerboy21 <woogerboy21@users.noreply.github.com>
Date:   Sun Sep 6 08:25:48 2015 -0400

    Merge pull request #1471 from ctrlaltca/deckeditor_theme_cardback
    
    get cardback image from theme

**Comment by Daenyth** [comment]
Sorry, I thought we mentioned it in this thread.

**Comment by tadiou** [comment]
Just curious. I've been bisecting back... way back. Granted I'm not trying fresh installs (and i'm not sure that it's not overwritten completely on each install/totally not familiar with the codebase). On Ubuntu 15.04.

Funny that, ctrl+enter works on the deck selection page, but, that's it. Nothing works in the deck editor or in game, makes me think that it's something else, because I know I made something past summer magic actually work, but i can't remember what.

fb7de2a works.
ea8c55b doesn't. 82 revisions between the two. (i'm probably gonna comment and actually find the revision where it broke and let y'all know later)

**Comment by ZeldaZach** [comment]
Thanks for your efforts, @tadiou

**Comment by tadiou** [comment]
Bisect log

# good: [fb7de2ad1db0b75ac490ba99fff28e14195a9fd7] Merge branch 'windows-nsis-fix'
git bisect good fb7de2ad1db0b75ac490ba99fff28e14195a9fd7
# bad: [7ce9d3749ecc7fb19dd365bf1f6a5af6437579ef] Fixed "analyze on deckstats"; Fix #662
git bisect bad 7ce9d3749ecc7fb19dd365bf1f6a5af6437579ef
# bad: [66aba2eec7cdf8914d69828fcc235b69b27d0b76] Merge remote-tracking branch 'upstream/master' into translation
git bisect bad 66aba2eec7cdf8914d69828fcc235b69b27d0b76
# bad: [9ba2ae71a870c2c67714ce474ff6220140767293] Merge pull request #244 from ctrlaltca/cards_xsd
git bisect bad 9ba2ae71a870c2c67714ce474ff6220140767293
# bad: [ea8c55b2c98507dcac08a86cfb669cf43bb4e634] Merge remote-tracking branch 'upstream/master' into cmake_qt5
git bisect bad ea8c55b2c98507dcac08a86cfb669cf43bb4e634
# good: [73e5e12c24af193658798850c2eec0e7159e34c5] Merge pull request #199 from arxanas/remember-game-filter-preferences
git bisect good 73e5e12c24af193658798850c2eec0e7159e34c5


73e5e12c24af does not display the bug. d894c5326 does, and they're right next to each other. 2014-08-08

**Comment by ctrlaltca** [comment]
d894c5326566d5ba56925cfed0358c8cd787da3c is a servatrice-only fix.

**Comment by tadiou** [comment]
That's strange. Because one build works for me, the other doesn't.

I'll try to investigate further and bisect more during my spare time today.

**Comment by catmanjan** [comment]
Still not working, ask in this thread if you don't have a Ubuntu test environment yourself...

**Comment by ctrlaltca** [comment]
Reopening: need further testing

**Comment by marcofernandezheras** [comment]
Tested on: (lsb_release -a)
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

Desktop xfce4

working fine here...

**Comment by catmanjan** [comment]
Doesn't work on a fully updated stock copy of 14.04, nothing else installed

**Comment by Daenyth** [comment]
Bizarre. I'll see if I can get some time to run 14.04 in a VM and test it. I haven't heard of anyone else having this issue, I don't think...

If you use the configurable shortcuts, do the configured keys work?

If you try another keyboard, does it work?

**Comment by catmanjan** [comment]
Everything is stock, Ubuntu, Cockatrice - I've tried a second keyboard (do you really think keyboard support is broken in Ubuntu/QT haha?), same result.

**Comment by Daenyth** [comment]
I was wondering if your keyboard had a problem.

**Comment by ctrlaltca** [comment]
So, i lost some time to work on ubuntu 14.04 in order to make the creation of a proper package possible, and checking also this problem related to shortcuts; i only tested qt5.

> do you really think keyboard support is broken in Ubuntu/QT haha?

Yes, it is: https://bugs.launchpad.net/appmenu-qt5/+bug/1380702
They created a compatibility package named "appmenu-qt5" to make qt5 apps show their menubar entries in ubuntu's "global unified menubar"; this unfortunately breaks accelerators (keyboard shortcuts).
The bug is one year old, they know the specific problem and possible ways to fix it, and a guy is working on it.
By now, the only known workaround is to ``` apt-get remove appmenu-qt5``` until they get this bug fixed.

**Comment by tadiou** [comment]
This would explain why I had no problems in XFCE on my last computer.

Thanks for the update.

**Comment by jacebenson** [comment]
Thank you @ctrlaltca ctrlaltca for the info.  Removed that package and now the shortcuts work.  
Been super frustrating playing w/o shortcuts.
