### ISSUE TITLE
[woogerworks] mac is not an os

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#1489]
http://woogerworks.com/?option=com_content&view=article&id=91

> Which operating system are you running?

> Windows

> **Mac**

> Linux

**Comment by woogerboy21** [comment]
LoL.  Shall I call it something else?

**Comment by aeosynth** [comment]
i mean, you could just change mac to osx

**Comment by woogerboy21** [comment]
Your really looking to confuse most Macintosh users I see

**Comment by ZeldaZach** [comment]
You can change it to "Mac OS X" i guess... doesn't really matter tbh

**Comment by woogerboy21** [comment]
Oh this is a serious issue post?

**Comment by aeosynth** [comment]
smh

**Comment by woogerboy21** [comment]
@aeosynth So here's the deal.  I understand that Mac is not the actual name of the operating system.  The problem is the target audience that comes to download the client.  The majority of the users that hit the site are most likely around the early teen years of life and when you put OSX up for the operating system name I get a lot of contact us messages saying "im trying to download the software but I have a mac and dont see that listed".

Im more than willing to change it to Mac OS X if it really bugs you that much.  I seriously thought you were joking.

**Comment by aeosynth** [comment]
you can have 'mac' as an option without referring to it as an os. this is sloppy.
