### ISSUE TITLE
Some hotkeys are bugged after last client update

### ISSUE THREAD

**Issue by Pauperist** [Cockatrice/Cockatrice#1493]
some of the P/T setting hotkeys don't work, namely the altGr+ + and ctrl+ +, also the attach command ctrl+a doesn't work. this happened since the last client update about one week ago... also, trying to watch a replay crashes the program. Thank you for your attention!

**Comment by ZeldaZach** [comment]
Replay bug will be addressed in the next release (sometime this week).

The hotkeys should work, unless you're on Mac OS X, in which case some don't work as expected. In this case, you can re-assign the commands.

**Comment by tooomm** [comment]
what's the deal with shortcuts on osx @ZeldaZach ?

**Comment by ZeldaZach** [comment]
Some defaults don't work on OS X, so you can custom set them to your likings.

**Comment by Daenyth** [comment]
> Some defaults don't work on OS X,

We should change them when on OSX then. The defaults should always work.

**Comment by ZeldaZach** [comment]
We've talked about that for years @daenyth. What should we do then?

**Comment by Daenyth** [comment]
Is there a ticket for it? If not let's make one; either way we can get to it eventually as with anything else.

**Comment by ctrlaltca** [comment]
Just tested the cited shortcuts on mac, and they mostly works. The only problems i found are:
 * ctrl+a (cmd+a on osx) doesn't work when the massage input is focused, because the same hotkey is binded as "select all text" in that widget;
 * in some keyboard layouts the ALT key is used to form different characters; eg. in the italian layout, pressing ALT and the "+" button is used to get the "]" character. By default both an hotkey for ctrl+alt+plus (increment p/t) and one for ctrl+] (rotate view) are defined, and those collides.

Imho both these situations are problematic.
The first problem could be solved changing the default to something similar, like ctrl+alt+a;
The second problem could be solved changing (or removing) the hotkey for rotate view;

**Comment by Daenyth** [comment]
I'm fine with unbinding "rotate view", it's a fairly rare action anyway
