### ISSUE TITLE
Cannot set card/deck back image

### ISSUE THREAD

**Issue by institute** [Cockatrice/Cockatrice#1519]
The latest version of Cocktarice has moved top themes instead of setting each zone image separately. Unfortunately the ability to choose a card/deck back image seems to have disappeared as well. My card backs are just a flat gray now.

**Comment by ctrlaltca** [comment]
This was due to an already fixed bug (see #1507). The ability to set a custom image for card back is now integrated with the themes functionality that, unfortunately, is still missing some good documentation.

Here's some related informations from a recent ticket: https://github.com/Cockatrice/Cockatrice/issues/1470#issuecomment-138059026

**Comment by ctrlaltca** [comment]
Just an additional information: themes are now loaded from both the application's bundled themes directory and from the "themes" subfolder in the user profile.

I'll keep this ticket open until we get some proper documentation available on how to work with themes.

**Comment by ZeldaZach** [comment]
I'll work on documentation soon

**Comment by ctrlaltca** [comment]
Started writing some documentation here: https://github.com/Cockatrice/Cockatrice/wiki/Themes

**Comment by alvaro-cuesta** [comment]
This was fixed for me in the latest Woogerworks build.
