### ISSUE TITLE
Add a "Run 'Cockatrice' now" after updating the cards/tokens with Oracle

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1531]
If you install Cockatrice and run Oracle afterwards, or when you manually run Oracle it'll just end when you're finished and doesn't offer to start the Cockatrice client.

Most of the time you install Cockatrice (or update your card database manually=run oracle manually) because you want to use the application/the new cards immediately afterwards. :)

[Like at the end of the Cockatrice installation.](https://github.com/Cockatrice/Cockatrice/blob/master/cmake/NSIS.template.in#L20)

**Comment by Nightfirecat** [comment]
:+1:

**Comment by ZeldaZach** [comment]
So like a checkbox that will launch the program?

Also, it will have to know where the client is, so it's not so simple...

**Comment by tooomm** [comment]
Right now Cockatrice offer to run Oracle after the client installation finishes. And it needs to know where Oracle is as well.
So we have it working the other way around and it shouldn't be too difficult to adopt?

**Comment by Daenyth** [comment]
This could work. For a small version it can just launch the app. Future
version could check if it's already running and tell it to refresh. But now
launching is good

**Comment by ctrlaltca** [comment]
I see this as a nice improvements:
 1. installer finishes and offers to run cockatrice (so the user doesn't need to find trice on the start menu)
 2. cockatrice starts, and on startup checks for a card database as usual
 3. if the card database is not found, instead of popping up the "gimme the card database path" settings dialog, it could tell the user "hey you need cards, do you want me to run oracle for you?"
 4. (Future implementation) on startup, check if the card database is out of date and propose to run oracle also in this case

This workflow sounds more user-friendly to me that just proposing to run oracle and letting the user guess that he needs to find cockatrice hidden somewhere in the start menu

**Comment by tooomm** [comment]
This sounds very user friendly and like the better implementation! :+1: 
...because the user wants to run trice, not Oracle in the first place... they likely don't even know about Oracle.
Actually the user doesn't need to know about Oracle and where to find the .exe etc., we have a button in the UI to update the database and run Oracle already.

Nice description and roundup.
