### ISSUE TITLE
OS X Shortcut Malfunction

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1581]
I'm not able to pinpoint what happened, but it seems that the inputs are now altered incorrectly on OS X 10.10.5.

<kbd>Alt + P</kbd> results in <kbd>ALT + Π</kbd>
<kbd>Alt + O</kbd> results in <kbd>ALT + Ø</kbd>
<kbd>control + S</kbd> results in <kbd>meta + S</kbd>
<kbd>option + A</kbd> results in <kbd>Alt+Å</kbd>

Which is all unexpected behaviors. I tested on QT4/QT5 and the issue persists.
Tested versions: d55e44e c6aba5a

This is a new issue that has just started to occur and I'm not sure why. Due to it affecting older builds, I have a feeling it's something with OS X itself and not directly the client.

cc: @ctrlaltca @marcofernandezheras

**Comment by Daenyth** [comment]
Is this for shortcut configuration?

ctrl key is `meta` on osx, that's normal. Maybe we could display better. Option is alt so that's not surprising.

I think our issue is that we need to catch the key and osx is taking option+key to be the unicode instead of us catching the key.

Did it used to work at any point in time?

**Comment by ZeldaZach** [comment]
Yes it used to work a few weeks ago before we published expeditions. It worked fine on revision 2 of LA

**Comment by ZeldaZach** [comment]
This seems to be an issue on Linux as well now.

**Comment by Daenyth** [comment]
Probably dupe #1614
