### ISSUE TITLE
[Suggestion] Way to save enabled and disabled sets so that updating does not require users to go through the set list to disable them.

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1592]
I just installed the new version of Cockatrice and, since it was a new version, it enabled all of the sets, including onces I had specifically turned off. This is fine if you are just new to Cockatrice, but not for users who have used previous versions.

EDIT: I did not select the setting to uninstall settings, decks, cards, or pics. It kept all my other settings (such as chat mention color and special words to notify me) but it auto-enabled all the sets. There was a popup box that said something along the lines of "we noticed this is the first time using this version of Cockatrice, all sets have been enabled".

**Comment by Daenyth** [comment]
Does it really do this? That's a pain in the ass.

**Comment by Psithief** [comment]
In my experience, it only does this if Cockatrice can't find any existing settings. With all the installation changes this year, there's probably a new file or path that Cockatrice is checking.

**Comment by Daenyth** [comment]
I was talking in chat and we were thinking that the uninstaller is removing the settings for this.

**Comment by ctrlaltca** [comment]
The settings are saved in an ini file in the user profile.
Previously, before the "portable mode" patches, the settings were saved in the registry; the uninstaller has a (default off) option to wipe the settings, that now should be removed / fixed.

**Comment by tooomm** [comment]
I've never run into this problem the last few months while uninstalling/installing many many different clients.

Is this fixed? It most likely was an issue due to path changes and older clients?!
<br>


>The settings are saved in an ini file in the user profile.
Previously, before the "portable mode" patches, the settings were saved in the registry; the uninstaller has a (default off) option to wipe the settings, that now should be removed / fixed.

I don't quite get this. What is removed / fixed exactly?
We still have a (default off) option in the uninstaller to wipe settings - which is great actually!

**Comment by Daenyth** [comment]
I believe this is an issue with older versions, or if you check "remove settings" when uninstalling an older version.

**Comment by Daenyth** [comment]
Didn't realize this was an old issue, I believe this is now fixed.
