### ISSUE TITLE
Saving decks in text format puts tokens in main deck

### ISSUE THREAD

**Issue by MrAAA264** [Cockatrice/Cockatrice#1599]
So the last few times ive put tokens in the sideboard for a deck, when i load the deck in a game, for some reason the token keep appeaping in the main deck??

**Comment by Daenyth** [comment]
Can you provide screenshots of the step by step process?

Please also upload the .cod deck file to gist.github.com and link it here.

What version are you running? (`About Cockatrice` menu)

**Comment by MrAAA264** [comment]
i have the pictures, but how do i upload to gist.github?

**Comment by Daenyth** [comment]
You can drag the file from your file manager onto the gist screen.

**Comment by MrAAA264** [comment]
http://imgur.com/gallery/iTxWZ/new 
the tokens are currently in the sideboard, but move to the main?
https://gist.github.com/MrAAA264/5e99a18c00d3da11ea86

**Comment by Daenyth** [comment]
I see what the issue is.

Your deck is text format, not cod. The text export doesn't correctly handle tokens.

To fix this, make a brand new deck file and then use the "load from clipboard" action with the text you uploaded. When you save it, open it in notepad - it should have lots of things like `<card>` in it.

At that point it should work correctly.

**Comment by MrAAA264** [comment]
yep, it worked

**Comment by Daenyth** [comment]
Thanks. We'll get the core issue resolved.

**Comment by tooomm** [comment]
linking https://github.com/Cockatrice/Cockatrice/issues/472
