### ISSUE TITLE
Disallow single-key shortcuts

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1621]
Ref #1615; [(related comment)](https://github.com/Cockatrice/Cockatrice/pull/1615#issuecomment-144748472)

**Comment by Psithief** [comment]
That's too simplistic.

Keys that should still be allowed by themselves are ones that the chat does not print characters for.

* F1 through F12
* Tab (Game window only)
* Esc

- - -
Key combinations that should be disallowed because of conflicts:
**Windows** 
* Anything involving Printscreen
* Anything involving the windows key (Meta)
* (Chat text manipulation)
  * Ctrl+A (select all)
  * Ctrl+C, Ctrl+Ins (copy)
  * Ctrl+X, Shift+Delete (cut)
  * Ctrl+V, Shift+Ins (paste)
  * Ctrl+Z, Alt+Backspace (undo)
  * Ctrl+Y, Shift+Alt+Backspace (redo)
  * Del, Ctrl+Del, Ctrl+Shift+Del
  * Home, Shift+Home
  * End, Shift+End
  * Left arrow, Right arrow, Ctrl+Left arrow, Ctrl+Right arrow
  * Shift+F10 (context menu)
* Up, down, page up, page down (Scrolls chat window)
* Windows application manipulation
  * Alt+F4 (closes app)
  * Alt+Tab, Shift+Alt+Tab (Switches applications)
  * Alt+Esc (minimises application)
* Windows global shortcuts
  * Ctrl+Alt+Del
  * Ctrl+Shift+Esc (task manager)
* Alt+C, Alt+G, Alt+H, Alt+Space (Menu Accelerators)
* Ctrl+Tab, Ctrl+Shift+Tab (Switches windows)
* Ctrl+Alt+ [A-Z] types an uppercase character, shortcuts don't work.

**OSX**
Probably a lot from the same reference below.


Reference used: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by ebbit1q** [comment]
we can't keep track of which shortcuts are used by which desktop environment, since https://github.com/Cockatrice/Cockatrice/pull/3898 you're perfectly able to use single key shortcuts
