### ISSUE TITLE
Deck editor suggestions and other ideas

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1644]
- [x] 1. allow us to sort by rarity.
- [ ] 2. allow us to sort by Format.
- [x] 3. allow us to "flip" cards to read both sides.
- [ ] 4. allow the ability to save pms.
- [ ] 5. I have heard about people customizing themes to change the "hand icons" how is this done?
- [ ] 6. Is there any idea on allowing us to see all users in a room before joining said room?

**Comment by Psithief** [comment]
How can you sort by rarity when we only have one entry per card but they can have multiple rarities?

**Comment by radioactivehazards** [comment]
the card would show up as the newer rarity. some cards have been moved in rarites i agree. Serra angel used to be rare now its a uncommon

**Comment by Psithief** [comment]
Newer rarity ordered by standard-legal sets only? I would expect supplemental set reprints would need to be excluded, e.g. From the Vault is all mythic rarity.

**Comment by Psithief** [comment]
As for the other suggestions:

1. --
2. Can't sort by format either, for similar reasons. *Filtering* by format should be possible.
3. There's only a marker that one card is related to another at the moment, we're not yet tracking enough data for the editor to know that a related card has a second side.
4. You already opened an issue on this in #1644.
5. If it's just a discussion about technical questions, it's probably easier for you to ask in the gitter chatroom: https://gitter.im/Cockatrice/Cockatrice
6. Did you mean game, instead of room?

**Comment by radioactivehazards** [comment]
yes i meant game. and the pm thing is still an issue so i refreshed it.

**Comment by Daenyth** [comment]
Related #215

**Comment by Daenyth** [comment]
Also #492

**Comment by ZeldaZach** [comment]
This ticket is too busy. If things are still relevant, separate tickets can be opened.
