### ISSUE TITLE
Morph Cards Issue and an inapropriate Moderator move

### ISSUE THREAD

**Issue by PrimeSpeaker** [Cockatrice/Cockatrice#1651]
Helios just banned me from the server after I wanted to tell him a game-breaking issue. After he was ignorant about it and I told him that he's no use if he doesn't help, he banned me from the server.

Absolutely inappropriate, screw you, helios.

The bugs I want to report are as follows (and were disregarded by helios AND jinete, who both showed absolutely no interest in fixing those bugs and showed that they don't want to be involved in anything and just want to be left alone).

(1) Your ban was inappropriate, helios, definetly just want to show your power of banning people.

(2) When you have a morph creature in play and you double-click a creature card from your hand that is the same as the face-down creature, it enters the battlefield on top of the morph, telling your opponent, that the morph is the same creature as the one you played from your hand. Fix that.

(3) The two new manlands of BFZ enter the battlefield untapped when double-clicked from hand, while all other manlands enter tapped. Fix for consistency. Fix that.

You mods, especially Jinete and now being banned by that slacker helios show me that you are not even interested in improving cockatrice and are rather offended when being called out on your non-activity to imrpove the software. 
Thanks for the ban, you are not part of the solution, you are part of the problem.

**Comment by PrimeSpeaker** [comment]
Ban reason was "Flaming, Trolling".

Screw you, helios, I was trying to improve your software. What are you doing.

**Comment by ctrlaltca** [comment]
I just stopped reading after ```Helios just banned me from the server```.
We are not related to any server, this is not the place to whine about moderators.
Typically each server has a forum/web form/email address where you can send your complaints.

**Comment by Nightfirecat** [comment]
Hi @PrimeSpeaker,

I'm glad you were able to address the software bug here &mdash; I'm able to reproduce it, so I see what you're saying. @woogerboy21 this appears to be a server-side issue, if I'm understanding this correctly.

I'm not able to reproduce the issue with the BFZ manlands entering the battlefield untapped. Can you please ensure you're using the most up-to-date card database by running Oracle? That may be the cause of the issue.

Regarding your issue with the moderators &mdash; the moderators for the server are exactly that: moderators for *the server*. They do not hold any special obligation to the software by being a server moderator. Software issues should be reported here, rather than brought up to the moderators. To dispute moderator behavior, you should contact a server operator. (in this case, likely @woogerboy21)

**Comment by Daenyth** [comment]
#2 I think might be already reported.

#3 is fairly minor but we can look at it.

Please don't bring issues with individual server's moderators here, this page is for the software - bring up issues directly with the server owner
