### ISSUE TITLE
On first launch, show "Register to server" dialog

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1672]
Have a dropdown of the default servers to register to.

Have a button to specify that you already have an account.

First launch only

**Comment by tooomm** [comment]
There are maybe many servers that work without registration. Do we really want to show the dialog just because the biggest server we know of requires a registration?
Many just play private servers or community servers etc.pp.

But some kind of guidance at first start besides the "Hello & Welcome" that we have right now might be cool to tell them where to find help or get started and how to connect/register if needed. There could be an additional button that opens the register/connect dialog for them.

Conclusion: I would rather expand the dialog we have now (with button and more information), instead of using a second one that many people might not need/want. There could also be a link in the menu to reopen the "Welcome to Cockatrice / Get started" dialog if people end up just closing it at first start.

**Comment by Daenyth** [comment]
Yes, good point. The first run intro should be more general

**Comment by ebbit1q** [comment]
I think instead what'd actually be most useful is to put this message on the cockatrice.us webpage: "to register use the option 'register to server' in the top left menu" considering registration differs per server and the webpage is linked in the connect dialog. @ZeldaZach

**Comment by tooomm** [comment]
I doubt that any user checks or even knows about the server webpage before running the app for the first time.

**Comment by ebbit1q** [comment]
before running the app they can't connect or register to this server anyway

**Comment by tooomm** [comment]
Well, I guess with https://github.com/Cockatrice/Cockatrice/issues/742, this problem is gone as it gets more intuitive how to register.

**Comment by ebbit1q** [comment]
I'd close this in favor of #742
