### ISSUE TITLE
"Create related card" tokens can't be duplicated with "Create another token".

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1726]
A workaround is to select the token just created and duplicate it with the "Clone" command.

In later turns, however, a player won't remember the difference between creating a token using the "Create Related" feature versus the "Create Token" feature, leading to confusion over what "Create Another Token" will do.

**Comment by ZeldaZach** [comment]
I don't fully understand. Can you include pics?

**Comment by Psithief** [comment]
Sure. Notice how the "Create Another Token" command is greyed out because it has nothing to reference.

![1726-1](https://cloud.githubusercontent.com/assets/1124846/12014905/5a5c0f68-ad6f-11e5-84e5-833e3929bf9f.png)
![1726-2](https://cloud.githubusercontent.com/assets/1124846/12014906/5a5d53be-ad6f-11e5-9f73-5b8c17e6dc10.png)

**Comment by ZeldaZach** [comment]
I see, that's an issue. So when i hit create related card and a token pops, I should be able to create another token that's the same by hitting Ctrl+G (the default). Makes sense

**Comment by ZeldaZach** [comment]
cc: @ctrlaltca

**Comment by Daenyth** [comment]
I'm actually not sure of that. ^g is a shortcut for manual tokens. Can we
set up a straw poll to see which behavior people prefer?

**Comment by ctrlaltca** [comment]
The "create another token" functionality is currently tied to the value of the fields coming from the "create token" dialog: it just creates a token reusing the last values from the dialog.
Anyway, this request can be implemented if necessary.

**Comment by Daenyth** [comment]
http://strawpoll.me/6383660

**Comment by tooomm** [comment]
The strawpoll results shouldn't be valued too much because people mostly don't know about the new extended "Create related card" feature and don't use it at the moment mostly.

**Comment by Psithief** [comment]
@Daenyth Setting up a straw poll is the worst idea I've ever seen in open source development. It makes absolutely no sense to ask *any* development question in a anonymous, unsecured, repeatable poll.

**Comment by Daenyth** [comment]
@Psithief It's by no means scientific. It's not going to be the deciding factor in which way we go. I'm just using it as a quick and dirty opinion poll.

I'm open to other suggestions. What would be a better way for us to gather community feedback? I'd estimate that under 1% of active users will actually get on github and participate in this conversation even if we ask them to (and I have, many many times).

For the moment I'd like to not change this behavior. It's easy to just select the token on the board and "clone" it, or to right-click the source and do another "Create related". The "create another token" feature exists because the "create token" dialog is annoying, so expanding the scope of its behavior will reduce it's intended effect, in my opinion.

**Comment by Psithief** [comment]
Yet, the fact that the create token dialog is annoying is why we've gone to all this effort in the first place, it alleviates the vast majority of the reasons to use it. 

Why should anonymous community feedback matter at all? If someone wants to make their thoughts known that person should write a few words, just to prove understanding of the issue.

**Comment by Nightfirecat** [comment]
Whoops, missed this ticket when I created mine. 😁
