### ISSUE TITLE
tab_userlists --> tab_account (code file rename required)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1737]
In #906 we changed the former `User lists` tab to `Account`.

However the code files didn't receive a renaming and are still named `tab_userlists.h` & `tab_userlists.cpp`. They need to get renamed as well I think. :)

The code may include many more old references related to that change that confuse new developers which want to work with the code!

---

other example:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/sequenceEdit/ui_shortcutstab.h#L1478
It should be "ClearFilterSelected" or sth., not "ClearFilterOne"
You are going to clear filter one? It's not precise...

**Comment by Daenyth** [comment]
This is good clean up. :+1:

**Comment by ctrlaltca** [comment]
The class is still named TabUsername, so we should rename it aswell and fix the code calling it.

I'd also go for a "one class per file, file name=class name" rule; i found it to help for newbies approaching your project, because at least they don't have to mess around to find where that symbol is defined.
The bad part is that, the last time i did it on a project, it totally destroyed the ability to backlog commits on the cvs (svn), but git should handle this better, afaik it understands when a file gets renamed.

**Comment by Daenyth** [comment]
I'd support "one major class per file" but if it has supporting data I wouldn't split it. For example, if a class uses an enum, I think it's reasonable to put the enum definition in that file. All platforms have IDE options, and even for the vim/emacs crowd there's ctags.
