### ISSUE TITLE
Ignoring users can still be messaged

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1757]
If I ignore a user, I can send them a message but they can't respond. 
Correct way should be if I ignore a user, I can't message them and they can't message me.

Thoughts on this change?

**Comment by Fizztastic** [comment]
Does this only apply to private messaged or to in-game/chat rooms as well?

**Comment by Daenyth** [comment]
We should probably get around to changing this but I don't think it's actively hurting anything.

**Comment by LethalPigeon7** [comment]
Currently applies to chat rooms and private messages, ignore lists do not function in games iirc. This seems like a perfectly well working setup.

**Comment by Daenyth** [comment]
Given that users you ignore can't join games you create, and if you didn't
create a room, you can't control who joins it, it seems easiest that you
see the chat of people you ignore in game. It would lead to some amount of
confusion otherwise if you tried to play a MP game where one person's chat
couldn't be seen.

**Comment by LethalPigeon7** [comment]
I mean everything you just said is what I had in mind when I said the current setup is as good as it gets as far as I know.
