### ISSUE TITLE
UTF-8 Not used everywhere

### ISSUE THREAD

**Issue by imaspen** [Cockatrice/Cockatrice#1786]
Chat in Cockatrice is using latin1 instead of UTF-8.

**Comment by ZeldaZach** [comment]
The codebase seems to have latin1 used in a few places, that should be changed over.

**Comment by ctrlaltca** [comment]
The deck editor handles UTF8 just fine:
![schermata 2016-02-02 alle 21 46 34](https://cloud.githubusercontent.com/assets/1631111/12764091/1c56067e-c9f8-11e5-90a1-b58a521ed514.png)

Games are broken due to qstring 2 stdtstring conversion: cards named with kanji chars just disappears from the deck as if the server is silently discarding them.

**Comment by Daenyth** [comment]
I wonder if discarding kanji cards could be used to generate arbitrary deck
hashes

**Comment by Fizztastic** [comment]
@Daenyth I just tested it and they affect the hash the same way regular characters would. Also, when I loaded a deck that had kanji card names in it they weren't discarded from the deck in-game.

**Comment by zebington** [comment]
Struggling to recreate this.
![test](https://cloud.githubusercontent.com/assets/4019381/12793724/bd71f3e0-caa9-11e5-869e-9bc3dfb1a07d.png)

**Comment by ZeldaZach** [comment]
Dupe #2545

**Comment by tooomm** [comment]
>Dupe #2545 

This issue is about chat, not the card database?

**Comment by ebbit1q** [comment]
the problem is the card database
