### ISSUE TITLE
Use roaming appdata for windows user settings.

### ISSUE THREAD

**Issue by pfirsich** [Cockatrice/Cockatrice#1814]
It seems that decks and user settings are stored in AppData\Local. I could explain or just post this link, which points a little to how this should be dealt with: 
https://msdn.microsoft.com/en-us/library/windows/apps/hh465094.aspx
Most of the content should probably be moved somewhere to AppData\Roaming.

**Comment by ctrlaltca** [comment]
I noticed this same problem when working on the windows packages.
The user profile used to live in the "cockatrice" folder in %PROGRAMFILES%, then it got moved to %LOCALAPPDATA%. I suppose it got moved there because the card images folder can grow up to a few gigs, and we don't probably want it to roam between the user's devices or in the domain.

I thought on splitting user settings in %APPDATA% and cached data (like card images) in %LOCALAPPDATA%, but i found some possible problems in doing that:
 * il will make it confusing for users trying to migrate / move the profile from another installation or os;
 * we should handle the migration of old profiles to the new split layout;

Instead, i did not really found a good reason on doing this change, so i thought it was not worth the required effort. Do you know of any real-world case where this change is needed?

**Comment by Daenyth** [comment]
>  I suppose it got moved there because the card images folder can grow up to a few gigs

It also was moved so that
- Users don't need write permission to program files
- Deleting the app wouldn't delete user decks.

**Comment by Daenyth** [comment]
So, we should probably use this for user settings and decks and put pictures in appdata.

I don't think this is high priority but we can do it eventually. We will need to make sure we have a good transition option for users with existing installations.

The big blocker to this is that user settings are mostly in the registry, not on a file we can sync.

**Comment by ctrlaltca** [comment]
> The big blocker to this is that user settings are mostly in the registry, not on a file we can sync.

IIRC most of the settings have been moved to INI files to support portable builds.

**Comment by ZeldaZach** [comment]
This isn't really worth it
