### ISSUE TITLE
Cockatrice doesn't load actions on client but they register on server

### ISSUE THREAD

**Issue by YellowAssassin** [Cockatrice/Cockatrice#1815]
I've just gotten cockatrice on my new computer, but it has this really weird kind of lag where cards, after I've dragged them to a different zone, don't move for a couple of minutes on my client. However, whilst skyping my friend, he says that the cards have moved on his side and they've moved almost instantaneously. Can anyone help me with this? 

Thanks

**Comment by ZeldaZach** [comment]
It's possible you're on a weak connection to the internet and/or you're very far from our server location (which I believe is in California, but @woogerboy21 can correct me).

**Comment by YellowAssassin** [comment]
One of the issues is that it runs fine on my old laptop but it just doesnt on my pc

**Comment by Daenyth** [comment]
Very strange. So it works like:

- User does action locally
- Cockatrice tells the server
- Server replies
- Cockatrice uses the reply to update the visuals.

It sounds like there's a lot of latency in your connection since that last step is very delayed. Minutes however is incredibly extreme.

What OS are you on?

You say it doesn't run on your PC, can you elaborate? Maybe we can fix that.

**Comment by Daenyth** [comment]
If this is still an issue for you please re-open the ticket.
