### ISSUE TITLE
Set column empty for non-tokens

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1839]
<b>OS:</b>
Sabayon Linux

<b>Cockatrice version:</b>
0b8f52e

---

<br>

On a new install of Cockatrice, the set column is empty for cards added from mtgjson, while it has values for tokens, which are from another source.
![2016-02-28-231123_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6954107/13385586/a10132b8-de70-11e5-805b-cd69372be702.png)
This appears to be because the "printings" field is only available in `AllSets-x.json`. I'm unsure if this is the intended behavior or not, but if it is, there should probably be a note about it in Oracle.

**Comment by ctrlaltca** [comment]
> This appears to be because the "printings" field is only available in AllSets-x.json.

Oracle is parsing the set names from AllSets.json, as documented in [mtgjson's documentation](http://mtgjson.com/documentation.html) and implemented in the [oracle importer class](https://github.com/Cockatrice/Cockatrice/blob/master/oracle/src/oracleimporter.cpp#L16), so your assumption is wrong.

Now, trying to troubleshoot your problem, it seems that your cards.xml is missing a lot of cards (the first one starts with "An") and also the sets information.
Can you attach your cards.xml so that we can see if it's formatted correctly?
Do you see the full sets list when oracle is run?
![schermata 2016-02-29 alle 12 45 58](https://cloud.githubusercontent.com/assets/1631111/13393551/6a172506-dee2-11e5-95c7-758e2824919b.png)

**Comment by skwerlman** [comment]
Regarding missing cards, the first one starts with 'an' because i have scrolled down a bit (it's a little hard to see because of qt's awful default theme)

As for `printings`, it is listed as "Extras Only" in the documentation: http://mtgjson.com/documentation.html

I am not currently using my Linux box, but when I am, I will upload cards.xml

**Comment by tooomm** [comment]
Taken from your link, right at the top...
```
Sets

The AllSets.json file is an object that looks like this:

{
	"LEA" : { /* set data */ },
	"LEB" : { /* set data */ },
	"2ED" : { /* set data */ },
	...
}

(...)
Each individual set is a JSON object like this:
              "name" : "Nemesis",            // The name of the set
              "code" : "NMS",                // The set's abbreviated code
(...)
             "cards" : [ {}, {}, {}, ... ]   // The cards in the set
```

So you see that all the set names are in the **AllSets.json** we use.
Each set is a object of it's own containing informations about that set and it's cards.
No need to use `printings` field.

**Comment by skwerlman** [comment]
I can not reproduce this.
