### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by FoxTrot199** [Cockatrice/Cockatrice#1840]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 0b8f52e 2016-02-08

___
<br>

I have been issues with the severs and oracle.
When I tried connecting it would start to conect and a message would pop up saying "Socket Error connection timed out" I've only had gotten cockatrice 2-3 days ago and today it has had this problem. For Oracle if been getting the same error where the mbs stays at 0 and the socket error has come up. I have downloaded to json file and fixed that but I can't download the tokens.
I have looked up how to fix this problem but i have come to conclusion that i couldn't fix it so I can to you as my final attempt.
P.S. sorry if i didnt put enough info this is my first time with Github

**Comment by Daenyth** [comment]
Connection time out means that your computer sent information to the server (and the mtgjson site) but spent too much time waiting with no reply.

Typically this means it's a problem on your network.

What kind of network are you on? Are you on a managed network like a university or work? They might have software intercepting the requests and making them fail.

With oracle, try visiting the url from the app in your web browser - if you can download the file like that, you can run the import for it from the file instead of having oracle download it.

**Comment by FoxTrot199** [comment]
I'm on a WiFi extender because i have a dead zone in my house and I'm going to presume that might be the issue?

**Comment by woogerboy21** [comment]
One way to find out is to actually move to a segment of the network that is not on the extender

**Comment by ZeldaZach** [comment]
If this is still an issue for you, please feel free to reopen!
