### ISSUE TITLE
64bit windows installer should prevent 32bit users from installing.

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1854]
This leads to the 0xc000007b error.

**Comment by Daenyth** [comment]
http://stackoverflow.com/questions/13229212/how-to-detect-windows-32bit-or-64-bit-using-nsis-script

**Comment by radioactivehazards** [comment]
Yeah Hi. :+1:    This is MY house. I just found the page to check my machine specs via control panel and i know this has got to make sound  VERY smart here. but yes i am copying this straight from that.

System type: 64bit operating system, 64x based processor

**Comment by Daenyth** [comment]
OK, then I suspect the 7b error is needing 64bit redist files then... I'll look into how we can help people get those

**Comment by Daenyth** [comment]
@radioactivehazards If you follow the download instructions [here](https://www.microsoft.com/en-us/download/details.aspx?id=40784) does it work for you with the 64bit version?

**Comment by radioactivehazards** [comment]
sry my machine decided that now was a great time to have a Seizure.. sound issue not related to cockatrice at all happened and then I got booted off the server for "other" reasons. I am checking this now. downloading the vcredist_x64.exe

**Comment by radioactivehazards** [comment]
Sometimes I swear technology hates me...the feling is mutual.  The sound issue was my left ear dying for the millionith time in a pair of headphones..... :< :8ball:

**Comment by radioactivehazards** [comment]
ok after that installs you want me to do what?

**Comment by Daenyth** [comment]
Retry installing the 64bit weekly build

**Comment by radioactivehazards** [comment]
I assume you mean a QT5 build,

**Comment by tooomm** [comment]
>System type: 64bit operating system, 64x based processor

You are obviously running a 64bit system...
(and I know by reading your other postings that it's Windows - always make sure to provide this information when you open new issues!)


Just grab your 64bit version from our **Official Cockatrice website** at https://cockatrice.github.io/
![untitled](https://cloud.githubusercontent.com/assets/9874850/13731382/59cc04a2-e967-11e5-8ac4-869ac72d9b15.png)



We don't provide Qt4 builds anymore... and you definitely don't need one unless your hardware is from the stone age. ;)
(your cpu needs to support SSE2 to use Qt5 --> mostly all hardware from 2002 onwards)

**Comment by radioactivehazards** [comment]
Same error happened with the qt5.

**Comment by radioactivehazards** [comment]
Like I said technology sucks. I know my machine is current. It can probably
Run windows 10.. but i have 8 installed.

**Comment by tooomm** [comment]
Reading your other issue posting you wrote that the Qt4 version worked for you last month...
But since the download links were labeled wrongly at that time and the so called Qt4 version just happened to actually be a Qt5 32bit version you might want to try that one instead.

You'll find it below the other download buttons on our website!

Hope that gets it working for you again.

**Comment by radioactivehazards** [comment]
huh? i am on that one still. because any other updates do not work.

**Comment by Daenyth** [comment]
@tooomm the 32bit version is working for him, I was thinking it might be a redist thing preventing the 64bit one from working, but it looks like it does work, so I'm not sure.

**Comment by tooomm** [comment]
Ok, I'm back on track now... it seems mostly that it's related to the vcredist then.

@Daenyth linked you to the "Failed start because MSVCP120.dll was not found" page with the corresponding Visual C++ Redistributable file.

Are you up to try the last one as well on our troubleshooting page?
(aka "...MSVCP**140**.dll was not found"):
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

**Comment by radioactivehazards** [comment]
I am lost. too much techno lingo here. I got a working cockatrice. I am happy to leave it at that.
