### ISSUE TITLE
Downloading Error

### ISSUE THREAD

**Issue by Ledge-And-Dairy** [Cockatrice/Cockatrice#1870]
<b>OS:</b>
Windows 8.1

<b>Cockatrice version:</b>
Currently none. 

___
<br>

 I was getting an issue where none of the tokens were loading for me in game or deck builder so i decided to reinstall. I attepted to delete every previous file/app i had downloaded including Oracle. When I redownload I rn into this issue where its telling me I am missing MSVCP120.dll:

https://gyazo.com/09644f6c9e5373c06d67588da407fbbf

Even though i do have it downloaded:

https://gyazo.com/d1b746736fb34bbffb3b5b7465d8b555

Any help or suggestions would be awesome

**Comment by ctrlaltca** [comment]
Try following https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

When you'll be about to download the vcredist_xxx.exe file from the microsoft's website, ensure you are downloading the version that matches the cockatrice version you want to use:
* vcredist_x86.exe for 32bit cockatrice
* vcredist_x64.exe for 64bit cockatrice

**Comment by Ledge-And-Dairy** [comment]
thank you got it working :)

**Comment by ctrlaltca** [comment]
You are welcome.
