### ISSUE TITLE
Permission error loading decks

### ISSUE THREAD

**Issue by Ledge-And-Dairy** [Cockatrice/Cockatrice#1872]
<b>OS:</b>
Windows 8.1

<b>Cockatrice version:</b>
cbea432 (2016-03-08)

___
<br>

https://gyazo.com/b3d318ccdf804cdb305d0fff462f4ec9

Not quite sure how to fix this but I get an error everytime I try to go to ldeck loader. I am Administrator on this PC by the way

**Comment by ctrlaltca** [comment]
That sounds like a messy permissions problem.
I'd start ensuring the disk is ok, running [scandisk](https://support.microsoft.com/kb/2641432); this will requite about 10 minutes and a reboot.

Then, you can try to become the owner of the folder following [this procedure](https://technet.microsoft.com/en-us/library/cc753659.aspx)
Please note that this is something that should not be usually needed, since when you run Cockatrice it should create folders that are accessible by your user.

**Comment by Daenyth** [comment]
It this still a problem for you?
