### ISSUE TITLE
Card lookup is case-sensitive in chat - displays blank for incorrect case

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#1915]
<b>OS:</b>
Win7

<b>Cockatrice version:</b>
948a5c6

___
<br>

Cards not propagating the chat link box.  Cards exist in card database.  Tried various cards, did not find any that worked.

![image](http://i.imgur.com/0BCCypU.png)

**Comment by tritoch** [comment]
Only in main chat / PM.  Works in-game.  Box displays oversized as in screenshot in game.

**Comment by tritoch** [comment]
It's case-sensitive now.  Using proper case brings up the box as 'normal' (box still looks larger frame-wise than previous versions).

**Comment by Daenyth** [comment]
That should be easy enough to fix

**Comment by tooomm** [comment]
Totally agree! :+1: 
So many cards are linked in the chat... but many people just write them in all lower case letters and the card linking remains useless.

Instead of just ignoring the case for the database lookup, Cockatrice should also correct and print the correct name of the card in the chat if you use [[cardname]].
`[[bearer of overwhelming truths]]` --> `Bearer of Overwhelming Truths`
