### ISSUE TITLE
Not working on windows xp!

### ISSUE THREAD

**Issue by LordJohn985** [Cockatrice/Cockatrice#1951]
I'm trying to install the new version into a windows xp computer, but after installing it, it tells "Not a valid win32 application". Before trying to install the new version, it ran without aby issue (except for the token library). I've read the troubleshooting about that, but after trying to install the 32-bit cockatrice many times it doesn't run, although it's installed.

Any ideas why this happens?

**Comment by Nightfirecat** [comment]
Probably the same problem here: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application

**Comment by ctrlaltca** [comment]
> I'm trying to install the new version

I suppose you mean Cockatrice: "Gatewatchers", aka 323fc06. This version has a problem that makes it incompatible with PCs running windows Xp. Since then we fixed the problem (in 195ab9a150b09b65658dec922ee3f86e2f47eb0d), so you may want to run a fixed version like this one: https://bintray.com/artifact/download/cockatrice/Cockatrice/Win32/Cockatrice-0.0.1~git20160416.2e3966a-x86_qt5.exe

**Comment by tooomm** [comment]
[New official Cockatrice version out!](https://github.com/Cockatrice/Cockatrice/releases/tag/2016-05-06-Release)
XP is working again... but I consider this fixed anyway. After 3 weeks no reply and ctrlaltca already linked to a working xp version.
