### ISSUE TITLE
Msvcr120.dll missing

### ISSUE THREAD

**Issue by TheLemmyW** [Cockatrice/Cockatrice#1968]
I'm with Win10 64 bit

Cockatrice-0.0.1~git20160427.ff1091a-x86_64_qt5 This is the name of the build i downloaded.
___
<br>

I tried to update my version to the latest, and now it keeps telling me that msvcr120.dll is missing, i downloaded it, installed in the cockatrice folder and then, after it was useless, i put that in /syswow64, restarted the computer, but still the error occurs. What can i do?

**Comment by ZeldaZach** [comment]
You read the wiki on how to fix this issue already, correct?

**Comment by ctrlaltca** [comment]
Better link it: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

Advice: you shouldn't download random dlls from the web and put them into your pc's folders, it could cause misc problems with other software using the same dll or even get your computer infected by any sort of malware.

**Comment by TheLemmyW** [comment]
I downloaded the dll from microsoft itself, but still i'm not able to make
it work. Do i have to try again and so on until i manage to fix it?

2016-05-02 18:16 GMT+02:00 ctrlaltca <notifications@github.com>:

**Comment by Daenyth** [comment]
Did you get it from the specific link in the troubleshooting page? There's several similar dlls and only the exact one will fix it. If it stills says it's missing you might not have installed the right one.

**Comment by TheLemmyW** [comment]
After some more tries, i managed to fix the problem. Thanks for the support.

2016-05-02 21:30 GMT+02:00 Gavin Bisesi <notifications@github.com>:

**Comment by Daenyth** [comment]
Glad you got it working!
