### ISSUE TITLE
BinTray Auto Updating Issues

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1972]
Seems like BinTray's API may have changed as it no longer includes a "date" field (as seen [here]( https://github.com/Cockatrice/Cockatrice/blob/cbea43267ef32135d34099efbdf699703228547a/cockatrice/src/update_checker.cpp#L76))

I was successfully able to get it to work by changing "date" => "created" as they're very similar and contain the same type of dataset.

Once doing this, the program seems to work (on OSX) correctly. An issue I came across, however, is that [this](https://github.com/Cockatrice/Cockatrice/blob/cbea43267ef32135d34099efbdf699703228547a/cockatrice/src/dlg_update.cpp#L167) line on a mac doesn't open up the installer. I couldn't figure out how to do that, so I'm not opening a PR in favor of someone else looking into this.

This is a critical bug that needs to be addressed.

cc: @ctrlaltca

**Comment by tooomm** [comment]
Also the updater somehow checks for special strings in the file name to determinate if there is a proper version for your os available. At least I think so. :)

Since we're about to drop Qt4 soon and we might want to check for 32 or 64bit instead this could see a change too:
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/update_checker.cpp#L60

https://github.com/Cockatrice/Cockatrice/pull/1727 isn't giving too much details about the actual step by step behavior and requirements of the updater without looking at (and understanding) the code...

**Comment by Daenyth** [comment]
I agree, try to summarize issues more clearly so others have context.
