### ISSUE TITLE
Change "Quit" to "Conceed" when in-game

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1988]
Currently if you want to quit a game in play, you are asked if you want to `Quit`/`Leave the game`.
I think that changing this to `Are you sure you want to concede` would be better. If a player quits a game in progress, then they have conceded.

This change should show in the quitting players popup, and also to the other player: `playername has conceded`

I think this may also help with people dropping, as the MTG community can be fickle and not want to concede.

**Comment by Daenyth** [comment]
Reasonable enough. 👍

**Comment by Jinxstands4Jinx** [comment]
I do not get this. I would rather quit than concede as conceding justifies a loss, sometimes you just quit due to irritating opponent or simple fact that life happens, or that you feel the game is unwinnable for both parties and would rather move on to something else.

**Comment by poixen** [comment]
This is how MTGO handles it.

If the other player is annoying for any reason and you leave because of that, then you have left the game.
It doesn’t matter the reason. You have left and thus conceded.

If life happens and you need to leave the game? Same thing, you should concede to the opponent.
Right now this IS what happens anyway, its just our game text does not reflect this.

**Comment by Jinxstands4Jinx** [comment]
I do no think this should be changed. Leaving a game is fine, but conceding a game that you did not lose by your own choice is not fine.

**Comment by poixen** [comment]
Leaving IS conceding.

**Comment by Jinxstands4Jinx** [comment]
So should we change kick to "Force concession"?  because that is the reason why i leave most games, because no one can win. I feel having it be concede may provoke people to be even more annoying and trollish because no one wants to concede against their will. People will quit no problem

**Comment by Daenyth** [comment]
> This is how MTGO handles it.

MTGO has a concept of winning the game and losing the game, we don't.

**Comment by Jinxstands4Jinx** [comment]
cockatrice is superior to MTgo. so why would we follow them.

**Comment by Daenyth** [comment]
> cockatrice is superior to MTgo.

It's just different. The projects have very different goals. And even so, we should evaluate the idea on its own merits for our use case rather than based on who else does what.

Given that trice doesn't have a win/loss concept, I think changing the wording would be misleading for users. Since the server has no idea what winning is, mentioning it doesn't provide useful information. You're either in a game or not. If you go from being in a game to not in, that's leaving.

I'm open to being convinced on this, but I think the benefit to changing would be marginal, and I'd like to stick to that consistent wording to express the app's concepts.
