### ISSUE TITLE
All matches appear to have +hours

### ISSUE THREAD

**Issue by pviollier** [Cockatrice/Cockatrice#1994]
<b>OS:</b>
Win 7

<b>Cockatrice version:</b> Version d55e44d (2015-09-23)

___
<br>

When I enter the match area, all matches appear to have +5hours. That doesn't let identify which are starting, etc

Here is a link to the screenshot: ![pic](http://i.imgur.com/jVemQa9.png)

**Comment by Daenyth** [comment]
Can you include a screenshot of your game filter settings?

**Comment by ctrlaltca** [comment]
Also, can you check if your pc has the correct date and time set?

**Comment by Daenyth** [comment]
Good call, that could definitely do it.

**Comment by pviollier** [comment]
Changed the time and that fixed it :) thanks!

**Comment by Nightfirecat** [comment]
So the game creation time is checked against the user's date/time? It seems to me like they should be updated with the user's time, but should have a static age when initialized. (if the user's clock is minutes or hours off, the room ages shouldn't also be minutes or hours off)
Another point to consider: what happens if the user's clock is *ahead* rather than behind? Would all rooms display as being <1m old?

**Comment by ctrlaltca** [comment]
The server stores the game start time when the game gets created, and then sends it to the clients as a time_t datatype (also known as https://en.wikipedia.org/wiki/Unix_time). This is a design choice to go low on the calculations needed on the server, to avoid having the server re-calculate every single game's age every second and sending the updated value to each client.

Your idea is a bit more performant, but still would force the server to recalculate each game's age when sending the games list to a just-joined-in user. Also the client calculation is a bit more complex, since it would have to keep for each game both the exact time when it received the game properties and the server-supplied age of the game at that time and sum them  before subtracting from the current time. 

> Another point to consider: what happens if the user's clock is ahead rather than behind? Would all rooms display as being <1m old?

You are right, and it takes like 10 secs to test it, just adjust your pc's time and hop the room.

I would say that if my clock is skewed, i expect to see the wrong time :)

**Comment by Daenyth** [comment]
> I would say that if my clock is skewed, i expect to see the wrong time :)

Yep. I don't see any gain for the app in accommodating people who have their clocks set wrong at the cost of the server doing more work.
