### ISSUE TITLE
Pictures not working properly

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2024]
<b>OS:</b>
*Win 7*

<b>Cockatrice version:</b>
3c58003
___
<br>

When downloading pictures it always downloads the newest even though I have sets ordered oldest to newest in the client UI. Hideous, eyes burning, not worth it. Tried rerunning oracle, clearing already downloaded pictures, downloading from default and gatherer, doesn't help. It happily downloads pictures from sets I even have disabled. Oh and also some pictures are just blank. Instead of the card I see the card backside forever.

**Comment by Daenyth** [comment]
Sounds like a regression. We should be able to fix that for the next release

**Comment by LethalPigeon7** [comment]
Sorry for the question, but when is that? I mean is it a matter of days, weeks, months... I never really took much interest in this.

**Comment by ctrlaltca** [comment]
> When downloading pictures it always downloads the newest even though I have sets ordered oldest to newest in the client UI.

This sounds like a bug. Does it happens with every card, only with some cards, can you name one?
I suppose trice somehow is not able to download the card from your preferred (topmost) set and resorts to the first set with a working image.

> It happily downloads pictures from sets I even have disabled.

That's by design, or you won't be able to see images for cards coming from sets you disabled. Eg. a lot of people only play standard and disable every set but the ones currently legal in that format. Still, if they join a modern game as spectator, they're supposed to be able to see card pictures.

> Oh and also some pictures are just blank. Instead of the card I see the card backside forever.

Can you please name one?

**Comment by ctrlaltca** [comment]
Assuming you're running windows, can you try to update cockatrice to this experimental version: https://ci.appveyor.com/api/buildjobs/ykxd62t769j87bmv/artifacts/Cockatrice-0.0.1~git20160624.66942cf-x86_qt5.exe 
It adds a new menu entry `Help -> View log` that brings up a dialog with some informations about what's going on about image loading.
It should be really helpful in understanding why cockatrice is showing the wrong image for you.

**Comment by LethalPigeon7** [comment]
I would, but updating alone somehow fixed the problem ^^

**Comment by ctrlaltca** [comment]
Well then, if you happen to reproduce the problem again, feel free to reopen this ticket.
