### ISSUE TITLE
Can't update card database over SSL

### ISSUE THREAD

**Issue by thekingkazma** [Cockatrice/Cockatrice#2031]
<b>OS:</b>
Windows 7

<b>Cockatrice version:</b>
c19f225 (2016-06-26)

-___
<br>

When I open cockatrice, a window says, "Cockatrice is unable to load the card database. Do you want to update your card database now? If unsure or first time user, choose "Yes"

I press "Yes". It brings me to language choice screen, I select english and press "next". Now is the source selection screen. The "Download URL:" option has "https://mtgjson/json/AllSets.json.zip" as the source. I click next. Then a new window immediately pops up saying, "Network error: Error creating SSL context ()."

How do I move past this?

**Comment by ctrlaltca** [comment]
Somehow oracle (the card downloader) is not able to download a file from the internet.
try to:
 1. download http://mtgjson.com/json/AllSets.json.zip using a browser
 2. on the "Download URL" window, choose "local file" instead and load the AllSets.json.zip file you just downloaded

**Comment by Daenyth** [comment]
Maybe this? http://stackoverflow.com/questions/18894056/error-creating-ssl-context-qt

**Comment by ctrlaltca** [comment]
Yes, the problem is typically due to other software  installing a previous, ABI-incompatible version of the  openssl libraries in c:\windows\system32.
I already experienced this problem on pcs with some old crystal reports versions (11, iirc).

**Comment by tooomm** [comment]
Same error for me after updating to https://ci.appveyor.com/project/Daenyth/cockatrice-8k7y5/build/0.0.1-branch-master-build-223

**Comment by ctrlaltca** [comment]
> Same error for me after updating to https://ci.appveyor.com/project/Daenyth/cockatrice-8k7y5/build/0.0.1-branch-master-build-223

This is strange, i've just tested that exact version and i can tell i'm sure it's able to load the correct libraries:

![procexp-ssl](https://cloud.githubusercontent.com/assets/1631111/16443516/96e6aba0-3dd9-11e6-9770-aebe339d471e.png)

By the way did you test the 32 o the 64bit version?

**Comment by ZeldaZach** [comment]
I've had this reported by users on windows 7 and 8, but 10 worked fine

**Comment by ctrlaltca** [comment]
I can confirm the issue is due to the wrong openssl version (32bit) being bundled inside the 64-bit package.

**Comment by tooomm** [comment]
Yes, I'm using the 64bit version on win 10.

Oh, did we worked with openssl recently and changed things?!

**Comment by ctrlaltca** [comment]
No, i suppose that our check for openssl was too generic and an update on appveyor broke it.

**Comment by ctrlaltca** [comment]
I've worked out a fix, here's a test build that should work: https://ci.appveyor.com/project/ctrlaltca/cockatrice/build/0.0.1-branch-fix_2031-build-295/job/s41lc2cxwnl36emb/artifacts

**Comment by ctrlaltca** [comment]
@thekingkazma we solved the issue, you can expect new versions from now on to work fine.

**Comment by woogerboy21** [comment]
@ctrlaltca This seems to have come back up again.  The most recent installers for the windows clients are throwing this error on the x64 version of windows 10.  Replacing the DLL's with different version fixes the problem.  I grabbed the DLL's from ( https://indy.fulgan.com/SSL/openssl-1.0.2l-x64_86-win64.zip ) but you may have a solution for the builds.

**Comment by austucus** [comment]
@ctrlaltca do you think you could help me with this issue but referring to the token download step rather than the card database step. I had the same error message "Network error: Error creating SSL context ()." but again on the tokens download step.

**Comment by tooomm** [comment]
This is definitely not a general issue. Works on 64bit Win 10 (with all win updates and Cockatrice 64bit) just fine for me. No problems in Oracle for mtgjson or tokens downloads here.

**Comment by ctrlaltca** [comment]
The appveyor logs building the packages shows that the correct version of the packages are being picked up:
 * 64bit: https://ci.appveyor.com/project/Daenyth/cockatrice/build/2.4.1-branch-master-build-776/job/n3mop2cy0ytmrj1s#L66
 * 32bit: https://ci.appveyor.com/project/Daenyth/cockatrice/build/2.4.1-branch-master-build-776/job/5k4ng6cvyo6daab6#L66

I can confirm that the openssl dlls included in Cockatrice-Unwrapped-2.4.0-x86_64_qt5.exe are 64bit; checking the libraries for dependencies, i can see that they still depends on the visual studio 2013 runtime (msvcr120.dll):

![schermata 2017-12-18 alle 23 24 17](https://user-images.githubusercontent.com/1631111/34131173-cf91efc8-e44a-11e7-923d-3acbf273578d.png)

So, while cockatrice itself is using the visual studio 2015 runtime, openssl will require the 2013 runtime to be loaded correctly at runtime (and make ssl work).

The libraries you linked ( https://indy.fulgan.com/SSL/openssl-1.0.2l-x64_86-win64.zip ) have no dependency on any MSVC, as stated on their README file.

Based on this, i suppose that ssl was not working on your win10 box because of missing msvc 2013 runtime.

**Comment by tooomm** [comment]
So we need to include that to the troubleshooting in the wiki... i try to do that tomorrow 👍

**Comment by NutellaGrande** [comment]
@ctrlaltca 

Just wanted to chime in and say that downloading the [64bit Visual C++ Redistributable Package for Visual Studio 2013 ](https://www.microsoft.com/en-us/download/details.aspx?id=40784) resolved this issue for me.  Thanks for the tip!  I wouldn't have gotten there without this thread.
