### ISSUE TITLE
Daemon-style server configuration

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2034]
I'd like to see a way to configure servatrice without restarting it. The best way I can think of to do this is to convert servatrice into a daemon, and either provide a configuration tool to communicate with it, or to have subsequent servatrice act as the configuration tool.

With this tool, it would be possible to add/remove users, change user roles, add/remove rooms, start/stop the server, etc.

I'm kinda guessing here since I don't have a very good idea of how they work (I can't read C++), but is it possible the use the websockets added by #1991 to facilitate communication between daemon and configurator?

**Comment by Daenyth** [comment]
Probably the best way to handle this is to reload config on sighup. There's
unclear questions though. What if it's set to auth mode and then changing
the config puts into into no auth mode?

**Comment by ctrlaltca** [comment]
This is surely something that is highly desirable to be added to servatrice.

> is it possible the use the websockets added by #1991 to facilitate communication between daemon and configurator?

We'd still need to add the relevant functions to servatrice, but the possibility of coding a simple UI based on a web client could help in speeding up the task.

> Probably the best way to handle this is to reload config on sighup

This is how it works now. There are two ways to make servatrice reload config:
 * on UNIX*, sighup the process
 * from cockatrice, login as admin, unlock admin tools and choose "reload config"

> What if it's set to auth mode and then changing the config puts into into no auth mode?

This scenario should be fine, since logged in clients will stay connected, while no auth will be required for newly-connecting clients. But surely there are other corner cases like this that should be handled.

**Comment by ZeldaZach** [comment]
With those corner cases, I'm fine with you having to restart the service / bring down the server to complete the changes

**Comment by woogerboy21** [comment]
YaY!  Some one else interested in giving servatrice some love :+1:

**Comment by ZeldaZach** [comment]
Closing as you can reload already while running
