### ISSUE TITLE
Deck Editor Card Search Inefficiency

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2054]
Deck editor is currently using `QList::contains()` whenever a character is typed/removed from the search bar. This is horribly inefficient and needs to be redone.

Using `Trie` would allow for a fast, anchored search, but it may have some downsides. What other options are there to help improve the search time from O(n) to something quicker.

Binary search maybe?

**Comment by Psithief** [comment]
String searches don't work like that. A binary search is only good for matching a whole value, not arbitrary parts of a value.

You may want to read up on them here: https://en.wikipedia.org/wiki/String_searching_algorithm

**Comment by Daenyth** [comment]
You definitely can binary search if the list is sorted by name prefix and we use prefix matching.

That said right now we use unanchored matching so we'd have to change the data structure to really improve it. I'll have a look at it eventually

**Comment by ctrlaltca** [comment]
Wait, the situation is a bit more complex here:
We have a list of cards in the card database, a CardDatabaseModel (used to extract and format card data out for the table view) and a CardDatabaseDisplayModel (used to filter and sort the list of cards).

When the user searchs for a word in the deck editor (or changes any other filter), the "model" gets invalidated and the list of card goes through this method: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabasemodel.cpp#L184

Comparing each card name is really not efficent by itself, but the situation is somewhat mitigated by the fact that the model will stop when enough cards are found to fill the visible part of the table.

In order to rework this and use a different data struct, i'm afraid we should abandon the use of Qt's model/proxymodel.

**Comment by Daenyth** [comment]
Note to self: trigram index implementation

**Comment by ebbit1q** [comment]
dupe https://github.com/Cockatrice/Cockatrice/issues/1720
