### ISSUE TITLE
Server shutdown UI update

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2085]
Currently the shutdown server UI asks for a reason and a time frame in minutes when wanting to shutdown the server.  We should consider updating the UI to have a date/time selection box and code in the calculations for minutes letting the server do all the hard work when scheduling shutdown.  One other update that could also happen to improve user experience is adjust the time that client notifications for shutdowns happen.  Something like a notification up front, then half the time till shutdown, followed by half that time and so forth till the 5 minute mark and then notification every minute.

**Comment by tooomm** [comment]
>Something like a notification up front

You mean like on initial connect to the server while there is a scheduled downtime show exact minutes left until restart? Then start the math and further popups based on that.
Is that already implemented?
<br>
>then half the time till shutdown, followed by half that time and so forth till the 5 minute mark and then notification every minute.

We have that logic now at least --> #2084 :+1:

**Comment by tooomm** [comment]
There should not only be the time left shown, but also the date/time itself that this results in (at best in local client time).

Because if you're away and only see a 1h upfront message when you come back, you've no idea if it's 55 or 35 minutes left. So you don't know if there is enough time to start and finish one more game for example.

**Comment by ZeldaZach** [comment]
It's not really worth our time imo
