### ISSUE TITLE
multiple tray icons and processes leftovers after closing the app

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2105]
<b>OS:</b>
win 10 64bit

<b>Cockatrice version:</b>
f87f677 (2016-07-22)

___
<br>

After closing the app sometimes tray icons are not killed and just disappear if I move my mouse over them.

But the real problem is that I experienced a few times now that after closing the app I need to manually kill processes which stick around. I realized that because the tray icons didn't close on mouse over anymore.
![trayicons](https://cloud.githubusercontent.com/assets/9874850/17080079/765daa7a-5123-11e6-99ae-9082fec8aab2.png)

**Comment by tooomm** [comment]
Other user with similar problem on Kubuntu 16.04: [July 23, 2016 10:01 PM](https://gitter.im/Cockatrice/Cockatrice?at=5793cd271b9de56c0ed61ba7)

**Comment by ctrlaltca** [comment]
> After closing the app sometimes tray icons are not killed and just disappear if I move my mouse over them.

This happens because cockatrice didn't remove the icon correctly when closing, or didn't close at all. Windows only notices that the icon is related to a no-more existing process only when you mouseover it, because it tries to ask the process if there's some mouseover behavior to apply. If this requests fails because the process doesn't exists anymore, then windows just removes the icon.

Did you happen to have local games open when closing the app? this could be related to #2096.

**Comment by tooomm** [comment]
>Did you happen to have local games open when closing the app?

Maybe. But #2096 should be included in the version that I'm using.

I did some further testing. To replicate:
- open local game
- close the app without closing the game first

**Comment by ctrlaltca** [comment]
> Maybe. But #2096 should be included in the version that I'm using.

Are you sure? #2096 has been merged just a few minutes ago, and it's currently compiling on appveyor.

**Comment by tooomm** [comment]
See my edit^^

Tested in the meantime and it seems to be fixed - Thanks!

**Comment by ctrlaltca** [comment]
Ok thank you for the update 👍
