### ISSUE TITLE
Related to function

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2110]
I am sure someone is on this but the EMN cards are not set up correctly. the "Related to" feature is not used in the token makers or with the Emblems.

**Comment by skwerlman** [comment]
This issue should be moved to [Magic-Token](https://github.com/Cockatrice/Magic-Token/issues), as its a token database issue, not a Cockatrice one.

**Comment by Jinxstands4Jinx** [comment]
magic-token?? but it is an issue when the cards are not linked and this is a cockatrice feature

**Comment by skwerlman** [comment]
The `reverse-related` governs whether a card appears in the "Create related card" dropdown. Those tags are managed by the Magic-Token project.

**Comment by Nightfirecat** [comment]
Please feel free to add more detail to the issue I created there: Cockatrice/Magic-Token#13

**Comment by tooomm** [comment]
Tokens working fine for me in EMN.
@skwerlman and @Nightfirecat Do you have problems with EMN as well? oO

Just tested again with Liliana Emblem and Desperate Sentry.

When did you updated your card database the last time?
In case you don't understand how things work with the tokens... all information which is needed for the `Create related card` feature not just comes from the card database, but also from our token file.
So in order to use that feature properly you need to have both - an up to date card database with EMN **and** an up to date token file.
The token file got updated 5 days ago and should be complete know.

**Comment by Nightfirecat** [comment]
I haven't tested, personally. I was just filing an issue in the right place.

**Comment by skwerlman** [comment]
I hadn't tested either, same as @Nightfirecat

**Comment by Jinxstands4Jinx** [comment]
will redo oracle and report back

**Comment by Jinxstands4Jinx** [comment]
All is good now i guess in the effort to update my lists with EMN spoilers i never touched the token database

**Comment by tooomm** [comment]
Once you run oracle properly you'll get the tokens as well. They are updated even before the set is released most of the time.

I recommend updating your cards.xml and tokens.xml with Oracle ([or use the ingame update option](https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#how-do-i-update-my-card-database-to-have-the-latest-cards)) once the set is officially released.
Oracle database > custom spoiler sets :P

**Comment by Jinxstands4Jinx** [comment]
yeah tom but those custom spoilers have their advantages as they come out
sooner and allow early testing :)

**Comment by tooomm** [comment]
Read my answer again ;)
Spoilers are perfectly useful and great. But should be replaced with "official" data once available.

>I recommend updating your cards.xml and tokens.xml with Oracle (or use the ingame update option) **once the set is officially released**.
