### ISSUE TITLE
Non-english card image/text support

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2122]
This is a meta-ticket centralizing information for non-english card support
- [ ] Download non-english card databases in some way #1876
- [ ] Use the client's language setting to select what language cards to show #841 
(should be a separate setting for card art language on its own)

**Comment by kascesar** [comment]
http://www.codexruler.com/base-de-datos-de-magic-assistant-actualizada-al-castellano/  (base de datos a español, hasta tarkir)

**Comment by tooomm** [comment]
mtgjson doesn't have image links, but foreign names and unique multiverse ids for some sets since v3. 
Check issue number 12 in their repo. But it's still work in progress I think...
We don't utilise v3 yet, though. @ctrlaltca was working on that once. 

No foreign card text in mtgjson as far as I can remember, but I'm not certain.

**Comment by EtaoinWu** [comment]
[http://gatherer.wizards.com](MTG Gatherer) uses cookies to mark the language. Cookie's name is `CardDatabaseSettings` and its value is `1=zh-CN` (if I am using Chinese language).

**Comment by Daenyth** [comment]
I think each foreign printing gets its own multiverse id, so that should be
enough. I'm pretty sure the cookie setting is for the web page contents

**Comment by tooomm** [comment]
Potentially useful link, thanks @ZeldaZach 
https://scryfall.com/docs/api/cards/collector

**Comment by Phantato** [comment]
I found a URL by using scryfall api that would help to get non-english card image:

`https://api.scryfall.com/cards/!set!/!set:num!/zhs?format=image&face=!prop:side!`

and one can simply change `zhs` for what language they want. But the thing is that this api need a lowercase set code rather than uppercase. I don't know whether the downloader could provide the lowercase set code

Hope this would help. @Daenyth

**Comment by ebbit1q** [comment]
I knew this was an option but while scouring the api docs I never found it, thanks!

**Comment by tooomm** [comment]
Here is a list of all language codes at scryfall: https://scryfall.com/docs/api/languages

**Comment by ebbit1q** [comment]
I got it working, exactly as intended: `https://api.scryfall.com/cards/!setcode_lower!/!set:num!/zhs?format=image&face=!prop:side!`
![image](https://user-images.githubusercontent.com/36401181/54883034-2620f880-4e61-11e9-872f-c28bbfad92d2.png)

**Comment by ZeldaZach** [comment]
@tooomm can we document the !sflang! feature on the wiki better? That's as good as the support will be for the time being.

**Comment by tooomm** [comment]
@ZeldaZach do you think the documentation is not clear enough already?
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs

There is also an example. And a link to the available set codes at scryfall...

**Comment by ebbit1q** [comment]
thanks for adding it to the faq

**Comment by tooomm** [comment]
From the settings we link to https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs already as well 👍
