### ISSUE TITLE
Cant get user registration to work on Servatrice

### ISSUE THREAD

**Issue by chairborne33** [Cockatrice/Cockatrice#2165]
<b>OS:</b>
Windows Server 2012 R2

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

___
<br>

I have a new servatrice setup and I'd like to allow users to use Cockatrice to register on the fly. Everytime I test I get the error "Registration failed for technical reasons on the server" The server log shows 
```
Fri Sep 16 16:01:24 2016 1ba662bca0 [Command_Register.ext] { user_name: "chairborne33" email: "" gender: GenderUnknown country: "" real_name: "" clientid: "19a13728f0b8327" }
Fri Sep 16 16:01:24 2016 Got register command:  "chairborne33"
Fri Sep 16 16:01:24 2016 "[pool 0] Error executing query: Field 'admin' doesn't have a default value QMYSQL3: Unable to execute statement"
Fri Sep 16 16:01:24 2016 Failed to insert user:  QSqlError("1364", "QMYSQL3: Unable to execute statement", "Field 'admin' doesn't have a default value")  sql:  "insert into cockatrice_users (name, realname, gender, password_sha512, email, country, registrationDate, active, token) values (:userName, :realName, :gender, :password_sha512, :email, :country, UTC_TIMESTAMP(), :active, :token)"
```

**Comment by chairborne33** [comment]
Is there a way to strip out those fields that Cockatrice doesn't provide an option for?

**Comment by woogerboy21** [comment]
What do you mean by "on the fly"?  And how are your users registering?  Things like "admin" are required to let the app know if the user is a plain user or mod or admin so removing it would break other things in the app.

**Comment by woogerboy21** [comment]
The closest thing I can think of to "on the fly" would be to set your config to "registration/enabled=true registration/requireemailactivation=false" .  User then would simply choose "register to server" from the menu, fill the information in and when they click submit it would create there account and then log them in.

**Comment by chairborne33** [comment]
So by on the fly I just mean the ability to Register To Server from Cockatrice. My users would be registering through the Cockatrice application. In my servatrice.ini file, the registration is set to enabled=true. and requireemailactivation=false.

**Comment by woogerboy21** [comment]
I see that some one has removed the portion of the servatrice configuration that mentions problems with strict mode enabled.  Can you verify you have strict mode disabled on your database server.  You can find details out in the issue discussion https://github.com/Cockatrice/Cockatrice/issues/865

**Comment by woogerboy21** [comment]
I can tell you that the woogerworks server is currently operating in the fashion you mention and the settings under the registration portion of the config are as follows:
~~~
[registration]

; Servatrice can process registration requests to add new users on the fly.
; Enable this feature? Default false.
enabled=true

; Require users to provide an email address in order to register. Newly registered users will receive an
; activation token by email, and will be required to input back this token on cockatrice at the first login
; to get their account activated. Default true.
requireemail=true

; Require email activation. Newly registered users will receive an activation token by email,
; and will be required to input back this token on cockatrice at the first login to get their
; account activated. Default true.
requireemailactivation=false

~~~

**Comment by woogerboy21** [comment]
I would recommend requiring emails for users simply for the ability for you to be able to contact them.  But its not required.

**Comment by Daenyth** [comment]
@chairborne33 I'm fairly sure as well that this is related to the strict mode setting.

There's some work needed to support strict mode, for now you'll need to use non-strict. Follow at #865

**Comment by chairborne33** [comment]
Switching to non-strict resolved the issue. Thank you very much for both of yours help.

**Comment by tooomm** [comment]
In case your server is public and you want to see him on our official site, let us know!

https://cockatrice.github.com
