### ISSUE TITLE
Server Full Multiple message box problems

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2176]
When a server has reached its capacity the client shows 2 boxes.  The top box displays the proper message about the server being at capacity but the bow below it shows the unknown error -1 message box.  

Solution should be as simple as adding a case statement for the id in https://github.com/Cockatrice/Cockatrice/blob/da2eb97c7b587b1b49bc1d93d4d9f717eb4ec275/cockatrice/src/window_main.cpp#L326 but should be investigated to be certain.

**Comment by Daenyth** [comment]
@wincinderith In the servatrice.ini there's a setting for maximum number of users. Launch a server with no registration and a low limit, say 2 or 3 users, and launch multiple cockatrice instances connecting to different unregistered names.

**Comment by wincinderith** [comment]
Thanks, I've got it now. Any chance I could have this assigned to me?

**Comment by Daenyth** [comment]
Github only lets us assign it to people in the org / with direct commit access. Our pace of development is pretty slow though, so don't worry about folks duplicating work. If you can link to a branch here that would help so that we can see what progress there is. Feel free to also hop on gitter if you need help with anything!

**Comment by wincinderith** [comment]
OK, I've submitted a PR: #2195
