### ISSUE TITLE
clang-format stuff

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2183]
https://arcanis.me/en/2015/10/17/cppcheck-and-clang-format/

And the branch.

(this ticket is a reminder for me for later)

**Comment by Daenyth** [comment]
wip style
```
BasedOnStyle : webkit

---
Language: Cpp
PointerAlignment: Right
ColumnLimit: 120
---
Language: Proto
DisableFormat: true
```

**Comment by ZeldaZach** [comment]
Any news on this?

**Comment by Daenyth** [comment]
No

**Comment by tooomm** [comment]
Since all repo branches got lost...

Here a write up from @Daenyth about his initial process on gitter:
https://gitter.im/Cockatrice/Cockatrice?at=5a5f9b4d5ade18be398aa836
>idgaf about brace style as long as it's consistent
In fact if someone can please pick up my clang-format branch
I have a beginning of a clang-format config file
the way I did it was to run clang-format over the codebase, examine the diff, find something that got a big diff, and see if clang-format had a toggle to make that diff smaller, then reset the codebase and run with the new settings
tedious iterative process
that said, if someone wants to just pick a style and commit to it and do one huge diff of formatting the whole codebase
When this is done, it means we will never have another comment on code format in PR ever again
and I think we can all appreciate how nice that would be
especially for new contributors!
