### ISSUE TITLE
Add "Playing Since" to the profile/user details

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2214]
I think it would be nice to allow users to specify when they started playing.
As a user you select one of the set names from a drop down. Other users can then see this on your profile.
- adds some more profile pride / customization
- allows users to know how experienced you might be

**Comment by Daenyth** [comment]
I'm not entirely sure this is aligned with the goal of being the best online kitchen-table card system. Do we want social network-like features? I don't think users will be able to trust this profile piece because a large enough portion of the userbase will just lie.

Maybe we could allow users to have a short free text field on their profile? They could link to outside profiles, put short pieces of info like this, etc. It would be more flexible.

**Comment by ZeldaZach** [comment]
@Daenyth That will require more moderation as spammers/derps will be writing bad things... If we're going on anything like that, I'd like it to be in the dropdown format.

**Comment by Daenyth** [comment]
If it causes more moderation I think that's a good thing; it gives toxic
users a way to preemptively out themselves

**Comment by tooomm** [comment]
`Playing since` should just be a year or month/year if at all...

The customizable field sounds ok, too.
