### ISSUE TITLE
Cards in game should stack in 4s, not 3s

### ISSUE THREAD

**Issue by bbwlover** [Cockatrice/Cockatrice#2224]
The current interface makes stacks of 3 cards. Why not make it 4? So when you have a playset, it doesn't make a stack of 3 and then another one

**Comment by Daenyth** [comment]
This is reasonable but unfortunately more annoying to actually fix than it would seem, due to how the server is aware of card placement on the board. Probably what we'd need to do is a multi-step rollout where we update the protocol/server, make the client aware of the same update but still using 3, then eventually make a forced upgrade for all users after some amount of time has passed, then update the client code to be able to create the stacks.

**Comment by Nightfirecat** [comment]
It might be just me, but is there a practical reason for needing stacks of 4s? One typically won't get all of their playsets of a card onto the battlefield in any given game...

**Comment by Daenyth** [comment]
I'm more interested in making the server care less about where cards on the board are, but that's a way bigger change. Physical layout really shouldn't matter. Unfortunately having the server aware of the layout is really nice for cards like fact or fiction, for example. Making the layout client-side-only would break that.

**Comment by MotherofRuins** [comment]
Stacking deeper is nice for when you run out of space horizontally and the display starts shrinking vertically.  It uses less pixel space per permanent.

**Comment by tooomm** [comment]
It still doesn't make sense to allow stacks of 4, if the only cards that you have (all) 4 or more copies on the battlefield on a regular basis are lands, but lands are not the main cause for shrinking table sizes.

No idea about other card games.

**Comment by Daenyth** [comment]
There's no real reason for it to be 3 either

**Comment by tooomm** [comment]
Actually there is a reason to have it be stacks of 4 instead 3... tokens! https://github.com/Cockatrice/Cockatrice/issues/2934
Never thought about it before.

**Comment by ZeldaZach** [comment]
This is fairly arbitrary. Kinda related to #1740
