### ISSUE TITLE
Message about unsupported features on server

### ISSUE THREAD

**Issue by Shiaulis** [Cockatrice/Cockatrice#2230]
<b>OS:</b>
MacOS 10.12 (16A323)

<b>Cockatrice version:</b>
Version 277d7e2 (2016-06-30)

---

<br>

Message _Your client appears to be missing features that the server supports.
This usually means that your client version is out of date, please check to see if there is a new client available for download._ appears every time I trying to connect to cockatrice.woogerworks.com

**Comment by skwerlman** [comment]
You're seeing these because new features have been added to the protocol since the last full release of the client. For the most part, these warnings are fine to ignore.

The changes I can think of that might be causing these issues are:
#2200: Username profanity filtering
#2209: Idle client timeout
#2220: Max user check fixes

There are testing versions available that have support for these features, but they are potentially less stable than the current release. You can find these builds [here](https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/#files), if you decide that the risk is worth it.

**Comment by Daenyth** [comment]
We should

- Make the warning message more explicit that it's ok to ignore and not a problem
- Add a setting to not show it every time you log in (remember the specific feature the server said is new and don't alert for that feature in the future, when the setting is enabled)

**Comment by woogerboy21** [comment]
Fixed with #2275
