### ISSUE TITLE
unknown login error 1

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2231]
<b>OS:</b>
Windows 10 home
<b>Cockatrice version:</b>
323fc06 2016-02-02
___
<br>

I got unknown login error 1

**Comment by skwerlman** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#unknown-error--1-message-upon-login

**Comment by tooomm** [comment]
If you need further assistance let us know! ;)

**Comment by Daenyth** [comment]
@skwerlman that link isn't accurate in this case, though it's close.

@philipcliang It's because the server is at its maximum user limit right now, but your client doesn't know how to display that.

We can update the wiki to help people understand what's going on here

**Comment by tooomm** [comment]
@woogerboy21 whats your cap atm?

**Comment by skwerlman** [comment]
We should probably add user cap information to the server list

**Comment by tooomm** [comment]
I don't think that helps too much, information there should be as static and basic as possible.
Otherwise it will be likely outdated and wrong. It doesn't help the user to much either, if he knows that the cap is at 500 or 1000.

But there had been talks about receiving/sending server information to the client which are set in the config (authentification, registration etc.), it should better be included there at one point.

**Comment by Daenyth** [comment]
@skwerlman it will be added to the in-client server list once we introduce the ability to ask the server for its information without being logged in

**Comment by skwerlman** [comment]
Makes sense.
