### ISSUE TITLE
ip_address in cockatrice_sessions is too short

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2276]
Currently, the `ip_address` column in `cockatrice_sessions` is a `char(15)`, which is fine for storing IPv4 addresses, but it is too short to store IPv6 addresses, which can be as long as 39 chars.

In order to store IPv6 addresses, the `ip_address` column should be changed to a `varchar(39)`.

**Comment by Daenyth** [comment]
:+1:

**Comment by woogerboy21** [comment]
One thing to mention about this, I would need to double check were else the IP address is stored in the DB (ban table comes to mind) but changing this value(s) size may result in breaking things like currently defined ban's since the new length value(s) would not match the old stored value(s) with shorter lengths.

**Comment by skwerlman** [comment]
IP addresses are also stored in `cockatrice_log`, `cockatrice_bans`, and `cockatrice_servers` as a `varchar(255)`. These can all be reduced to a `varchar(39)`, if desired (though it wouldn't save any space)

Since the ip is stored independently (and correctly) in `cockatrice_bans`, i don't think this should have any effect on bans.

**Comment by woogerboy21** [comment]
YaY for consistency....   teaches me to assume its consistent across all the tables 💩
