### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2338]
<b>OS:</b>
Win 10 Pro 64bit

<b>Cockatrice version:</b>
Cockatrice: All Hallow's Eve, Revision 1 - f7c8651d (2016-12-30)
**installed with in-client updater**

___
<br>

After installing the new release, I keep getting update notifications from `Help --> Check for updates`

![updater](https://cloud.githubusercontent.com/assets/9874850/21614510/fae4beaa-d1d9-11e6-9475-dcd3e6906be5.png)

**Comment by woogerboy21** [comment]
Does anyone that works with the bintray stuff understand how the file at https://api.bintray.com/packages/cockatrice/Cockatrice/Cockatrice/files is generated?  If I am reading it correctly it shows a client version available from 01/01/2017 on the windows platform yet we dont have that client version anywere that I can see.

**Comment by tooomm** [comment]
For clearness, the content of the bintray api call for the win64 build reads:
```
{
"name":"Cockatrice_All_Hallows_Eve_Revision1_win64.exe",
"path":"Cockatrice_All_Hallows_Eve_Revision1_win64.exe",
"repo":"Cockatrice",
"package":"Cockatrice",
"version":"2016-12-31_All_Hallows_Eve_Revision1",
"owner":"cockatrice",
"created":"2017-01-01T22:05:50.113Z",
(...)
}
```

>"version":"**2016-12-31**(...)"
vs.
"created":"**2017-01-01**(...)"


<br>
Question stands:

>Does anyone that works with the bintray stuff understand how the file (...) is generated?

Where does the date in "version" and the date for "created" exactly comes from?
How can we avoid differences? Or do we need to change the handling in the updater? Did bintray change something again?

**Comment by woogerboy21** [comment]
@tooomm 
The code block for the updater for finding the client info from bintray looks like this:
```
QDate UpdateChecker::dateFromBuild(QVariant build)
{
    QString formatString = "yyyy-MM-dd";
    QString dateString = build.toMap()["created"].toString();
    dateString = dateString.remove(formatString.length(), dateString.length());

    return QDate::fromString(dateString, formatString);
}
```

When the updater looks to find the date on bintray to compare the date of the current client  ```buildDate = QDate::fromString(VERSION_DATE, "yyyy-MM-dd");```  (of the running client version information) to the date(s) of the returned data off bintray (see above using created date) .  If the current running version < created date then it notifies you of an update.  So far the values work out to be current version = 2016-12-30 and the bintray dates pulled from the returned data is 2017-01-01 .  2016-12-30 < 2017-01-01 so the message is displayed.

I don't think there is anything updated or changed.  I have a feeling what happened is since we have to manually upload the files for a release, the creation date simply reflected the time the files were uploaded which was on the 1st were as the client was compiled/created on the day before.  Im betting it simply worked out to be bad timing of events.

**Comment by tooomm** [comment]
As reported [here](https://github.com/Cockatrice/Cockatrice/issues/2353#issue-199386003) on a side note: the problem also exists on mac. So not just windows only!

**Comment by tooomm** [comment]
Problem persists with `dab7316 (2017-01-19)` aka "Cockatrice: All Hallow's Eve, Revision 2" 

![untitled2](https://cloud.githubusercontent.com/assets/9874850/22156299/f98b24b6-df32-11e6-9b78-6806f9621bd7.png)

**Comment by ZeldaZach** [comment]
The issue persists b/c the merge was done at like 1130pm and the release didn't go live till around 1230am the next day. It's an annoying issue that has always been around but we only found out about once we did late merges

**Comment by tooomm** [comment]
We could have easily avoided that... since we knew about it before.
Too bad it happened twice in a row within just 3 weeks.

I hope we get another release/update system in place soon. :)

**Comment by ctrlaltca** [comment]
Fixed by https://github.com/Cockatrice/Cockatrice/pull/2362
