### ISSUE TITLE
Deck editor paste formatting

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2366]
<b>OS:</b>Win 7 SP1
<b>Cockatrice version:</b> f7c8651d (2016-12-30)
___
Can we go back to the old formatting or something similar? The current way doesn't help clarity much, what it definitely does do is make it a chore to paste decklists anywhere else (deck sharing sites like tappedout, magic league tournaments). A way to switch between the two would do the job, but clutter the settings. Example of what I'm hoping for:
```
4 Goblin Guide
4 Lightning Bolt
8 Mountain
Sideboard
SB: 2 Mountain  
```

**Comment by Daenyth** [comment]
How about a menu entry that lets you select the output format and then the copy action goes by that format?

**Comment by ZeldaZach** [comment]
^ that works for me

**Comment by tooomm** [comment]
What did change exactly?
Was it the comment above each group with quantity?
Why did we change it though?

Maybe that is really not too helpful in the file itself since it's displayed in-client anyway and just adds problems in evey day use cases as described?^^
We had some more reports about this beeing problematic if I recall correctly.

**Comment by ctrlaltca** [comment]
I suppose this is related to #2126
