### ISSUE TITLE
Left Click

### ISSUE THREAD

**Issue by callmejustin** [Cockatrice/Cockatrice#2367]
<b>OS:</b>
Win 7
<b>Cockatrice version:</b>
Version f7c8651d (2016-12-30)
___
<br>
When ever im in a game and i left click it does the thing where it would hold left click and starts making a box. this makes it so that i would select cards that i dont want and i have reinstalled cockatrice and it still has this problem

**Comment by ZeldaZach** [comment]
I'm trying to understand what you're saying, so let me know if I misinterpret: 

You are creating this box
<img width="874" alt="screenshot 2017-01-16 16 07 18" src="https://cloud.githubusercontent.com/assets/7460172/21999019/f18db13c-dc05-11e6-9123-e9d49d129d0b.png">

and highlighting cards, but it's selecting cards you don't want?

If so, this is a feature of the client (the box) and it's used to make mass changes at once (i.e. highlighting all your creatures to attack with at once instead of individual taps)

**Comment by Daenyth** [comment]
I think he's saying it's acting like he's holding click when he wasn't.

Try:
- Unplugging the mouse and replugging it.
- Rebooting
- Checking windows accessibility settings; I think there's a system setting that acts like this

**Comment by woogerboy21** [comment]
Ill see if I can stand a windows 7 VM up but so far I cant reproduce the issue on any windows boxes I have around.  Though the issue sounds related to the PC @callmejustin is using.

**Comment by Nightfirecat** [comment]
I can say I haven't seen this issue on my primary home PC, and that's on Win7.

**Comment by callmejustin** [comment]
i have fixed it somehow thanks a lot guys
