### ISSUE TITLE
Error 0xc000007b after troubleshooting

### ISSUE THREAD

**Issue by owerbart** [Cockatrice/Cockatrice#2392]
OS: Windows 10 64 bits

Sorry, but in the last thread I forgot to state that I already visited that Troubleshooting page and nothing worked, I tried changing the name of the file, I'm already 100% positive that I'm trying to run the 64-bit version (i already tried too to run the 32 bit one), I already searched online and found out about some .dlls that needed to be changed. I already did that and still I can't play :(

**Comment by woogerboy21** [comment]
0xc000007b is generally due to a mismatch in runtime files.  Either you have the 32bit client installed and the 64bit runtimes from MS installed or vice versa.  My suggestion would be to remove all clients that might be installed and then download and install the appropriate version of the MS runtime files , followed by the corresponding version of the cockatrice files.

You can find the links to the various MS run time files in the https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found section.  I believe if your trying to use the precompiled versions of the client through here you would need the 120 version of the DLL.

**Comment by owerbart** [comment]
Sorry to sound repetitive, but I already uninstalled every version of cockatrice and imstalled the proper version. I will check with the .dll file link you posted and report back.

**Comment by woogerboy21** [comment]
Figure things out?

**Comment by owerbart** [comment]
still nothing. I remember having this problem like 2 or 3 years ago, and I remember having to install an specific version of cockatrice, which was name CockatriceWindowsClientQT4.

i already tried with all of those DLLs, and nothing seems to work :(

**Comment by woogerboy21** [comment]
Hmm... well if there is a reason you can not run Qt5 you wont be able to run the cockatrice application.  We dropped support for Qt4 a while back.

**Comment by woogerboy21** [comment]
The only thing I remember running into is if you have a processor that doesn't support SSE2 you can get the same error.  But that would be either a very old intel based machine or there are some AMD based processors.

**Comment by owerbart** [comment]
I don't know how he did it, but my sisters' fianceé came home last night, I told him about this problem, and I left my laptop with him this morning to see if he could fix it. I stepped to my sisters' house, she said that her fianceé took a look at it and now it's somehow working perfectly. I'm going to ask him tonight to see what was the error so I can report it to you guys

**Comment by tooomm** [comment]
Cool, please come back with his solution and spread the knowledge @owerbart! 👍

**Comment by ctrlaltca** [comment]
Closed: sister bf timeout.
