### ISSUE TITLE
Ubuntu 16.04 failed login request

### ISSUE THREAD

**Issue by Gunman28** [Cockatrice/Cockatrice#2407]
<b>OS: Ubuntu</b>
Ubuntu 16.04

<b>Cockatrice version: d82564d (2016-07-15)</b>

___
<br>
Have been getting the error
 
"Failed Login
Your client does not support features that the server requires, please update your client and try again."
Additional Details
"Missing Features:
      idle_client"

Just finished deleting all the old files and recompiling and reinstalling as described here: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#ubuntu-16xx

Still getting the same message.

A couple weeks ago was getting the same error but wasn't stopping me from connecting.

**Comment by skwerlman** [comment]
d82564d is a very old commit. Did you remember to run `git pull` before recompiling?

**Comment by Gunman28** [comment]
does the 'git clone git://github.com/Cockatrice/Cockatrice' step not get the most recent release? If not could you tell me what I need to pull?

**Comment by woogerboy21** [comment]
> git clone git://github.com/Cockatrice/Cockatrice

This should grab the most recent code revision assuming you don't already have the "Cockatrice" folder with a previous pull.  If you do you should either delete the folder and start from scratch using the git clone command OR you can change into the directory and should be able to use ```git fetch origin``` to fetch all the changes followed by ```git reset --hard origin/master``` to make sure  your at the master branch with no changes.  Then run your build commands.  FYI, doing the fetch method may save a bit of time depending on what components haven't changed since your original code base and the new code base as they wouldn't have to be compiled again.

Obviously removing the folder and re-cloning everything would be the most sane/safe method if your not concerned with any changes you might have made.

**Comment by skwerlman** [comment]
> Obviously removing the folder and re-cloning everything would be the most sane/safe method if your not concerned with any changes you might have made.

Alternatively, if you know for a fact that you haven't made any local changes (aside from the `build` folder), you can just run `git pull` in the Cockatrice directory, which will achieve the same but much quicker.

**Comment by Gunman28** [comment]
I got everything working now. Seems I had symlink to a copy of the run file from the old build and it was getting launched every time I called from the terminal.
