### ISSUE TITLE
I am Keenojags on the server and I can't get in, it keeps crashing can someone see if I have an ip ban or someone over extended a range or something?

### ISSUE THREAD

**Issue by Azreal16** [Cockatrice/Cockatrice#2408]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by Daenyth** [comment]
There's no actual information here about what your problem is.

Fill in the prompt about os and cockatrice version, and describe the issue. Include any error messages or screenshots if relevant. If it's server-specific issues you'll need to resolve it with the server owner - we can't help you with bans or anything.

Reopen when you have information
