### ISSUE TITLE
Cockatrice does not update on Mac

### ISSUE THREAD

**Issue by fbroma** [Cockatrice/Cockatrice#2554]
<b>OS:</b>
*OSX 10.11.6*

<b>Cockatrice version:</b>
*1/19/17.*

__________

*Will not update cockatrice. After downloading update, cockatrice crashes, every time.*

**Comment by Daenyth** [comment]
Can you be more specific? Crashes how? Is there an error message? When does it happen?

If it crashes when you do things with tokens, it's a known issue that's fixed in development and we will have a new release out hopefully within the next day or two - if you want the fix sooner, you can follow the compile instructions from the wiki, or download a development snapshot from here https://github.com/Cockatrice/Cockatrice/releases/tag/snapshot0.0.4

**Comment by Daenyth** [comment]
Reopen if you have more specific info
