### ISSUE TITLE
Oracle UX improvements (workflow and UI mockup inside)

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2571]
The current flow for Oracle looks like this:

1. Select language
2. Select source
3. Wait for download/import to complete
    - If the download fails, you're stuck. There's no way to progress. (#1364)
4. Decide whether or not imported data should be saved in the default location
    - If it is, progress
    - If not, the user is asked to find a suitable place to save the xml file. This location is not stored, so the user must navigate to it each time they run oracle.
    - A log is shown here
5. A modal appears, saying that it saved the xml file
6. Select source for token data
7. Wait for download/import to finish
8. Decide whether or not imported data should be saved in the default location
    - If it is, progress
    - If not, the user is asked to find a suitable place to save the xml file. This location is not stored, so the user must navigate to it each time they run oracle.
    - No log is shown here (inconsistent with the same screen for card data)
9. A modal appears, saying that it saved the xml file
10. Oracle exits on its own

This flow has _lots_ of problems:
1. Why are there 10 steps involved in importing 2 files?
2. Its not possible to select where to save the xml until _after_ you've downloaded it.
3. The checkbox for deciding where to save xml data is easy to miss.
    - Why is it even a checkbox?
4. If you only want token data, you have to get card data too
5. If you only want card data, you have to know to quit manually
6. Modals are obnoxious

I suggest reworking Oracle so that it has a flow like this:
1. Select language, and whether you want card or token data, or both
2. Select where to fetch card/token/both data from, and where to save the resulting files
    - have the fields for both there, but grey out any which are unwanted
3. Download and import the wanted data
4. Show a finished screen
    - A log is shown here
    - Any errors in the last step are presented to the user here
    - Clicking Finish closes the app

**Comment by tooomm** [comment]
linking https://github.com/Cockatrice/Cockatrice/issues/1364

**Comment by tooomm** [comment]
We could also query @tritoch's spoilers with oracle and include them in the future, to stop the mess with custom sets and the need to delete them later once available on mtgjson.

 - [x] Update Main Card Database (mtgjson)
 - [x] Update Token Database
 - [ ] Include newest Spoiler into Main Card Database

If you check it, it'll include them into cards.xml. That way, if we priorize the AllSets.json data, they get just included if not already found in mtgjson (aka released on gatherer).
Will make the process for users easier, lower their waiting time and explanations needed in main chat. :D

**Comment by Daenyth** [comment]
I'm not sure we should do that, at least for now. Let's focus on cleaning up what we have, maybe we can consider that change later

**Comment by skwerlman** [comment]
If we do end up adding spoiler support in future, I don't think they should get merged directly into `cards.xml`. It'd be better to add them as a separate `spoilers.xml` in the `customsets` folder.

**Comment by tooomm** [comment]
I created a mock-up taking the steps from above:
>I suggest reworking Oracle so that it has a flow like this:
>
> 1) Select language, and whether you want card or token data, or both
> 2) Select where to fetch card/token/both data from, and where to save the resulting files
           - have the fields for both there, but grey out any which are unwanted
> 3) Download and import the wanted data

1) Select language + select wanted updates (any combination of card updates, tokens, spoilers...)
![mockup1](https://cloud.githubusercontent.com/assets/9874850/25087123/0fc79eb6-236d-11e7-9b78-dd8e41e224c0.png)

2) Give links to online sources or provide local files for each of the selected sources from step 1
![mockup2](https://cloud.githubusercontent.com/assets/9874850/25087128/143651a4-236d-11e7-962b-2361cc6a30d5.png)

3) Downloading+parsing starts. Tokens are greyed out here (in case you deselect them in step 1)
![mockup3](https://cloud.githubusercontent.com/assets/9874850/25087138/19d7b648-236d-11e7-9b0b-e74389dc515e.png)

**Comment by tritoch** [comment]
That looks great.  The only thing lost is

- Changing destination for xml files.

I see you can view the file directly, but that may be ill-advised for an 8MB file - could choke some text editors.

**Comment by tooomm** [comment]
>The only thing lost is changing destination for xml files

Jep, I don't think it's needed. It should be in the advanced screen (step 2) though, if at all.
I guess if you want the file in a special location you just open the folder at the end and cut/move it where you want it to be.
But in general you just need to change the location if you adjusted your default location in Cockatrice settings I think? Oracle should just pick up that custom location from the settings.ini instead... to keep Oracle as simple as possible.
If you still need the file in a different place, you can open the location and move the file around. We offer help to open the locations from within the client and in my mock-up in Oracle as well.


>I see you can view the file directly, but that may be ill-advised for an 8MB file - could choke some text editors.

It should better be named "Show location" for sure, not "Show file". Since it shouldn't **open** the file! Just opening the corresponding folder.

I think we planned on integrating foreign pictures in the client without the need of dealing with several .json files etc. There is also a ticket.
But that will take some time since mtgjson needs to include this information for all sets first, before we can parse it with Oracle and offer options in Cockatrice to download different pictures. It's also ticketed on the mtgjson repo and he started working on it. I guess the information is already there for some sets.
For now, I think people need to deal with customizing stuff if other pictures are needed.

**Comment by tooomm** [comment]
Oracle should also validate any xml that is imported and throw useful errors (Token, Spoiler...): #2065

**Comment by ZeldaZach** [comment]
We want to get rid of Oracle at some point, in favor of distributing databases (See #4109) as such I don't find playing with this option worth our time
