### ISSUE TITLE
"Add to buddy list" and "Remove from buddy list" options are gone from user related context menu everywhere in the client

### ISSUE THREAD

**Issue by MopDa** [Cockatrice/Cockatrice#2572]
<b>OS:</b> 
Windows Server 2008 R2 Enterprise x64

<b>Cockatrice version:</b>
ef7670a (2017-03-31)
__________

Suddenly found myself in the situation described in subject. Dug the code a little and found out that this menu items are not shown to unregistered users, but I'm a registered user for sure (username:"MopDa")

Buddy list is now at 190 items (which doesn't look like its full or something) and there is no real reason to hide "Remove from buddy list" item even in that case. I have no real way to remove users from buddy list at the moment.

Only thing I remember which wasn't commonly used by me, and which I did today is adding user to buddy list by typing in its name in account tab (Type his name in the "Add to buddy list" field, then hit enter) when the user was offline (he gone offline so I had to type it in there) and I made a typo once, or twice. New buddy was added, but couple of hours later I found myself in this troublesome state.

Reconnected to server 5 times, restarted client 2 times, reinstalled client once - no success.

What do? Thanks

**Comment by Daenyth** [comment]
This is a known/fixed issue - #2560

The next full release will have a fix in it.

@ZeldaZach Can you cut a new prerelease? And make a doc on the wiki for convenience telling the rest of us how? I remember it's pretty simple, I just want it documented because I forget things :P

@MopDa once a prerelease is out, you can change your "check for updates" preferences to use the development update channel and it will look for prerelease builds
