### ISSUE TITLE
Add notice about downloading spoiler updates

### ISSUE THREAD

**Issue by Typhon126** [Cockatrice/Cockatrice#2596]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
dab7316 (2017-01-19)

__________

A simple question for the DEVS. Is it possible that we can have a screen pop up for all players when hoping into the server or main for Woogerworks (Or any other server) to inform players of using cards from Unreleased sets (as of this post it's 4/17/2017 and Ahmonket is coming out) to please have it in their game description. And if possible can you also have them have links ready for players who don't know/use Ahmonket cards (or any unreleased set) so there isn't confusion among players? I've already had issues with players not wanting to provide links for the cards or if I don't know what they do (as I'm not uber familiar with unreleased set cards) kicking myself and other players in the server from the games, simply because we don't know what a future card does or doesn't do. 

Thanks,
Typhon126

**Comment by tooomm** [comment]
Normally people just ask in main chat and many many people happily provide help with unreleased sets.
Right now they are mostly linking you to http://www.cockatric.es/spoiler/. There you also find explanations, but chat will help you with that too if you ask friendly.
People in games though might just want to start a game, and are not patient enough to explain and wait 15min for you until you maybe managed it.
Generally speaking you find information about how to deal with custom sets and such in our wiki: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-%26-Sets

I guess the problem is many people don't know how trice works regarding to cards and the database. So they don't understand the process and need for databases and how they interact with each other or influence the information available in the app.

Anyway we can't force individual server owners to put special information in their server description or welcome messages. There needs to be another way of helping people.

**Comment by Daenyth** [comment]
I don't think a popup will be effective or useful. Popups are obnoxious - everyone hates them. We certainly don't want it to show up more than once, because that's useless. Even showing once at all might be useless for most people. 

I agree it's really annoying to be in the chat and have people asking for the spoiler link over and over, but I don't think this is the right solution.
