### ISSUE TITLE
Address the feedback in #2605

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2608]
To keep the code clean I have given feedback on the #2605 PR.
@ZeldaZach mentioned in the PR that he can address it, though there are other tickets he would work on.

@ctrlaltca maybe you want to look into it as you signed off on the PR?

**Comment by ZeldaZach** [comment]
As I said, since it's a relatively simple PR you're free to open another PR with the changes you think are better and we will gladly review it

**Comment by backendr** [comment]
I think its better if you clean your own PRs/code? That way it may prevent these issues in future.

**Comment by Daenyth** [comment]
Yeah in general we should try to address style concerns in the same PR. Especially as we hope to get more contributors, readability and factoring become more important. It's an area we're somewhat weak on with the years of organic growth.

In this specific case since there's not a functional concern I'll leave to to you guys to consider whether you want to make another PR to clean it up.

And yes, we should document the peer review process. Right now it's just that CI passes and there's an approved review from someone with commit access
