### ISSUE TITLE
Gideon of the Trials Emblem - Spelling

### ISSUE THREAD

**Issue by cloomis4234** [Cockatrice/Cockatrice#2612]
<b>OS:</b>
Win 7

<b>Cockatrice version:</b>
Version dab7316 (2017-01-19)

__________

In the description for "Gideon of the Trials (Emblem)", "game" is spelled "ganme"

**Comment by ZeldaZach** [comment]
This is an issue for the token repo. Thanks for your help finding mistakes!

**Comment by tooomm** [comment]
Haha Zach, you should either fix it or open an issue and put a simple link here... just closing is not helping. 😆 

@cloomis4234 fixed and available if you run oracle in 1-2 days: https://github.com/Cockatrice/Magic-Token/pull/24

Tokens are just semi related to the Cockatrice app, that's why we have a special repository for that. So if you find mistakes it's best to open issues in the token repo to make sure it gets fixed! https://github.com/Cockatrice/Magic-Token
