### ISSUE TITLE
If a player gets kicked tell so, not just "leaves game"

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2624]

**Comment by Daenyth** [comment]
I'm not sure this is worth fixing because it will require a protocol change and a forced update

**Comment by tooomm** [comment]
Considering that we could tell if a user closed a game, left a game, got kicked, closed the client/crashed OR just lost connection.

**Comment by Daenyth** [comment]
I'm not convinced this is worth forcing an update on people. That's always a disruption to the userbase.

Maybe we could add a field to the existing leave game event for the reason, instead

**Comment by ShrewMaster** [comment]
I second this. Sometimes hosts are rude to other players just because. I've even caught hosts lying saying a player left the game on its own, and then have that same player tell me he/she was actually kicked out. This update would help other players access how much we can trust the host's judgment and know if this is a game worth joining or not.

Note that I'm not saying this needs to be done ASAP, but it would be a worthwhile feature to have on the next Cockatrice update.

**Comment by Daenyth** [comment]
I think we can probably add a reason field to the existing "left game event" message. Older clients would not know about it and continue to say "left game" but newer ones would know about it and display the reason
