### ISSUE TITLE
32-bit version doesn't launch

### ISSUE THREAD

**Issue by sewageblip** [Cockatrice/Cockatrice#2664]
<b>OS:</b>
Windows 8

<b>Cockatrice version:</b>
I don't know because it won't open...

__________
Error message I get on trying to launch it:

Entry Point Not Found
The procedure entry point _except1 could not be located in the dynamic link library C: \Program Files\Cockatrice\Qt5Multimedia.dll

**Comment by tooomm** [comment]
>Cockatrice version:
I don't know because it won't open...

Can you tell us the name of the installer file instead and where you downloaded it?

In addition please try our newest official development release from here:
https://github.com/Cockatrice/Cockatrice/releases/download/2017-04-25-Development-2.3.17-beta003/Cockatrice-2.3.17-beta003-x86_qt5.exe

As well es the latest main release:
https://github.com/Cockatrice/Cockatrice/releases/download/2017-04-15-Release-2.3.16/Cockatrice_Thopter_Pie_Network_Revision2_win32.exe

**Comment by sewageblip** [comment]
I've since deleted the installer but I'm 95% sure it was Thopter revision 2. I'll try the development build when I get home

**Comment by Daenyth** [comment]
I really don't think this is a 32bit thing. I don't think windows 8 *has* a 32 bit version, so 64 should definitely work

**Comment by ctrlaltca** [comment]
Win 7, 8, 8.1 and even 10 have a 32bit version. The error itself sounds like the bundled Qt5 needs a more recent vcredist package.
Please try to follow the instructions at: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found , i suppose the "120" version is the correct one, but i could be mistaken.

**Comment by sewageblip** [comment]
120 worked, thanks ctrlaltca

**Comment by Nightfirecat** [comment]
I'll update the wiki with this error message later today. @ctrlaltca is "120" always the right version to stick with, or is that dependent on the OS/something else?

**Comment by ctrlaltca** [comment]
@Nightfirecat we are currently building cockatrice on Appveyor using MS Visual C++ 2013, that corresponds to the "120" library version.
A list of compiler/library versions is available here: https://github.com/WPN-XM/vcredist

**Comment by Nightfirecat** [comment]
Gotcha. I'll reference that for now then.
