### ISSUE TITLE
disconnect leave reasons not working correctly

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2697]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Version 2.3.17 (2017-05-05)

__________

In #2633 we introduced several leave reasons which should get passed from the server to other clients:
> OTHER = 1;
USER_KICKED = 2;
USER_LEFT = 3;
USER_DISCONNECTED = 4;

But they are not working as intended.
So far I've just seen kicked and left working correctly...
<br>

If a user disconnects from the server you just see:
>[00:19:28] xxx has lost connection to the game.

Happened to me all the time so far, never saw "disconnected".

cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
And the problem is?

For registered players the game engine is using the ping time to check each player's connection to the game, and the ping handler outputs the "has lost connection to the game" message on the client.

The USER_DISCONNECTED event is only used for unregistered players (eg. server without db), spectators and players being forcibly disconnected by the server (eg. server shutting down).

**Comment by tooomm** [comment]
Then its behavior was just never explained correctly maybe?

<br>
We spoke a lot about this in the pr itself...

Quoting from there:

 >> When a user closes the app it'll show "left" or "disconnect"?
>
>If you "menu->disconnect" from the server, or just close the whole cockatrice app, **it will show "disconnect"**.

>> When a user restarts his PC or his Internet connection drops, what will be shown?
>
>**"disconnect"**

So there is a variance from your feature description and the actual behavior. That's the "problem". ;)

**Comment by ctrlaltca** [comment]
You didn't state that your example user was a register player on a server running with a db ;) :D:D

**Comment by ctrlaltca** [comment]
Well, we could rework the messages in order to make them more consistent:
 * Player has lost connection to the game.
 * Player has restored connection to the game.

**Comment by tooomm** [comment]
Haha, well played. ;)

So bug or feature? Can we do something about that?

**Comment by ctrlaltca** [comment]
> (Actually I'm not sure if the restored connection shows up if somebody disconnects manually and reconnects - I assume so)

Yes, if you are a registered user and disconnected in the middle of a gameplay, when you reconnect you should rejoin the game automatically. The server has no real way to understand if you disconnected on on purpose, by mistake or it was just your cat playing with the keyboard.

**Comment by Jinxstands4Jinx** [comment]
Why was this even added? I do not get why people would even care to know this info

**Comment by tooomm** [comment]
We argued and discussed about it before on gitter and github.
If you don't feel it's useful... well, most think it quite is @Jinxstands4Jinx . ;)
<br>

Hey @ctrlaltca. I'm further elaborating on #2633... I'm wondering if we have to double the messages.
We show the reason in brackets, but the reason could just be the string itself?!

"xxxx has left the game (player left the game)"
"xxxx has left the game (got kicked by game host or moderator)"
"xxxx has left the game (player disconnected from server)"


Just use:
 - xxxx has left the game
 - xxxx got kicked by game host or moderator
*why do we have the expansion at all? it gives no more information - it just names two potential user groups with kick rights. if you got kicked, somebody had the power to do so, the message doesn't tell you if it was the host or a mod, so you don't know anyway. it could even be wrong if it was an admin for example. not telling the exact user either. so just scrap it!*
--> **xxxx got kicked**
 - xxxx has disconnected from the server (well, too bad this is only used for unreg and other special cases...)

They all imply that the user left. So we don't need to tell that twice!
The spectator messages are fine by the way and don't need to be changed I think.

So two things. Adjust the reasons a bit, and make them the only message appear on leave.

**Comment by Jinxstands4Jinx** [comment]
I do not recall arguing this on gitter as i do not have a gitter... but anyways this is a Huge Drama machine. Honestly, who cares why a person left the game? Unless we are going to give the "leaver" an option to leave a specific reason as to why they left...then the poor shmo left in the room should not care or be given any reason.   I understand knowing when such and such user was kicked. thats fine.  Most people leave games for their own reasons. life happens, their opponent is just too rude to be dealt with. The game is over, They have no outs and instead of wasting time they try to be respectable and leave, sudden disconnect due to weather or Cat. ETC.  When you say that they left for "reasons unknown" you allow the people or person left to assume that the person who left rage quitted and then they start talking bad about that peron because as it seems to them they rage quit alot. This creates Drama....Do we need more drama??  As i said if you want to have this feature it MUST swing both ways. Allow the person leaving to actually say why they are leaving, even if they say nothing. They should get a prompt asking "why are you leaving?"

**Comment by Daenyth** [comment]
I think it's enough to distinguish between leaving from kick and leaving from client activity. Beyond that is diminishing returns.

Does it work for kicks?

**Comment by Jinxstands4Jinx** [comment]
Yes it does. but other than kicks i see no reason to ever have this unless
we got all the way.

**Comment by ctrlaltca** [comment]
```
OTHER = "Server doesn't support this feature"
USER_KICKED = "kicked";
USER_LEFT = "user left";
USER_DISCONNECTED = "server is shutting down, no db or spectator";
```

Sometimes people asks why code is stale, see [recent comment](https://github.com/Cockatrice/Cockatrice/issues/479#issuecomment-299859992), but doesn't realize that developers spend more time on tickets, debating on [details](https://en.wikipedia.org/wiki/How_many_angels_can_dance_on_the_head_of_a_pin), instead of working on the code.
See the discussion in #2624, #2633 and now this ticket just to work a trivial change like this one.

**Comment by tooomm** [comment]
>"reasons unknown"

This is just a fallback in the protokoll in case something goes wrong I guess and should never display.

We just display kick, left game and disconnect. While disconnect just works for unregistered player and spectators if I understood ctrlatlca correctly.
So we basically just have kick and left game. If a user forces a trice quit or has other internet problems ongoing there will still be the lost connection message though.

**Comment by ZeldaZach** [comment]
I don't really see any issues... @tooomm ?

**Comment by tooomm** [comment]
The initial feature seems to work as designed, though @ctrlaltca missed some details in his feature explanation in the initial pr, so there was a misunderstanding and lack of information which is now clear I guess.

I don't think https://github.com/Cockatrice/Cockatrice/issues/2697#issuecomment-299803460 is addressed and got sidetracked a bit due to some problems in between the communication here. :)

<br>

@ctrlaltca 
Was this a suggestion to change the "other" message btw?
```
OTHER = "Server doesn't support this feature"
USER_KICKED = "kicked";
USER_LEFT = "user left";
USER_DISCONNECTED = "server is shutting down, no db or spectator";
```

**Comment by ZeldaZach** [comment]
We've agreed this isn't worth more efforts
