### ISSUE TITLE
Creating a token via Context Menu should name Creator

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2705]
When creating a token via right click context menu or card shortcut, the log should reflect the card that is creating the tokens. 

Current:
```
[17:30:35] tritoch plays Lingering Souls from their hand.
[17:30:38] tritoch creates token: Spirit (1/1).
```

Suggested:
```
[17:30:35] tritoch plays Lingering Souls from their hand.
[17:30:38] tritoch creates token with Lingering Souls: Spirit (1/1).
```

**Comment by ZeldaZach** [comment]
While I understand your suggestion, I'm not sure what this adds to the game besides adding _more_ words to the game log, which we're trying to reduce.

I'm not shooting your idea down, just would like to know what the pros/cons are.

**Comment by tritoch** [comment]
Related to #2702 

If you create a token from the graveyard or have multiple cards on the stack or battlefield that can create tokens, it's easier to distinguish which one is doing the actual creation without using arrows or moving the cards.

**Comment by tooomm** [comment]
Regarding translations it also just adds "with %2" basically.

Wording could also be
```
[17:30:38] tritoch creates Spirit (1/1) token with Lingering Souls.
```

**Comment by Daenyth** [comment]
This would require a protocol change and as such I don't think it's worth it

**Comment by Daenyth** [comment]
You can use arrows

**Comment by ZeldaZach** [comment]
I still feel this isn't a worthy change as it will cause more clutter & there is a way to just use arrows and such as Dae suggests...

**Comment by tooomm** [comment]
>this isn't a worthy change as it will cause more clutter & there is a way to just use arrows

It adds useful and basic information on the other hand which is missing completely at the moment. I think arrows are just a bad workaround here just because the log lacks it's basic functionality.
In the case of confusion with your opponent you have to use them to clarify things, but with the suggested change that might be avoided in the first place.
A log should always include comprehensive information.

<br>
This would need a protocol change for sure? @Daenyth
