### ISSUE TITLE
Cockatrice Application Error 

### ISSUE THREAD

**Issue by manoyski** [Cockatrice/Cockatrice#2710]
<b>OS:</b>
"Win 7 ultimate"

<b>Cockatrice version:</b>

Cockatrice_Thopter_Pie_Network_Revision2_win64

__________

I just recently downloaded cockatrice but i am having this problem when i am starting to run the program, it says " cockatrice.exe - Application Error"

"The application was unable to start correctly (0xc000007b). Click OK to close the application. "

I tried to replace dlls and download other versions of cockatrice but still getting the same results. I hope someone can help me so i can play again on cockatrice.

Thank you in advance!

**Comment by tooomm** [comment]
Two things...
Please download the more recent new version. There happen to be another release in between. :)

Check our troubleshooting: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b
The error code is the same. So maybe your windows is 32bit? In this case the 64bit installer (win64) will install, but cockatrice can't run.
The problem is already known, but our installer doesn't check for it yet upon install, I filed an issue already: https://github.com/Cockatrice/Cockatrice/issues/1856

cc: @ctrlaltca

**Comment by Nightfirecat** [comment]
You may want to check this Troubleshooting Wiki item: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b

**Comment by tooomm** [comment]
How did it go? Please report back

**Comment by manoyski** [comment]
Hello first of all sorry it took me so long to reply. But as for the
results, i tried the 32 version and it says mscvp120.dll missing, i fixed
the c++ but still the same result. Then i tried the 64bit version and again
it says the same 0x000007b application error. I hope there are other ways
for me to enjoy again playing cockatrice? Thank you guys in advance.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ctrlaltca** [comment]
> i tried the 32 version and it says mscvp120.dll missing
Install from https://www.microsoft.com/en-us/download/details.aspx?id=40784 (choose vcredist_x86.exe from the download list)

> Then i tried the 64bit version and again it says the same 0x000007b application error
Try vcredist_x64.exe from the above link

**Comment by tooomm** [comment]
Just to be sure... you should go with the 64bit version to avoid future problems!
