### ISSUE TITLE
error opening cockatrice

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2734]
<b>OS:</b>
Windows 8

trails of the gods
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

I installed the trial of the gods version, and it cannot open due to error 0xc000007b   please help.

**Comment by Thunderbeliever** [comment]
3 hours?? more like 3 minutes

**Comment by Thunderbeliever** [comment]
Also for some reason everything I type here is 3 hours behind the time i see on my clock and such.

**Comment by ctrlaltca** [comment]
You computer's clock is probably set on the wrong timezone.

**Comment by Thunderbeliever** [comment]
yeah i am stupid at times. what about the other error?

**Comment by Thunderbeliever** [comment]
and the other?

**Comment by Thunderbeliever** [comment]
sry for deleteing adjusting time

**Comment by Thunderbeliever** [comment]
ok time is fixed.. but what about cockatrice?

**Comment by ctrlaltca** [comment]
try to have a look at the relevant info on the wiki: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b

**Comment by Thunderbeliever** [comment]
ok.. i have looked at this wiki..... I have Ran and reran the following applications

vcredist_x64 and 86
I have found and downloaded Msvcr120, and mscvp120 (btw your link is broken)
I put them Both in system 32 folder and the syswow 64 i have reinstalled and uninstalled cockatrice from 

Cockatrice-2.3.18 beta002-86_64_qt5, trail of the gods 2.3.17-x86_64_qt5, And cockatrice trail of the gods 2.3.17-x86_qt5.

All with no avail

Am i putting the files in the wrong places?? the 0xc000007b Keeps returning or it switches to one of those msvc files missing.

Your wiki does not say where to put them.

**Comment by tooomm** [comment]
If you have a `sysem64` folder you are on 64 bit. So you should also run 64bit Cockatrice.

You are right, the links to the install files here are no longer working:
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found
We will try to find new ones and update the wiki + let you know!
That's the way to go and better than downloading the single files and try to make them work.

Is this the correct/newest one @ctrlaltca? https://www.microsoft.com/en-us/download/details.aspx?id=53840&751be11f-ede8-5a0c-058c-2ee190a24fa6=True

**Comment by Thunderbeliever** [comment]
so the  trail of the gods 2.3.17-x86_64_qt5  Should work... but it returns me to the 0xc000007b error.  I assume that the 64 one because it has 64 in name

**Comment by tooomm** [comment]
I'm not saying it should work. It's just the version you should be using!
(Well normally it does, out of the box)

The error is because you're os is missing some files (normally they are automatically installed with windows updates I think). But in your case you have to manually add a " Microsoft Visual C++ Redistributable" package. We will let you know where to find and download the correct version.
Please be patient and let us find the right version. We will then put the correct links in the wiki as well for everybody! Microsoft changed the location of the files on their website.

**Comment by Thunderbeliever** [comment]
No problem, I am patient. I am glad we found these Dead links.

**Comment by Thunderbeliever** [comment]
Just give the word bros so i can Reopen My Thunderdomes!

**Comment by tooomm** [comment]
Can you try this link and download+install the x64 file in the language of your operating system, please?
https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

(and please try to minimize your replies since you trigger a mail for each of your posts to several people and "spam" them)

**Comment by Thunderbeliever** [comment]
Downloaded, installed... and  We did it :) Awesome, feel free to close i am
about to lose battery power or i would.

**Comment by ZeldaZach** [comment]
Awesome!

**Comment by tooomm** [comment]
Thanks for updating the wiki as well @tritoch!
