### ISSUE TITLE
Cockatrice not updating

### ISSUE THREAD

**Issue by Fuddledidi123** [Cockatrice/Cockatrice#2739]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Version 2.3.17 (2017-05-05)

__________
Each time I update Cockatrice it shows me all the sets that it added, including AmonKhet.  However when you search for AmonKhet cards, the only ones I can find are the special invocations and none of the actual set is available.

**Comment by Daenyth** [comment]
Did you run oracle?

**Comment by tooomm** [comment]
Can you provide a more detailed description what you actually did? (at best with screenshots - just drag them to the text field here!)

**Comment by Fuddledidi123** [comment]
this is what I have done so far: Cockatrice -> Check for updates -> Next, Next, Next, Ok, Next, Save, Ok. I have also done the Check for Client Updates in the Help tab.  The two images are showing that Amonkhet was in the update I ran and that an example of a card from Amonkhet is missing from the card list.
![amonkhet](https://cloud.githubusercontent.com/assets/29001103/26525904/6c069b9a-432b-11e7-994a-a27f5f588289.png)
![searching for nissa steward of elements](https://cloud.githubusercontent.com/assets/29001103/26525905/6fe46080-432b-11e7-92e8-839cb179f78c.png)

**Comment by tooomm** [comment]
You don't need to check for *Client* updates to get the most recent *Card* updates. Two things.
But it's always good to keep the Cockatrice client up to date as well. For AKH for example it was needed to make Aftermath cards work correctly!

You just need to go to `Card Database --> Edit sets` and enable AKH there after running Oracle to fetch the mots recent cards.
Normally, after you run **"Cockatrice --> Check for CARD updates..." (Oracle)** you see a popup with "new sets found - do you want to enable them?" If you hit yes there all is good.

But maybe you updated your database a few weeks ago before the set was released?
Then you maybe added AKH tokens already back then and therefore didn't get the info popup now, because AKH was already in your set list - just with tokens though.

**Comment by Fuddledidi123** [comment]
Hello,
The Edit Sets suggestion worked.  Thanks a lot for your help. It is very much appreciated.
Jarred 

    On Sunday, May 28, 2017 4:24 AM, tooomm <notifications@github.com> wrote:
 

 You don't need to check for Client updates to get the most recent Card updates. Two things.
But it's always good to keep the Cockatrice client up to date as well. For AKH for example it was needed to make Aftermath cards work correctly!You just need to go to Card Database --> Edit sets and enable AKH there after running Oracle to fetch the mots recent cards.
Normally, after you run "Cockatrice --> Check for CARD updates..." (Oracle) you see a popup with "new sets found - do you want to enable them?" If you hit yes there all is good.But maybe you updated your database a few weeks ago before the set was released?
Then you maybe added AKH tokens already back then and therefore didn't get the info popup now, because AKH was already in your set list - just with tokens though.—

**Comment by tooomm** [comment]
You're welcome. Happy Playing! :)
We try to improve that behavior in the future and make it more clear.
