### ISSUE TITLE
Pos1/End not working in card list

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2801]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
Version 2.3.18-custom_83f287b (2017-06-18)

__________

<kbd>Pos1</kbd> and <kbd>End</kbd> doesn't jump to the start or end of the card list in deck editor.
This is most likely due the input focus is set to the search bar once you click the card list.
Would be helpful to use that once you click a card.

Should be the same on mac if there exists such a key.

**Comment by Psithief** [comment]
Is <kbd>Pos1</kbd> your equivalent of the <kbd>Home</kbd> key?

(I had to look up the `<kbd>` tag, haha.)

I thought this would be the expected behaviour. That is, I expect a user would want to go to the beginning or end of what's typed in the search box almost always (to help with editing, or deleting the text). I, for one, don't particularly want to make the effort to click that squat search box if I don't have to.

However, I think it's more important that the <kbd>PgUp</kbd> and <kbd>PgDn</kbd> keys don't work. They have no purpose in a text box and should be forwarded to the list.
As with other office applications, a modifier key (platform appropriate?) with <kbd>PgUp</kbd> and <kbd>PgDn</kbd> could substitute for <kbd>Home</kbd> and <kbd>End</kbd> for going to the top of bottom of the card list.

**Comment by ebbit1q** [comment]
merging into https://github.com/Cockatrice/Cockatrice/issues/3945 see that ticket for progress
