### ISSUE TITLE
Card Art Selection like how it's done with tokens

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2827]
Give cards with multiple art variations different names by adding spaces on the end like how it's already done with tokens so players can have the option of whichever they prefer.

(Idea from Grim that they'll never actually make a issue out.)

**Comment by skwerlman** [comment]
The spaces thing is a hack to work around problems in how the card database stores cards.

The changes in #2545 would allow for multiple cards with the same name to have different arts, since they'd still have unique hashes. Combined with #486, this would allow multiple arts without necessarily needing to duplicate cards in the XML. Additionally, it avoids the problems that'd be caused by suddenly having multiples of every card appear in the deck editor.

**Comment by Daenyth** [comment]
I don't think we're going to take this approach - I don't want to contribute more to the space hack than we already use. We should just fix things properly so people can select custom art entirely
