### ISSUE TITLE
Tokens again

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2842]
OS:
windows 8*

Cockatrice version:
2.3.18-beta004

  Same as the last issue, the Cat dragon token is still messed up.

**Comment by tooomm** [comment]
Can you please link the old issue or describe your problem with the cat dragon token more in detail?

**Comment by Thunderbeliever** [comment]
The Cat Dragon Token from 2017 is not linked correctly. When you play the Creature that makes them, and you make the token linked to him you get a Cat Soldier instead of the Cat dragon

**Comment by tooomm** [comment]
You must be wrong.

The token file has correct links:
https://github.com/Cockatrice/Magic-Token/blob/a8320d6dda4c39a09601a32127069509cd782f13/tokens.xml#L667-L680

Somebody reported the problem with that token in the correct token repo and it got fixed a few days ago: https://github.com/Cockatrice/Magic-Token/issues/41

You need to use the newest token file obviously (Cockatrice --> Check for card updates...).
And for sure you have to clear the old and wrong pictures from your picture folder. (You find the path to your picture folder in the Cockatrice settings on the first page)

I hope you get it working - let us know.

<br>

Closing since
1) wrong repo
2) error in token file is fixed already

**Comment by tooomm** [comment]
Did it work out?

**Comment by Thunderbeliever** [comment]
yeah.
