### ISSUE TITLE
Banning procedure

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2895]
I would like a better understanding of banning procedure because it look very 1 sided. people are allowed to be Cancer and do whatever they like and you only Ban people who try to solve issues in the communtity. Also the Banning time frames Make Zero sense.  You tell people to help but you provide them No way to help police each other, since your mods Only Ban people who do good.

**Comment by Daenyth** [comment]
Please talk to the admin staff of whatever server you're having an issue with. This site is for issues with the software itself and the dev team does not run any servers

**Comment by Thunderbeliever** [comment]
yep the normal run around, no one gives a hoot. understood.

**Comment by Daenyth** [comment]
I don't run a server. Contact the person who runs the server you care about. This site is where we develop the software. I am literally unable to help you with banning procedures because they are server specific and are set by the person running the server. Since that person is not me, that's the person you should contact.

I'm sorry I wasn't clear enough the first time.

**Comment by ctrlaltca** [comment]
@Daenyth's current patience level: shaolin monk
