### ISSUE TITLE
Use card back for custom tokens by default, instead of a colored rectangle

### ISSUE THREAD

**Issue by reem** [Cockatrice/Cockatrice#2940]
In the previous version of trice, unknown tokens used the card back for their image. This looked much nicer than the new version which uses just colored rectangles.

Also want to say I am generally really enjoying the new version! Great job!

**Comment by Daenyth** [comment]
I'm pretty sure the colorized tokens were the original and the card back
was the bug actually. This is intentional. In any case if you run oracle on
a recent version, you should have tokens art for most tokens in the game

**Comment by tooomm** [comment]
Yes, the bug got reported in https://github.com/Cockatrice/Cockatrice/issues/2600 and fixed in https://github.com/Cockatrice/Cockatrice/pull/2638.
The colors are used to show the actual color of custom or unavailable token. 

*If you really prefer a card back icon you could pull a unrelated card from your sideboard and flip it face down and add an annotation. That's very weird though I have to say.. :)*

We could consider adding an option to display the card back as background picture for custom tokens, too.
But that really doesn't fit the create token interface right now and would need more tweaks.
Simply adding it to the `Color` dropdown would be bad.

**Comment by reem** [comment]
I guess that's reasonable, I just really dislike having these odd color rectangles instead of the nice card back image.

**Comment by Daenyth** [comment]
If someone wanted to add a configuration setting to visually use card back image instead of colors for tokens, I think that would be worth accepting
