### ISSUE TITLE
The citys blessing

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#3002]
Can we have all the Treasure maker and Ascend cards in Rix fixed please? they should have links to the treasure token or to the blessing token

**Comment by tooomm** [comment]
1) This is a token issue -->https://github.com/Cockatrice/Magic-Token

2) Updates like that **always** happen after gatherer updates as stated [here](https://github.com/Cockatrice/Magic-Token/wiki/Token-updating-process-flow)
This has always been like that and is unlikely to change.

Thanks for the report, but you have to wait one more week. :)
We are generally aware of the token linking, because we have scripts for it, it just takes a while (and there are schedules).

**Comment by Thunderbeliever** [comment]
yet the flips cards work

**Comment by tooomm** [comment]
Flip cards are no tokens.., unlike "The city's blessing" and Ascend as an ability related to that token.
Also, "Treasure" is a token...
