### ISSUE TITLE
On deck load "name" and "comments" have wrong information

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3064]
<b>Info:</b>
Client Version: 2.5.0-custom(7fbff92) (2018-01-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.3

__________

As spotted in a recent PR: https://github.com/Cockatrice/Cockatrice/pull/3057#pullrequestreview-92894335

- The text for both is all lower case
- There is another bug when you copy any deck to the clipboard from the client menu, and import the deck back from there, suddenly the comment field contains information like `4 maindeck` which are our own annotations we create

Example:
![comments issue](https://user-images.githubusercontent.com/9874850/35687702-b0b45918-076f-11e8-9678-281f98d65230.png)

**Comment by ebbit1q** [comment]
Decided to pick this up by rewriting loadFromStream_Plain. I noticed a `|` will always remove everything behind it mentioning "post card name editions" this removes the last part of split cards when written like Fire | Ice". Is there a particular reason for this or would parsing the split card correctly be preferable?

**Comment by ctrlaltca** [comment]
If i recall it correctly, some other software (maybe magic workstation?) used to add a pipe character and the card edition name after the card name:
`4 card_name | edition name`
Since cockatrice makes no difference between cards with the same name from different sets, the information was just discarded.
