### ISSUE TITLE
[Feature request] Add age filter for games (if we can't deal with outdated games)

### ISSUE THREAD

**Issue by MopDa** [Cockatrice/Cockatrice#3067]
Everyone knows there are outdated games hanging on the server all day long. Seems like we can't deal with them (probably cuz its hard to say if game is outdated or just takes way too long, or maybe its just tenth game in the same lobby), maybe we can at least add an option to filter them out on the age basis?

**Comment by skwerlman** [comment]
its possible to sort the games list by age already, so i don't know if this is needed

**Comment by tooomm** [comment]
Sorting is helping, but I totally understand that one would completely hide games that are 2-3+ hours old for example. Also requested as part of https://github.com/Cockatrice/Cockatrice/issues/2431.
Filtering such games out might not be a real solution to the problem, but helps somehow.

There has been an attempt with some discussion about auto-closing inactive game rooms in a PR, it got never finished though: https://github.com/Cockatrice/Cockatrice/pull/806

Somehow this is addressed with the idle timeout feature from https://github.com/Cockatrice/Cockatrice/pull/2209, https://github.com/Cockatrice/Cockatrice/pull/2259 and https://github.com/Cockatrice/Cockatrice/pull/2456. Because it disconnects inactive players and the room should get destroyed once there are no players inside. But this could be disabled by the server owner and it's no guarantee that a active player keeps an old game room open while joining a second game.

Could we use the same timer the server is tracking already and use it to auto close rooms where all players don't do game actions or chat? In #806 there have been some discussions about how big such a time frame needs to be to cover several cases. Like 90-120min to start with maybe?
What is your idle timeout set to on the woogerworks server? @woogerboy21 

The idle timeout is tracking all activity? Not on a room basis?

**Comment by Daenyth** [comment]
I'd want to make a better filter UI before we add this. A common user error is that they can't see any games in the list, and it's because they added a filter and forgot

**Comment by tooomm** [comment]
There could be a simple little hint text **only showing** when filters are active:
![filter hint](https://user-images.githubusercontent.com/9874850/35741295-bed30cc4-0837-11e8-9fc0-10680937615d.png)

I totally see people adding filters to find a suitable game, then close trice and come back a week later to wonder why there are just a few games shown. (Cockatrice remembers used filters, which is a nice feature!)

**Comment by Daenyth** [comment]
That would be a good first step

**Comment by knitknit** [comment]
I'm happy to take on this one now that #3068 is closed.

@ZeldaZach you mentioned in https://github.com/Cockatrice/Cockatrice/issues/3068#issuecomment-362671432 that you wanted to clean up filters a bit - feel free to let me know if there was anything specific you were thinking of? I can look at implementing that along the way.

**Comment by ZeldaZach** [comment]
Honestly, it's been so long I no longer remember. I think this ticket has enough information to go on as-is :)
