### ISSUE TITLE
Duplicated cards in database

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#3129]
<b>OS:</b>
Win10

<b>Cockatrice version:</b>
f265dfa

__________

Clicking Manual Update (and possibly letting the updater run on schedule?) duplicates cards in the database.

Steps to recreate:
1. Run f265dfa or newer on Windows
2. Enable spoilers
3. Run manual update

You now have 2 or more copies of every card in your database.

**Comment by ZeldaZach** [comment]
I've noticed this... The reload is a bit weird and I need to look into it at some point

**Comment by tooomm** [comment]
Database reloading is fishy indeed... I can confirm the issue.

But not only on spoiler update, also on every normal Oracle update!
![db doubling](https://user-images.githubusercontent.com/9874850/37485125-e3e26f00-288a-11e8-8d5c-77dccf192525.png)

I also run into a problem that changing sets in `Manage sets...` didn't update the db unless I restarted the app (in the screen I swiched from "enable all" to only "RIX" and "XLN"):
![set change - no db refresh](https://user-images.githubusercontent.com/9874850/37485129-e5cde182-288a-11e8-9b19-a15203bb56db.png)

**Comment by ctrlaltca** [comment]
The problem is cased by #3053.
Since cards currently loaded in memory are not forcibly deleted anymore, the deck editor will still show both the old copy of those cards and the new loaded copy of the card. If you try opening a new deck editor, you should see only a single copy of those cards.
In order to fix this, when the card database gets reloaded, we need to inform all the `CardDatabaseModel` instances that they need to completely reload their data.
Something similar is already in place when enabled sets change (`cardDatabaseEnabledSetsChanged`), but as noticed by @tooomm that functionality is affected, too.

**Comment by ZeldaZach** [comment]
@Vafthrudnir Wanna look into this?

**Comment by tooomm** [comment]
This also happens (and is especially annoying) if automatic spoiler season is enabled and new cards are added because you can't avoid it and basically have to restart again right after opening cockatrice to fix it:

![untitled3](https://user-images.githubusercontent.com/9874850/40646189-c6a6d2ae-6328-11e8-9f33-c41704ec4ca3.png)
(screenshot from v2.5.1)
