### ISSUE TITLE
Fix UI for 4 player games

### ISSUE THREAD

**Issue by bcTLMO** [Cockatrice/Cockatrice#3158]
<b>System Information:</b>
   

_________________________________________________________________________________

   
The 4 player UI is too cramped. A suggestion would be to just do 4 squares instead of 4 lines top down. 

![untitled1](https://user-images.githubusercontent.com/37950044/38160502-47274ec4-348d-11e8-8da3-4cb57e8c9ae8.png)

**Comment by ctrlaltca** [comment]
Settings -> appearance -> Table grid layout -> minimum player count for multi-column layout
Lower that number to 2
![schermata 2018-03-31 alle 10 53 45](https://user-images.githubusercontent.com/1631111/38161583-ece79a50-34d1-11e8-82ec-9b63cc728721.png)

Ta-da!
![schermata 2018-03-31 alle 10 54 24](https://user-images.githubusercontent.com/1631111/38161587-08aeeebe-34d2-11e8-8e94-ce32cee941f9.png)

**Comment by Insertcleverphrasehere** [comment]
The issue is that the default for multi-column layout should be at most 4. At the moment the default is 5, so we end up with new players starting on a very space inefficient boardstate with tiny icons. And anyone who knows about the multicolumn layout doesn't get much advantage out of it because if they are playing with other players that don't use it they have to constantly ask them to move stuff to the left. 

The fix is to change the default to 4 instead of 5. (I actually use 3 as mine, but the benefit from 3 to 4 isn't as extreme)
