### ISSUE TITLE
Can't close banners

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3193]
Client Version: 2.5.1-beta.3 (2018-04-09)
Client Operating System: OS X 10.13
Build Architecture: 64-bit
Qt Version: 5.5.1
________________________________________________________________________________________
Was mousing over the banner (alert w/e) and it gives no option to close it. So when they pop up I just have to wait for them to go away.

![screen shot 2018-04-11 at 3 14 24 am](https://user-images.githubusercontent.com/6514656/38601866-06e49210-3d37-11e8-9f8e-7e1a71b1fdb2.jpg)

**Comment by Daenyth** [comment]
This is entirely reliant on how your OS does banners, I think. Slack does the same thing for me on OSX

**Comment by ZeldaZach** [comment]
You can drag it to the right do "dismiss" it. Althought I would like it to have the option to close directly on the banner... Hmm....

**Comment by ZeldaZach** [comment]
Figured it out. User has to define as alerts instead of banners.

<img width="402" alt="screenshot 2018-04-11 16 02 46" src="https://user-images.githubusercontent.com/7460172/38640260-cfd22a9c-3da1-11e8-8db8-599a897589c2.png">

<img width="371" alt="screenshot 2018-04-11 16 03 27" src="https://user-images.githubusercontent.com/7460172/38640311-ebab339e-3da1-11e8-9a56-6ed578235d72.png">
