### ISSUE TITLE
Update failure during Microsoft Visual C++ installation + glitch

### ISSUE THREAD

**Issue by HMgruul** [Cockatrice/Cockatrice#3202]
Hi,
I'm on Windows 7 sp1 64bits.

I attempted to update Cockatrice today and the same issue as here : [](https://github.com/Cockatrice/Cockatrice/issues/3125) happened to me. I hit "cancel" and "X" in the windows, nothing happened at first but after 5 to 15 minutes (I lost count !), the windows eventually closed and Cockatrice launched itself.

I went to  Settings > Deck Editor and updated with Dominaria. It appeared that - besides the Dominaria set -, every other set featured 4 iterations of each card in the "Search by card name" column. All 4 had the same name and art. I did shut down Cockatrice, updated Notepad++, and restarted Cockatrice. The glitch disappeared.

No problem currently, I wanted to highlight issue #3125 can happen again, kind of solves itself despite a minor glitch. ;)

**Comment by tooomm** [comment]
>I attempted to update Cockatrice today and the same issue as here : happened to me. I hit "cancel" and "X" in the windows, nothing happened at first but after 5 to 15 minutes (I lost count !), the windows eventually closed and Cockatrice launched itself.

You should not cancel the visual c++ installation at all.
And please tell us which version you try to install...

>No problem currently, I wanted to highlight issue #3125 can happen again, kind of solves itself despite a minor glitch. ;)

How did it solve itself?
Did you try our [latest release (2.5.1)](https://github.com/Cockatrice/Cockatrice/releases/tag/2018-04-16-Release-2.5.1)? It's the first version with the fix for #3125...

<br>

>I went to Settings > Deck Editor and updated with Dominaria. It appeared that - besides the Dominaria set -, every other set featured 4 iterations of each card in the "Search by card name" column. All 4 had the same name and art. I did shut down Cockatrice, updated Notepad++, and restarted Cockatrice. The glitch disappeared.

That is a known issue: https://github.com/Cockatrice/Cockatrice/issues/3129

**Comment by HMgruul** [comment]
I posted my issue the same day I attempted to update Cockatrice, so the version I attempted to install was the latest one available at that time via the "Help" option. My previous update was back when RIX was available. I had not updated in the meantime (I missed Masters 25 and DD Elves vs Inventors).
I updated once again a few days ago when I received a mail telling me a new version was available (16-04-2018 version). 

The update was done despite me canceling the CC installation. I believe the 3 following times I opened Cockatrice, I had 3 then 2 lines of the same cards displayed in the search column. It fixed itself before the last update I did, I don't know how (maybe CCleaner that I usually run cleaned the mess, otherwise I don't see what could've helped).

That's all I got for you. :grin:

**Comment by tooomm** [comment]
There might be a confusion with updating the Cockatrice client software itself, and the card database it uses to display game content.

Updating the software: `Help --> Check for Client Updates`
Updating the card database: `Cockatrice/Actions --> Check for card updates`

The first can also be done with downloading+installing a new app version from cockatrice.github.io webpage.
The second can also be done with running the `Oracle` tool.

Since the "glitch" with duplicated card entries is a separate known issue, and with the 2.5.1 version we updated how virtual c++ is installed I'm going to close this.
If you still have problems with installing the newest 2.5.1 version from our webpage feel free to reopen this issue, please!
