### ISSUE TITLE
0 matches values other than 0 in filters

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3212]
<b>System Information:</b>
   

   

Client Version: 2.5.1 (2018-04-16)
OS: Windows 10 64-bit

________________________________________________________________________________________

   

   

The filter `Power AND 0` matches cards with a power of 0, as well as cards with odd powers like `*`, `2+*`, `*²`, `½`, `3½`, `?`, or `∞`.

This also applies to toughness filters.

IMO `Power AND 0` should match exactly, like other filters. If the current functionality is desired, it should be a separate filter, like `Effective Power` or something

**Comment by Vafthrudnir** [comment]
I believe this is a bug:
https://github.com/Cockatrice/Cockatrice/blob/f5eb05b6824dbeb58fcf5b8628f47f111707634d/cockatrice/src/filtertree.cpp#L356
If the `toInt` conversion fails due to odd values like you listed, it returns `0` and that's why it matches the filter criteria. The algorithm should check whether the conversion failed or not, and only return true if it succeeded.
