### ISSUE TITLE
updater: reinstall option throws error

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3293]
<b>System Information:</b>
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE
__________________________________________________________________________________________

![reinstall update](https://user-images.githubusercontent.com/9874850/41532603-fa441b92-72f7-11e8-89f0-7bb6f813efb3.png)
It doesn't matter if I select `Stable` or `Beta` channel in settings.

With `2.5.1` it works fine!

**Comment by ctrlaltca** [comment]
The bug seems introduced by #2468, to be more precise by this line: https://github.com/Cockatrice/Cockatrice/pull/2468/files#diff-68c33782ee685fda6ebc3cc66405a16aR111
If you are already running the last version, `updateUrl` is not populated, so pressing the "reinstall" button starts the download of an empty url.
I'm not sure how it could work with 2.5.1.

**Comment by tooomm** [comment]
>I'm not sure how it could work with 2.5.1.

I tried it when 2.6.0 was out already, that's why probably. ;)
