### ISSUE TITLE
Token <reverse-related> Overlap

### ISSUE THREAD

**Issue by dylanhamada** [Cockatrice/Cockatrice#3362]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  

  

If a custom set XML includes cards that create ordinary tokens (eg. red 1/1 Goblin), creating a new <card> tag for that token, using its name (eg. <name>Goblin</name>) and including the <reverse-related> tag linking to the custom card will not allow you to right-click and "Create X token". However, if the token name is modified (eg. <name>Goblin-a</name>), the custom card will have the "Create X token" option available.

**Comment by ctrlaltca** [comment]
Wow, this ticket got overlooked for a long time, sorry for that.
I've tried following the steps you described, but it works fine now. 
Since you are defining a relation from a card to a token you should use the `<related>` tag; the `<reverse-related>` tag is instead used for the opposite, token -> card relations.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="4">
    <cards>
        <card>
            <name>Dark Kitten</name>
            <text>Meow</text>
            <prop>
                <type>Creature — Kitten</type>
                <maintype>Creature</maintype>
                <colors>G</colors>
            </prop>
            <set rarity="mythic" muid="123456" num="1" uuid="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa">M19</set>
            <related attach="attach">Goblin</related>
            <tablerow>2</tablerow>
        </card>
    </cards>
</cockatrice_carddatabase>
```

Feel free to reopen if it stills doesn't work for you.
