### ISSUE TITLE
Installing Stuck

### ISSUE THREAD

**Issue by matth1992** [Cockatrice/Cockatrice#3368]
<b>System Information:</b>
  

   Help please! I tried many times to install cockatrice, but it gets stuck like this and won't progress any further... What can I do? 
__________________________________________________________________________________________

    Help please! I try to install Cockatrice but everytime it gets stuck like in the image and won't progress any further

**Comment by matth1992** [comment]
And it seems i can't post the screen on here neither :/ basically, the installing "line"  is about to end and won't fill completely

**Comment by tooomm** [comment]
Please provide us the information we ask you for. We can't help you otherwise...
>If you can't install Cockatrice to access that information, make
       sure to include your OS and the app version from the setup file here

Where do you downloaded the installer from?
What's the name of the installer?
Which operating system are you running?
Is your operating system 32bit or 64bit?
...

<br>

>And it seems i can't post the screen on here neither

If drag&drop the screenshot to the text field doesn't work for you use any image file hoster (search in google) and link the url here

**Comment by ctrlaltca** [comment]
1) please provide the required information in the ticket:
> If you can't install Cockatrice to access that information, make sure to include your OS and the app version from the setup file here

2) If you see a progress bar, you also probably see a "details" button near it that should open a textbox with some more information (like the step it's currently stuck into)

**Comment by ctrlaltca** [comment]
@tooomm you beat me by 12 seconds ;)
