### ISSUE TITLE
Suggestion: add "reset P/T to base values" as an option in power/toughness context menu

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#3402]
Suggestion: under the right-click context menu for power / toughness, add the option "reset to base values". This is one of the more commonly used actions through that menu. 

2. It could also be useful to have a hotkey for this action.

3. "Set power and toughness" (hotkey ctrl-P) could pre-populate to the base values, rather than the current values.

**Comment by ebbit1q** [comment]
Seems like a good first issue, I'll try this :)

**Comment by tooomm** [comment]
Cool. Join our Gitter chat in case you've any questions! @ebbit1q

**Comment by ebbit1q** [comment]
This issue has been resolved and can be closed.
#3412 added the ctrl+alt+0 hotkey and menu options for resetting p/t.

**Comment by tooomm** [comment]
You are right, thanks for your hint (and the PR in the first place 😄)! @ebbit1q 
Just had a chance to test the change in the app, I like it. 👍 

Regarding the open issue, that slipped our attention because we are used to closing issues right from within the PR with keywords:
https://help.github.com/articles/closing-issues-using-keywords/

We have that also covered in our PR template.
