### ISSUE TITLE
Overgrown Tomb and Temple Garden missing cipt

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3410]
Ran oracle again to get a new xml today. Overgrown Tomb and Temple Garden are missing the 1 line in the xml file.

**Comment by alexandremj** [comment]
Could you please elaborate? Where did you get the XML from? So far it doesn't really seem like an issue with Cockatrice

**Comment by skwerlman** [comment]
can confirm; just ran oracle built from master, and no cipt for either. currently, oracle only applies cipt in the following circumstances:

- the card has hideaway
- the card has the text "[card name] enters the battlefield tapped" but does not have the text "[card name] enters the battlefield tapped unless"

because the text on Overgrown Tomb and Temple Garden have `it` in place of the actual card name in the oracle text, the check fails. The other lands in this cycle have the actual card name, and so the check works. 

because of the inconsistency, this seems like both a bug in MTGJSON and in oracle, since all the lands in the cycle on gatherer have `it` instead of the card name.

a quick search of the phrase "it enters the battlefield tapped" on gatherer returns only lands, so there should be no issues just accepting that term as cipt

the relevant lines in oracle:
https://github.com/Cockatrice/Cockatrice/blob/bc2cb59c506f30aa0d878a0ad1b538c0507b800a/oracle/src/oracleimporter.cpp#L107-L109

**Comment by skwerlman** [comment]
if i understand correctly, the issue isn't about 'unless' lands; its about shock lands. all the shock lands have cipt _except for_ Overgrown Tomb and Temple Garden, which should have it.

**Comment by alexandremj** [comment]
Seems like an easy fix. However I'm not sure if we should change `cipt` conditions in the code, fixing oracle and sending a ticket to the MTGJSON community seems like the way to go. As far as consensus is concerned, I don't know the community standard but padronizing this sounds right.

**Comment by ctrlaltca** [comment]
There are a two corner cases here:
- Blooming Marsh, Botanical Sanctum, ..: If one of these lands is your first, second, or third land, it enters the battlefield untapped. If you control three or more other lands, however, it enters the battlefield tapped.
 - Vampire Envoy: Vampire Envoy’s last ability will trigger if it becomes tapped for any reason, including attacking. However, if it enters the battlefield tapped for some reason, the ability won’t trigger.

So maybe checking for the complete string "If you don't, it enters the battlefield tapped." is a proper fix?
