### ISSUE TITLE
Shortcuts loosing focus

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3482]
Cockatrice 2.6.2

Shortcuts seem to lose focus when certain actions take place (Rolling dice I believe is one of them).

Came about with the update to 2.6.2. Investigation is needed

**Comment by ebbit1q** [comment]
How do I replicate this?

**Comment by ZeldaZach** [comment]
Start single player game. Try shuffling library (CTRL+S). Try rolling dice (CTRL+I). Try any other shortcut now.

The first two actions work, the shortcut afterwards fails until you either change tabs in-client, or change programs (i.e. i clicked firefox, then back to cockatrice and shortcuts worked again)

**Comment by ebbit1q** [comment]
Works just fine on Ubuntu 18.04

**Comment by ZeldaZach** [comment]
Can you test on Mac? macOS 10.14.2

**Comment by ebbit1q** [comment]
I can't

**Comment by ZeldaZach** [comment]
I think it's also an issues on Windows 10

**Comment by ebbit1q** [comment]
no issues on windows 10, I think it's just mac

**Comment by tooomm** [comment]
Works for me on Windows 10 with v2.6.2 as well.

**Comment by ZeldaZach** [comment]
User skinevo on Rooster Ranges is using macOS 10.12.6 and has reproduced this issue.

This seems to be affecting macOS across several builds, so it has to be something we've done or that QT did.

cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
Looks like https://github.com/Cockatrice/Cockatrice/issues/2647 is hitting us again.
The last release 2.6.2 bundles Qt 5.9.3, that is known broken (build log: https://travis-ci.org/Cockatrice/Cockatrice/jobs/470768703#L231), while the previous 2.6.1 bundles Qt 5.11.1 (build log: https://travis-ci.org/Cockatrice/Cockatrice/jobs/405156718#L6517).
I've tested the current master with Qt 5.11, and shortcuts works as expected.
I guess during the "cmake changes" in order to speed up compilation time the homebrew update step got removed, so Travis is building with an old, known broken qt version.

**Comment by ZeldaZach** [comment]
Glad this was figured out.

We're gonna have to update homebrew in the process for building then?

**Comment by ctrlaltca** [comment]
So, the Travis build image is quite old and, when updated, homebrew needs to perform a long step of migrating its formulas that takes a few minutes. I'm investigating the possible solutions.

**Comment by Daenyth** [comment]
I wonder if we can disable the self-Update and just install the new qt
specifically
