### ISSUE TITLE
Rethink how cart art priority and set management is done

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3485]
- Adjust card art order to download and display your preferred printings 
- Enable and disable sets of your choice to have only needed ones in your deck editor

These two different features being combined in one dialog leads to numerous usability problems and people struggle with understanding and using it.

See https://github.com/Cockatrice/Cockatrice/pull/3463#issuecomment-443548426 and following comments for first ideas.

**Comment by ZeldaZach** [comment]
I'm working on some stuff that'll probably expand out

1) Change download URLs (again...) to use scryfall IDs
2) Make it a list of download targets instead of the two (back end already in place, just gotta make front end better)
3) Better set management so you can better choose how sets are downloaded and the ordering of them

**Comment by ZeldaZach** [comment]
This was solved at some point

**Comment by tooomm** [comment]
Managing availability of cards/sets in the deck editor, and adjusting the download priority of card art - two different features - are still merged together and both are handled within the very same list. Nothing changed there and it’s still complex. 

This issue proposed to separate them.
