### ISSUE TITLE
Rewrite message log to not use events to guarantee order

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3553]
As realized first in https://github.com/Cockatrice/Cockatrice/pull/3549 and discussed in gitter... 

>Rob Blanckaert @basicer
The problem is all the logs in cockatrice are in random order if they happen in the same event.

>Rob Blanckaert @basicer 20:51 :point_up: [February 4, 2019 8:51 PM](https://gitter.im/Cockatrice/Cockatrice?at=5c5897ab8aa5ca5abf845867)
i mean a log is something that needs to be in an order
and with events you can never garnetee the order
>
>Zach H @ZeldaZach 20:51
That’s really dumb
We need that addressed in the future

**Comment by ctrlaltca** [comment]
> The problem is all the logs in cockatrice are in random order if they happen in the same event.

Actually, this is not true. Since the `Player` and `MessageLogWidget` live in the same thread, the signal/slot connection will default to `Qt::DirectConnection`, so the the slot is invoked immediately when the signal is emitted.
The problem seen in #3549 is caused by the fact that `MessageLogWidget` has a special handling for some events, especially for card moves, as seen in https://github.com/Cockatrice/Cockatrice/blob/9411396b971e32d855abca41dbf20918651c7d80/cockatrice/src/messagelogwidget.cpp#L446
Card moves are not logged immediately, but are queued and processed only after all the other events have been handled: https://github.com/Cockatrice/Cockatrice/blob/9411396b971e32d855abca41dbf20918651c7d80/cockatrice/src/messagelogwidget.cpp#L129
Why? Looking at the code it seems that when a card is moved the handling for some other events is skipped:
- logging of card properties change (P/T, tap, )
- card tap animations

The same special handling is used to avoid "draw card" and "deck shuffle" logs when a player takes his initial hand or a mulligan.
