### ISSUE TITLE
Judge Mode Suggestions

### ISSUE THREAD

**Issue by HyperionHK** [Cockatrice/Cockatrice#3619]
Having taken an initial look at Judge mode, I have some suggestions to consider.
1) Allow judges to enter games where spectators are not enabled
2) Allow judges to see hands even if spectators aren't allowed to see hands.

I think this would help make it a more useful feature, especially the first item

**Comment by ZeldaZach** [comment]
Additional: Add support for drawing arrows (of all colors too)

**Comment by ZeldaZach** [comment]
cc: @basicer

**Comment by skwerlman** [comment]
> Allow judges to enter games where spectators are not enabled

I'm not a huge fan of this. Having a judge join a game when spectators are disabled would be unexpected for many users. Rather, i'd like to see a separate "allow judges" option added to the create games dialog.

**Comment by FjordLac** [comment]
Hi there, 

As suggested by one of your devs, here are some suggestions : 
I'm judging in several competitions that mainly use cockatrice and thus Zach gave me the judge mode.
 
Being allowed to write to both player on the chat or to see their history would allow a very late intervention in the night without having to currently being in a vocal chat with players, or even to make rulings understandable since English is not my mother language and i might not be very clear when speaking. That would also allow anyone that would intervene later using the replay to see that a judge has stepped in and gave someone a penalty if any or even to show that a fix was made as remedy to a wobby situation. 

Being able to make arrows would help to show why something is interacting with something else, and in a different color would make things clear that it's the judge that is intervening.

**Comment by ZeldaZach** [comment]
After talking with the team, we agreed that the only issue here is Judges can't draw arrows. If users lock down their games, they explicitly state they don't want interventions. Judges can view hands by right clicking on a user, whether or not the view hands option is enable for spectators. Linking to the Arrow ticket #4113
