### ISSUE TITLE
Dev Team Pre-Screening Sets

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3623]
The past has been forgiving to the image loader. Now that we use better data sources, foreign cards sometimes slip through as they're the "highest" up on the list. 

I'm proposing Oracle disables some sets by default that are not in the english language. Some examples include `Salvat 2005`, `Salvat 2011`, `Renaissance`, and `Foreign Black Border`.

We can mark these as exceptions and tell the user we are disabling them by default, but you can re-enable if you'd like.

**Comment by tooomm** [comment]
What do you think about an option in Oracle to only add sets of certain types to the card database.
People mostly only use/need e.g. core, expansion and master probably. Maybe some others.
But definitely not all the promo and special stuff which is causing most user issues lately since mtgjson contains more data now.

Which `set_type`'s are currently included in mtgjson?
