### ISSUE TITLE
Deck Editor search bar doesn't match comma or hyphen

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#3700]
Type in "Ajani, Valiant Protector" in Deck Editor search bar.  Nothing comes up.  Remove the comma.  The card is found.

Try "O-Kagachi, Vengeful Kami".  You have to remove the comma and the hyphen.

Other punctuation with problems;  "  !  (  )  

Other punctuation that seems fine:  '  /

**Comment by tooomm** [comment]
@MotherofRuins for me, your examples `Ajani, Valiant Protector` and `O-Kagachi, Vengeful Kami` are found when I type them exactly like that.
Can you try rerunning Oracle and get the newest card database?
Also, which client are you running...

**Comment by Moonlight-Cockatrice** [comment]
@tooomm this issue was fixed along with many other deck editor features, but an official updated client version with any of the fixes from the last couple of months has never been released. You're probably not having the issue because you're using a client version not released to the rest of the Cockatrice userbase.

**Comment by tooomm** [comment]
Which version are you using then? (@Moonlight-Cockatrice & @MotherofRuins)
You can try using the beta, probably the fixes are included there!

Let us know if that worked!

**Comment by Moonlight-Cockatrice** [comment]
2.7.0 (March 4th) is the newest non-beta client version available.

**Comment by Moonlight-Cockatrice** [comment]
Considering some of the other solved issues can be rather annoying such as Tribal cards being listed in the deck builder as being Tribal cards rather than their main card type, and mac users apparently have their own host of issues, I think it might do well to look into pushing the beta version into full release sometime soon?

**Comment by tooomm** [comment]
@ZeldaZach what do you think about releasing 2.7.1?
It doesn't look like there are features pending, and the beta deals with some issues.

**Comment by tooomm** [comment]
As I understand it this is fixed already and just waits for a new release.
Please reopen if the problem persists with the 2.7.1-beta!
