### ISSUE TITLE
Network error: SOCKS version 5 protocol error

### ISSUE THREAD

**Issue by FinksJuice** [Cockatrice/Cockatrice#3744]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: macOS Mojave (10.14)
Build Architecture: 64-bit
Qt Version: 5.12.1
System Locale: en_DE
Install Mode: Standard

  
_______________________________________________________________________________________

Hello, I'm struggling to connect online, it says: "Network error: SOCKS version 5 protocol error." Also the same message pops up when I'm trying to run Oracle. I run it on Mac and I desinstalled it whith AppCleaner and reinstall it but now the problem persists.

**Comment by ZeldaZach** [comment]
Tag @basicer

**Comment by ctrlaltca** [comment]
Cockatrice is trying to connect to the server using a proxy.
Since Cockatrice doesn't have any kind of proxy support/configuration in place, i suppose that Qt (the basic library used by Cockatrice for a lot of things, including networking) is picking up the proxy configuration from somewhere, maybe the system's global settings.
So, first question, do you actually need a proxy to access the internet?
Second question: did you configure your mac to use a proxy?
I'd start following these instructions https://support.apple.com/en-us/guide/mac-help/mchlp2591/mac and see if you have any proxy configured.

**Comment by FinksJuice** [comment]
Thank you so much, it helped me so now it is working again :)
I wasn't aware the field was checked and even what it means but now I can enjoy playing again 👍

**Comment by tooomm** [comment]
Happy to hear the positive feedback. Enjoy! :)
