### ISSUE TITLE
improve move to bottom of library from hand (new mulligan rule)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3749]
Announcing article: https://magic.wizards.com/en/articles/archive/news/london-mulligan-2019-06-03

With `CoreSet 2020` there will be the new `London Mulligan Rule`.
It requires people to put single cards (or more) from their hand to the bottom of the library.

Currently, users can right click a card in their hand (or select several), and chose
`Move to --> Bottom of library in random order`
While that works and accommodates the new mulligan rule, the title of that option is really weird and quite confusing. "Single card in random order"?
But also when you select several cards at once it's difficult to understand how the random part works and if it gets performed correctly due to https://github.com/Cockatrice/Cockatrice/issues/3553.

PR which introduced the feature: https://github.com/Cockatrice/Cockatrice/pull/3549

CC: @basicer

**Comment by ctrlaltca** [comment]
How do we want to implement the new mulligan rule?
Changing how the current "mulligan" implementation works would probably be bad of other games or people that likes to play with old sets using the old rules.
We could add a second "mulligan (London)" command implemented a:
1. move all cards from hand to deck
2. shuffle deck
3. draw initial # of cards

About every player I know uses the ctrl+m shortcut, should we bind it to the new mulligan or the old one?

**Comment by tooomm** [comment]
In what cases do you need the old rule? (magic related?)
How do other games perform "mulligans"?

**Comment by ShrewMaster** [comment]
My personal suggestion on how to implement this:

(1) Create an option in 'Settings...' that allows each player to choose what to do when they mulligan in a normal game. For instance, London mulligan -> shuffle current hand back and draw new hand of seven cards (then players can use other commands to choose which cards to put on the bottom of their deck); regular or Vancouver mulligan -> shuffle current hand back and draw new hand cards minus one.
(2) Replace the 'Take mulligan' command that appears when you right-click the hand zone with different mulligan options. Maybe associate these new commands to shortcut options. This would be my preferred choice.

Answering @ctrlaltca question, I suggest to make the London mulligan the new default for Cockatrice, since this will be by far the most popular mulligan used in games.

**Comment by MotherofRuins** [comment]
It's already getting tedious to draw that seventh card...  So I vote for London default.

Also recommend disabling a player's mulligan hotkey after any cards have been played.  Can still keep it in context menu if someone needs it later for some reason.

**Comment by ZeldaZach** [comment]
London mulligan _will_ be the default, once it's added in. Disabling the hotkey sounds reasonable, but it may not be as simple as you think to check game states and determine if the game has started yet or not...

**Comment by ebbit1q** [comment]
There is plenty of cards that tell you to take a new hand of cards, I use ctrl m for those all the time, don't take this away from me. :P

**Comment by MotherofRuins** [comment]
_it may not be as simple as you think to check game states and determine if the game has started yet or not..._

Understood.  That's why I said "cards have been played".  Maybe the game knows if it is already drawing cards on your side of the battlefield.

_There is plenty of cards that tell you to take a new hand of cards, I use ctrl m for those all the time, don't take this away from me. :P_

The problem is some people accidentally hit ctrl m when they are going for ctrl n or ctrl j, which is a mess to fix.  Would you be happy if, after there are cards on your battlefield, it ignores the first ctrl m but another one before anything else draws you 7?

**Comment by skwerlman** [comment]
> The problem is some people accidentally hit ctrl m when they are going for ctrl n or ctrl j, which is a mess to fix.
that's better discussed here: #3222

**Comment by ShrewMaster** [comment]
Another, even better, idea I just had: when players take a mulligan, ask them how many cards they want to draw (with a default to seven cards).

I think the only drawback this option has is it requires a little extra typing. Other than that, it solves a lot of other issues:
- no more conflicts between what type of mulligan (Paris, Vancouver or London) players want to take;
- reduces accidental pressing of ctrl + m when players weren't intending to take a mulligan (see comment above);
- new option for players to shuffle their hand back into their library and draw a new hand of cards (ex. Timetwister effects).
