### ISSUE TITLE
Saving pictures on a external hard drive unlinks on restart

### ISSUE THREAD

**Issue by OrphanStomper** [Cockatrice/Cockatrice#3809]
<b>System Information:</b>
Win 7 SP1
Version 2.7.2 (2019-08-31) (this problem has persisted for a long time through many versions)_

I have my pictures folder on a usb hard drive, and whenever I restart cockatrice and click to change the location, it opens program files/Cockatrice. I think it still downloads to the correct location, just opens the wrong one when I try to change it. 
Note: I have cockatrice installed in a custom location on C:
I get pictures not working correctly every now and then even though I always disable all promos, and I thought it was linked to this, but I'm not sure how.
I didn't paste the logs, because I couldn't find any relevant info(related to card pictures) in them throughout the process of restarting, changing location, and loading up a card picture (only says "found on disk")
1: after restart
![image](https://user-images.githubusercontent.com/29932680/64486575-fc049c80-d22e-11e9-8e4c-19e8e76d1aa4.png)
2: after clicking [...]
![image](https://user-images.githubusercontent.com/29932680/64486582-10489980-d22f-11e9-9cfe-f393e1c775ef.png)

**Comment by ctrlaltca** [comment]
> whenever I restart cockatrice and click to change the location, it opens program files/Cockatrice

When you click the button to choose a new path for pictures, the "choose directory" dialog doesn't open the current path by default. It starts from a "generic" directory, usually under windows it's the directory where cockatrice.exe is started from. 
This could be changed to open the current path instead, it seems more what people would expect.
Anyway, I doubt this can fix any problem related to not-working card images.

> Note: I have cockatrice installed in a custom location on C:

Looks like c:\program files\cockatrice, from your screenshot, but maybe it was just a test?

> I get pictures not working correctly every now and then even though I always disable all promos, and I thought it was linked to this, but I'm not sure how.

When you get a not working picture, then open the debug log and see what Cockatrice tried to do to load that image. Usually the problem is due to:
- loading the image for a promo/localized set
- loading a wrong image cached from the disk
- temporary website problems
