### ISSUE TITLE
Add ability to create a token that is a copy of a random creature (so that you can play Momir Basic)

### ISSUE THREAD

**Issue by furrycombatwombat** [Cockatrice/Cockatrice#3821]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
Currently momir is implemented through extra tools, putting this into cockatrice in a way that prevents cheating is a lot more difficult than you'd think as you'd have to take into account not updated card databases etc. Bexause of this we have deided it's best to leave momir basic to the online tool, because if you can't trust your opponent not to cheat why would you be playing a more fun and casual game with momir?

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/issues/329 duplicate
