### ISSUE TITLE
Extended Art for Eldraine Cards

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3847]
Title says it all. Currently, there is no way to display the non extended art cards for Throne of Eldraine.

**Comment by LivingInfinite** [comment]
This applies to sets released after Throne of Eldraine as well. 

For now I have been downloading non-extended card images and putting in my custom folder, but as long as sets keep getting released this problem is going to continue getting bigger.

Would it at least be possible to show the non-extended art by default?

**Comment by ZeldaZach** [comment]
This was fixed already in #3965
