### ISSUE TITLE
Ordinal Not Found

### ISSUE THREAD

**Issue by gormleymark** [Cockatrice/Cockatrice#3849]
<b>System Information:</b>
  Win 10 64bit. 
  Cockatrice 2.7.2 64bit.
_______________________________________________________________________________________
Full error message: "The ordinal 3906 could not be located in the dynamic link library \Cockatrice\ssleay32.dll"

Confirmed that the file is in that location.

This happens as I try to open the software. Click OK and it opens anyway, select card database, it comes up again and closes.

**Comment by ctrlaltca** [comment]
That error means that Cockatrice is loading up the wrong version of openssl, a quite common library used to make secure connections.
Since the version that we ship with Cockatrice is supposed to be the correct one, I think Cockatrice could be loading a different version installed by some other software.
This is possible if the other software installed their copy of openssl in a generic path (eg: c:\windows\) instead of inside their application folder.
The first thing i would do is to check if any copy of these files exists in other folders on the pc:
 * libeay32.dll or libcrypto.dll;
 * ssleay32.dll or libssl.dll;

If a copy of these file exists in a "generic" path (one contained in the %PATH% environmental variable, to be precise), i would try to temporarly rename it to .dll.bak and see if Cockatrice works.

**Comment by ctrlaltca** [comment]
Feel free to reopen if you still want to discuss your issue.
