### ISSUE TITLE
Bat token instead of Bat- card

### ISSUE THREAD

**Issue by Leonis26** [Cockatrice/Cockatrice#3911]
The card named "Bat-" has all the info from a "Bat" token (Description and Image).
It is a token from Time Spiral.

Description:
Flying
{1}{B}, Sacrifice this creature: Return an exiled card named Sengir Nosferatu to the battlefield under its owner's control.

**Comment by ebbit1q** [comment]
This is caused by the database storing it as "bat " (note the space) and the token overwriting it, the only reasonable way to fix this is to change the behavior of the database.
As a workaround we can simply change the way tokens.xml is made.
If you want to fix this problem for yourself you can temporarily edit the "Bat " entry in tokens.xml to have a few more spaces in it.

**Comment by Leonis26** [comment]
Thank you. So the token listed as "Bat " overrides the "Bat-" in cards.xml.
adding a space to "Bat " does the trick, but that's a hotfix. Thanks.

**Comment by ebbit1q** [comment]
You're welcome
