### ISSUE TITLE
OSStatus-Fehler 99999.

### ISSUE THREAD

**Issue by MTGplay** [Cockatrice/Cockatrice#3937]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by MTGplay** [comment]
I wanted to install Cockatrice but always when I try to open it it shows me this message: OSStatus-Fehler 99999.
What can I do?

**Comment by ctrlaltca** [comment]
Are you running macOS? What version?

**Comment by MTGplay** [comment]
Yes. MacOS Mojava version 10.14.6

ctrlaltca <notifications@github.com> schrieb am Fr. 3. Apr. 2020 um 14:10:

**Comment by ctrlaltca** [comment]
There are a few reports onthe internet about macOS System policy corruption. Once that happens, random applications are not able to run and return that error.
You can get some info on how to fix the problem here: https://hints.macworld.com/article.php?story=20130803041717457 , but it requires some skills to enter commands in a terminal

**Comment by MTGplay** [comment]
Thank you very much! I will try!

Am Fr., 3. Apr. 2020 um 14:52 Uhr schrieb ctrlaltca <
notifications@github.com>:

**Comment by ctrlaltca** [comment]
Did it work?

**Comment by MTGplay** [comment]
WEll, I asked some friends. But none of my friends or I do have skills like
that..so I am not able to do it. :-(
Thank you though!

Am Sa., 4. Apr. 2020 um 12:52 Uhr schrieb ctrlaltca <
notifications@github.com>:
