### ISSUE TITLE
Settings menu clipping on Mac

### ISSUE THREAD

**Issue by mingomongo** [Cockatrice/Cockatrice#3950]
```
MacBook Air (13-inch, Late 2010)
1.86 GHz Intel Core 2 Duo
4 GB 1067 MHz DDR3
NVIDIA GeForce 320M 256 MB
```

```
Client Version: 2.7.2 (2019-08-31)
Client Operating System: macOS Sierra (10.12)
Build Architecture: 64-bit
Qt Version: 5.13.0
System Locale: en_GB
Install Mode: Standard
```
_______________________________________________________________________________________

At minimum width, the settings menu cuts off the QCheckBox text.
![Screen Shot 2020-04-08 at 23 09 56](https://user-images.githubusercontent.com/33768220/78838633-83490700-79ee-11ea-94ce-c84519f7e68f.png)

**Comment by skwerlman** [comment]
Using Linux and i3, I cant repro when the settings window is floating (due to the window refusing to narrow beyond 1280px), but can repro when it is tiled (since the program cant control its dimensions)

**Comment by Olxinos** [comment]
This could be fixed by slightly changing the settings' dialog layout so that the checkboxes span two columns of the grid instead of a single one (right now, widgets are placed in the cells of an "invisible grid", and because the checkboxes and comboboxes belong to different columns of that grid, the checkboxes' labels can't extend beneath the comboboxes).

This can be done easily by editing dlg_settings.cpp:90-92 to use [this overload](https://doc.qt.io/qt-5/qgridlayout.html#addWidget-2) of `QGridLayout::addWidget` and specify a columnSpan of 2.
That'd look like this on OSX (I haven't tried on Windows or Linux though):
![settings_noclipping](https://user-images.githubusercontent.com/8961335/80221932-efa64600-863d-11ea-8a24-96f4eb45425c.png)
As a side effect, this also makes the settings window less wide by default (since it doesn't need to fit all the text from the checkboxes' labels before the comboboxes).

**Comment by ctrlaltca** [comment]
@Olxinos please open a PR with the fix if you'd like to 👍
