### ISSUE TITLE
Function of moving indicator directly

### ISSUE THREAD

**Issue by ryze12138** [Cockatrice/Cockatrice#3966]
Would it be possible to add a function to move the counter directly from one card to another in the future? Instead of subtracting the counter on one card and adding the same counter on the other card. I think this operation is too cumbersome.

**Comment by ebbit1q** [comment]
Are you proposing to make this change or are you only suggesting this feature? What would the user need to do in order to activate this action? How should the program display to the user that the action is happening?

The answer to your question is something only you can answer, only you should decide what you do but if you add this feature and open a pull request it would be welcomed.

**Comment by ryze12138** [comment]
only suggesting this feature

**Comment by ebbit1q** [comment]
I edited your ticket to reflect this.

**Comment by ZeldaZach** [comment]
There's no intuitive way in Cockatrice to add such a feature. In real life, you could just pickup and move the counters. Online, we don't have a relationship between cards so this is very impractical. I like the idea, but I don't think it's in the future of our program at this time.
