### ISSUE TITLE
Double-Faced Cards Rework

### ISSUE THREAD

**Issue by Soltero10** [Cockatrice/Cockatrice#4081]
Hello, I was wondering if it's possible to make it so the double-faced cards have something akin to a "flip card" option. It would 
help save space on the board with how the cards work currently.

**Comment by ZeldaZach** [comment]
This feature exists already. 
<img width="464" alt="Screen Shot 2020-09-03 at 5 55 14 PM" src="https://user-images.githubusercontent.com/7460172/92177511-a4334e00-ee0e-11ea-85be-da0a89c0dcbe.png">

**Comment by skwerlman** [comment]
this issue is requesting a fundamentally different way of handling DFTs, not simply asking for _a_ way

**Comment by tooomm** [comment]
It would be awesome to properly support DFC's in a way that their back faces are shown instead the default card back once turned over and the database knows it has two sides. 👍

**Comment by ebbit1q** [comment]
it'd be simple to add this to the token database similar to the way suggested here https://github.com/Cockatrice/Cockatrice/issues/4016
adding a tag like `<reverse-related attach="transform">` wouldn't be that much of a hassle.

**Comment by tooomm** [comment]
Are you suggesting to add every single DFC to the token database to give it that tag?
I'm not so sure if @Psithief likes that :)

**Comment by ebbit1q** [comment]
no, even oracle knows when a card is double faced, it specifically creates an extra entry for those cards, they're in the main database.

**Comment by Elarnon** [comment]
I am currently playing with some modal double-faced cards and I agree that the current "attach token" approach is sub-par and I would like to implement something different and more ergonomic. I have been looking at this issue, #3033 and #2030 and I believe the best solution would be centered around the rough idea in https://github.com/Cockatrice/Cockatrice/issues/3033#issuecomment-359230143

After digging around the code and some experimentation, I came up with the following design, which I believe handles the required use cases in a backwards-compatible way (in the sense that an old client that doesn't support card transformation could connect to a server that does, and see card transformations initiated by other clients — although it wouldn't be able to transform its own cards). Barring negative feedback on this design, I intend to give a go at an implementation in the next few days.

# Transformation Use Cases

Considering only MTG rules (because that's what I play), proper design for double-faced cards needs to accommodate the following scenarios:

## Scenario 1: Card A is transformed into Card B while maintaining state.

Effectively, this changes the name (and derived attributes such as P/T) of the card from A to B: all counters, annotations, attachments, arrows, etc. involving Card A now involve Card B instead. This includes Kamigawa flip cards and most transform cards (as per https://github.com/Cockatrice/Cockatrice/issues/3033#issuecomment-370121703).

This can be implemented either by adding a card attribute `AttrName` to be set using `Command_SetCardAttr`, or using a new `Command_TransformCard` command. I'd prefer adding a new `Command_TransformCard` command because that gives more leeway for adding additional information on the new card (e.g. its P/T), but I'd be fine with a new card attribute (although note that this would mean old servers would untap cards instead of transforming them!).

In the event log, the easiest thing to do would be to add a new event or card attribute, but this would break old clients. Fortunately, card transformation can be implemented using the existing events (although the event log gets a bit messy, see below). This means that there can be a tiny protocol negotiation: clients that don't support the "transform_card" feature will receive the series of existing events described below instead of the `Event_TransformCard` event. Alternatively, if it's important that all clients receive the same set of events (is it?), this can be done for all clients if any client (or maybe non-spectator client) doesn't support the feature.

### Transform using existing events

To represent a card transformation to old clients, the server can proceed by first detaching all attachments from card A (emitting as many `AttachCard` events as required), then destroying Card A (emitting a `DestroyCard` event), creating Card B (with a `CreateToken` event with `destroy_on_zone_change = false`), then transferring the appropriate state from Card A to Card B (with a combination of `SetCardCounter`, `SetCardAttr` and `AttachCard` events). 

There are two minor issues with this approach: first, there is some tuning that needs to be done to ensure proper placement of the transformed card, and second this approach doesn't work in local games when transforming a card that has an opponent's card attached to it because the events are re-ordered according to the player. The second issue is a non-issue in practice, because in local games the new event for card transformation is either supported by both or none of the server and client, so is only mentioned for completeness. The first issue can probably be figured out; alternatively, it might be acceptable that transformation causes the card to move on the board in certain conditions.

## Scenario 2: Card A is transformed into Card B *without* maintaining state.

In MTG, these are typically cards that are exiled, then come back transformed. Since changing zones already remove state (such as counters and attachments) from a card, this can be implemented on top of Scenario 1 by first blinking Card A (moving it to the rfg zone and back), then transforming it while maintaining its newly empty state. It can also be implemented as a special case of Scenario 3 below.

## Scenario 3: Cards A, B, C… are transformed as a whole into Card Z.

In this scenario (e.g. Meld cards), it is unclear what "maintaining state" would mean, since each of the initial cards A, B, C, … have their own separate state. So Card Z would always arrive as a "fresh" card in this scenario.

This scenario can be implemented by an extension of the `MoveCard` command. The `MoveCard` command already supports moving multiple cards at once. It can be extended by adding an optional `card_to_create` field describing the new card to create: if absent, the move proceeds as usual; if present, the server must destroy all the moved cards and create a new card using the information in the `card_to_create` field. In the event log, this can be communicated through a set of `Event_DestroyCard` and `Event_CreateToken` events in a fully backwards-compatible way (old clients just won't be able to transform their own cards).

# Reverting a Transformation

If only to correct mistakes, there must be a way to transform back a card to its original version. In the case of Scenario 3, this means "splitting" the new card into its original *set* of constituent cards.

One way to achieve this is to keep track, for a transformed card, of the set of cards it has been transformed from. Using a new command (let's say `RevertCard`), the transformed card can be destroyed (emit `Event_DestroyCard` from the server) and the set of cards it has been transformed from re-created (emit appropriate `Event_CreateToken` events). It also makes sense to perform this re-creation whenever the transformed card is destroyed — in particular if `destroy_on_zone_change` is set on the transformed card, a zone change would cause it to automatically revert to its original "version". Of course, this set of "original" cards should never be copied: a token that's a copy of a transformed card was not created from these "original" cards.

This set of "original" card should be mentioned in the `Event_CreateToken` events so that clients can display appropriate menu entries, but can be safely ignored by old clients as the behavior would be 100% implemented server-side (in fact, it can probably be implemented by keeping the `Server_Card` objects).

# User interface

The above discussion is centered on server behavior, and does not discuss implementation in the client. There are two parts of the client implementation: the transform information must be present in the card database, for which the solution of https://github.com/Cockatrice/Cockatrice/issues/4081#issuecomment-699691534 sounds appropriate; and the appropriate menus must be created.

For scenarios 1 and 2, it is only a matter of adding a new menu in the style of the existing "Attach: ..." menu. For scenario 3 (meld) things are a bit more complicated because the menu entry should only appear when a specific *set* of cards is selected. I need to dig a bit deeper into this part to propose a satisfactory solution, but it should also be fine to leave this to future work, knowing that the protocol will support it once someone gets around to implementing the UI.

**Comment by ebbit1q** [comment]
One of the things I was thinking about was simply adding it as a flag to the create and attach to token command that would simply hide the original card. it'd look exactly the same to old clients and new clients only really need to hide the attached original card.
