### ISSUE TITLE
Problems adding Custom Card

### ISSUE THREAD

**Issue by Walkmr** [Cockatrice/Cockatrice#4083]
I am attempting to create a custom card for the new Omnath, Locus of Creation from upcoming ZNR set. I followed the instructions on Cockatrice to make xml file with the card info but my cards do not show up in the card database.

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps
did you follow all of the steps? most notably making sure your file is utf8 encoded, including the <set> tags and verifying your xml using the xsd schema?

Also note that you wouldn't have to add omnath yourself because you can enable prerelease cards in the settings by checking the download spoilers option in the card sources settings.

**Comment by ZeldaZach** [comment]
If this is still an issue for you @Walkmr after following Ebbit's instructions, do let us know!
