### ISSUE TITLE
add option to remove a previous server

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4099]
**Similar Requests**
https://github.com/Cockatrice/Cockatrice/issues/2492

**Description of New Feature**
After adding a server there is no method to remove it in the client, you can only remove the related entries manually in settings/servers.ini

**Additional Context**
credit to user Frank#3570 from the discord https://discordapp.com/channels/314987288398659595/431200098978889728/755337204909342761

**Comment by mpalmujoki** [comment]
Seconded, I'd like to see this.

**Comment by rivten** [comment]
Are we talking about the combo box inside the "Known Hosts" radio in the "Connect to server" dialog ? Because if so, looking at the code there is a way to temporaly delete the item in the combo when pressing Shift+Del. But this only deletes the display data, if you reopen the dialog, all the server info will be back.

Do you want to make it so that, when pressing Shift+Tab, it also deletes the server ? Or should we build another dialog just for the purpose of deleting servers ?

**Comment by tooomm** [comment]
I didn't know about that temporary hiding thing. Interesting. :)

>Do you want to make it so that, when pressing Shift+Tab, it also deletes the server ?

You mean changing/expanding the behavior of `Shift+Del`, or introducing a new shortcut for `Shift+Tab`?
Having a shortcut could work, but then it could just be a delete button+confirmation next to the server details as well?

A complete new dialog just for that purpose? Hmm, not a fan of that.

**Comment by Fenrirthviti** [comment]
Strongly related to #742
