### ISSUE TITLE
Custom card art not changing

### ISSUE THREAD

**Issue by Feldmanny** [Cockatrice/Cockatrice#4201]
<b>System Information:</b>
Client Version: 2.7.5 (2020-08-23)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

I've been using a custom set, and if I change the picURL of a card after I add it for the first time the image doesn't change in the client. Removing and readding the card doesn't help. If I change a card's name to the name of another custom card that has been removed, the card will appear as the named one, even if the URL hasn't changed.

**Comment by tooomm** [comment]
Downloaded images are cached and the stored images always have priority. As long as the card name is the same, the old pictures is found and used.

In order to display the new art you have to delete the old one first. Check your `Pictures directory`. You find the path in the main settings windows of Cockatrice.
You can also delete all downloaded images in settings, but be aware that it deletes hundreds or thousands of downloaded pictures.

**Comment by Feldmanny** [comment]
Worked perfectly, thanks!
