### ISSUE TITLE
Portable Version Run Error

### ISSUE THREAD

**Issue by etherya** [Cockatrice/Cockatrice#4230]
after "setup":

double clic on exe:

couldn't find VCRUNTIME140_1.dll

**Comment by tooomm** [comment]
Which version of Windows do you use?
Which version of Cockatrice do you try to use in Portable mode?

**Comment by etherya** [comment]
WIndows 64 bit version

**Comment by tooomm** [comment]
>Which version of Cockatrice do you try to use in Portable mode?

**Comment by Fenrirthviti** [comment]
> WIndows 64 bit version

Can you be more specific which actual version of Windows you are on? If you are not sure, follow these steps to find out:

- Press Win+R
- Type "winver" in the box and press enter
- Screenshot the window or copy the line with "Version" in the name. Example: `Version 2004 (OS Build 19041.746)`

**Comment by ZeldaZach** [comment]
The portable version of Cockatrice doesn't attempt to install any dependencies. This is intentional behavior and coincides with what  "portable" build is. You can see this action at https://github.com/Cockatrice/Cockatrice/blob/48c64587661fd8e9b79ecae3bac2615058804427/cmake/NSIS.template.in#L234.

As a fix, you can either install Cockatrice in its full form, or install the VC Runtime, which you can find via [32-bit download](https://aka.ms/vs/16/release/vc_redist.x86.exe) or [64-bit download](https://aka.ms/vs/16/release/vc_redist.x64.exe)
