### ISSUE TITLE
Save Sort Order

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#438]
Keep a record of the sort order for games a user has.
ex: if they have it listed ASC for Creator, the next time it starts up it will load in that order.

Re #436

**Comment by Daenyth** [comment]
I think this is done

**Comment by tooomm** [comment]
Looks like remembering the sort order is working in the way Zach reported.

But rearranging the columns (e.g. you want the password column more on the right and the player count way more left) or changing the width of columns isn't saved at all.
I'm using a low resolution display (1280*1024) right now and still have unused space on the right. I could see so much more use of a bigger description or restriction column since people use longer names for there room if its something special or several restrictions.
You need to rearrange that every time you rejoin the chat room or reconnect to server.

**Comment by Daenyth** [comment]
Let's make that a second ticket since this is partially done.
