### ISSUE TITLE
The newly implemented partial card search is not user friendly.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#442]
1. I don't like it.
2. The deck editor is not compatible with a proper partial search.

A proper partial search lists all of the cards that match the start, *then* lists all of the cards that match anywhere else.

**How it is now:**
"search for `Mountain`"
* Goblin Mountaineer
* Madblind Mountain
* Magnetic Mountain
* Mountain
* Mountain Goat
* Mountain Stronghold
* Mountain Titan
* Mountain Valley
* Mountain Yeti
* Snow-Covered Mountain
* The Lady of the Mountain

**How it should work**
* Mountain
* Mountain Goat
* Mountain Stronghold
* Mountain Titan
* Mountain Valley
* Mountain Yeti

---

* Goblin Mountaineer
* Madblind Mountain
* Magnetic Mountain
* Snow-Covered Mountain
* The Lady of the Mountain

I don't want to be searching a list for Mountains when previously I could just type in `Mountain` and press Return.

As the deck editor search results are sortable, the implementation of a proper partial search does not seem feasible.

Please revert and try again.

**Comment by ZeldaZach** [comment]
I don't see a reason to change it from what it currently does, unless maybe @ctrlaltca would like to look into it

**Comment by Daenyth** [comment]
I'd like it to sort prefix matches higher than contains matches

**Comment by poixen** [comment]
We can add a check box next to the line edit to toggle between search modes?

**Comment by Psithief** [comment]
>toggle
I'm not convinced. Toggling it on and off almost removes the point of this in the first place: speed of use.

**Comment by Daenyth** [comment]
Yeah, I think a toggle would just confuse people more

**Comment by poixen** [comment]
Who Is going to take this? I cant :/

**Comment by Daenyth** [comment]
I can probably do it eventually. If you connect the textedit signals to a
resort command and make resort use the contents of the edit box I think it
shouldn't be too hard

**Comment by tooomm** [comment]
Another thing I just stumbled upon:
![search sorting](https://cloud.githubusercontent.com/assets/9874850/6446038/822c5182-c108-11e4-921e-b8c63f7842aa.png)

"`Ajani`, Caller of the Pride" is a perfect "`Ajani`"-match in comparison to "`Ajani's` Chosen" and should be ranked higher.
The comma and apostrophe should be handled with different priority.

**Comment by poixen** [comment]
This type of sort have a name?

**Comment by poixen** [comment]
If it is a known algorithm then I can try to implement it.

**Comment by tooomm** [comment]
Maybe this is helping you poixen:
http://en.wikipedia.org/wiki/Lexicographical_order

I'm not sure if that's helping at all, but the introduction of the wikipedia article in my languages says something like this:
"Lexicographical order is a way to create (out of a linear order of simple objects, e.g. alphabetical ordered characters) a linear order of compounded objects (e.g. compound words out of characters).
The eponymous example is the disposal of the words in a lexicon: first they get sorted by their starting character, followed by words with the same starting character, but different second letter etc.
Is there a word completely included in the beginning of another word (to stick with the example above: Mountain in *Mountain*eer) the shortest will be listed first."
The english articel looks to be more mathematical and technical. Not sure if it fits, though.

btw
My Ajani-example is a bad example for lexicograpical ordering.
It's more of a special case for us since there are cards with card names and additions to that name separated by `,`.
`'` is more of an extension to that word used for a grammatical case.
With german cards this problem doesn't exist, there is no genitive s in germany separated by `'` (well there are a few exceptions...): :P
![](http://magiccards.info/scans/de/m14/2.jpg)<br>
(=Ajani's Chosen)

Hope that helps!

**Comment by poixen** [comment]
@tooomm We are currently sorting Lexicographicaly. 
Also, it is true that Mountain is in "**Mountain**eer", the same holds true for "Goblin **Mountain**eer". Lexicographicaly "Goblin **Mountain**eer" comes before "**Mountain**eer".

Also on an ASCII table the char **'** comes before **,**
That would explain the ordering there.

**Comment by poixen** [comment]
Have made a fix for the issue in #796

**Comment by ZeldaZach** [comment]
Fixed
