### ISSUE TITLE
Lolth card has token action available to opponent rather than owner

### ISSUE THREAD

**Issue by AJWMJr** [Cockatrice/Cockatrice#4421]
**System Information:**

_______________________________________________________________________________________

"Lolth, Spider Queen" has it's token action available to the opponent rather than owner/controller of the card. The opponent can right-click the card and select the token creation action, but the controller/owner of the card does not have this option listed in the menu that comes up when right-clicking.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by tooomm** [comment]
I did only test in a local game, but it did work for me there.

Which client version are you running?
It helps a lot if you provide those details when opening an issue...

Can you please update your card database and token file (running "Oracle") and see if the problem persists.

**Comment by mainman879** [comment]
The way all token creation cards are written is so that anyone in the game can click the create token button and create the tokens. These tokens will spawn on their field in the area designated in the tokens.xml. This sounds like maybe your client or card database may be out of date. 

To update go to Help->Check for card updates (or Check for client updates if your client is outdated)

**Comment by tooomm** [comment]
>This sounds like maybe your client or card database may be out of date.
>
>To update go to Help->Check for card updates (or Check for client updates if your client is outdated)

Jep, I think so too.

If updating the client and the card database (indlucing the tokens) does not solve your issue, feel free to let us know with more details here and we try to help you! @AJWMJr
