### ISSUE TITLE
Planes: Display horizontally

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#479]
Some cards, namely planes, should be displayed horizontally, instead of vertically.
Not just in the command zone (or currently, the battlefield), but in the popup window/enlarged card in the upper right as well. They currently are condensed into vertical cards, making the art hard to read.

I can imagine this feature could also be useful for some other card games.

If possible, they could be enlarged in size as well to reflect their real life counterparts (which is twice the size of regular cards. This applies to schemes, vanguards, planes, phenomena.

**Comment by Jinxstands4Jinx** [comment]
and nothing is done.....

**Comment by Daenyth** [comment]
@Jinxstands4Jinx If you don't have anything useful to add I have no problem removing your ability to comment on tickets.

**Comment by Jinxstands4Jinx** [comment]
because i posted a comment and it got closed. so i commented here to be included in the conversation since I wanted to know what was being done about this.  And now because i wanted to know what was going on i am being threatened with being ignored.....I have helped this thing out a ton..if not then i will gladly take back all the help i have put towards cockatrice. Pardon me since i am not computer savy enough to be included in the conversation. just say so. I'll walk away

**Comment by ctrlaltca** [comment]
> so i commented here to be included in the conversation since I wanted to know what was being done about this

You can click the "subscribe" button in the right column of the thread to achieve the same result:
![schermata 2017-05-08 alle 16 25 05](https://cloud.githubusercontent.com/assets/1631111/25808615/f2baa030-340a-11e7-8a49-ad7b5c1f4f97.png)

**Comment by Jinxstands4Jinx** [comment]
did not know that. Also never saw the button.

**Comment by Daenyth** [comment]
Commenting saying nothing ever got done is not how an adult expresses
interest in a conversation. And I would still have said nothing if multiple
people had not already asked me to block you on several occasions prior.

I haven't because I'm assuming a combination of good intent and lack of
tact. Please work on the latter.

**Comment by ZeldaZach** [comment]
Having a change in the cards.xml via Oracle would allow for better handling in the client and we can read the properties of rotation within the widgets. Doesn't seem too hard to do.

**Comment by APillarOfSalt** [comment]
just add a check box in the top left of the card preview that will rotate the png you are looking at within the "Card Info" by 90deg (they can resize their preview window appropriately themselves after that)
