### ISSUE TITLE
Expand gender/pronoun support.

### ISSUE THREAD

**Issue by StellaBiderman** [Cockatrice/Cockatrice#487]
I'm playing in English.

It is currently using he/him/his pronouns, and despite changing the gender designation of my account, I can get it to neither use she/her/hers or they/them/their pronouns. I've tried both the "f" and "o" designators for gender on my account page and nothing happens.

**Comment by JSBiderman** [comment]
Any progress?

**Comment by Daenyth** [comment]
I think this actually doesn't impact translation a ton, though that's a nice to have. The `unknown` gender level already existing has the two-gender icon and uses "they" in English, which covers a lot of people.

I'm really uncertain how best to handle more complex cases though - do we want to support things like xe, and how can we direct translators? If we only add a proper name using the existing two-gender icon, what should we call it? Queer? That certainly doesn't cover everyone using "they" for their pronoun. This stuff is extremely complicated and I don't want to get it wrong for people, but at the same time I have very few ideas on getting it right.

**Comment by Daenyth** [comment]
Note to self: https://github.com/Cockatrice/Cockatrice/blob/69e6aa355ff9caa016f066447b2d3aad5978dbb8/servatrice/src/servatrice_database_interface.cpp#L270

**Comment by Daenyth** [comment]
I spoke with a friend of mine and these are their recommendations:

Change male/female to masculine/feminine
Add a top level neutral option, using the two gender icon

And I'll also add a proper unspecified option as the default, using the null gender icon. In English both the unspecified and neutral would be put with "they" pronouns but it would allow translators more information for use in their language.

@JSBiderman what's your opinion on that proposal?

**Comment by JSBiderman** [comment]
That sounds wonderful! Thank you for caring :)

**Comment by Daenyth** [comment]
WIP branch: https://github.com/Cockatrice/Cockatrice/tree/gender-updates

**Comment by Daenyth** [comment]
@ideocl4st FYI expect a huge string update when this is done. I have no idea how korean handles gender neutral pronouns but it would be good to look into if you're uncertain

**Comment by ideocl4st** [comment]
I don't mind huge string updates at all, but I do agree that I'll need some research as well.

Thanks for letting me know about it beforehand.

**Comment by Daenyth** [comment]
It'll be four cases - masculine, feminine, unspecified (use whatever you would when you don't know the gender) and neutral (in english they'd have "they" as a neutral pronoun)

**Comment by Daenyth** [comment]
@JSBiderman I don't know how technical you are - there's a LOT of tedious translation work that needs to be done for this feature and it's extremely time consuming. If you have even a passing knowledge of C-family programming languages I think you could help speed things along to get this done faster, otherwise it's going to be done in bits and pieces whenever I have time (I don't have a lot of it and since it's tedious I'd honestly rather work on other features). It'll get done eventually, but it's going to take a really long time

**Comment by realityfabric** [comment]
I took a quick look at your gender-updates branch, and I can already tell it deals with the cases better than the main branch.
I'm familiar with C and C++, I'd be willing to spend some time on this.

**Comment by Daenyth** [comment]
@realityfabric I'd really appreciate that.

**Comment by realityfabric** [comment]
So, I completely lost track of time, but it looks like it's still not done so I'm working on this right now. I know that in local games it still assumes that the players use He pronouns (I don't think there's a way to change that for local games, although I haven't checked that specific thing since the latest update).

A problem I've run into in modifying the code is the difference between how the tr text is written between lines like https://github.com/Cockatrice/Cockatrice/blob/gender-updates/cockatrice/src/messagelogwidget.cpp#L338 and lines like https://github.com/Cockatrice/Cockatrice/blob/gender-updates/cockatrice/src/messagelogwidget.cpp#L385

The former example there's text, and then the gender/pronoun-set is listed separately from the text, but in the latter the pronouns are embedded directly into the text itself.

So far I've been assuming that I can just take lines that have tr("text here", "pronouns here") and make it so that "unspecified gender" and "gender neutral" are included in a switch, but I'm not actually sure how the translation code works, so I'm not sure how to handle that second case.

Hopefully my assumptions aren't wildly off.

**Comment by Daenyth** [comment]
Unfortunately the translation told work from the raw strings so you need to
have hard coded variations for everything.

**Comment by realityfabric** [comment]
I finished writing the strings, and it compiles, but it looks like there's some sort of problem from before I started, when trying to run Cockatrice it prints `cockatrice: symbol lookup error: cockatrice: undefined symbol: _ZN6QDebugD1Ev` and does nothing else

**Comment by tooomm** [comment]
@ctrlaltca might help you!?

**Comment by realityfabric** [comment]
I think the symbol lookup error was something to do with Qt, but I switched back to 5.2 for the time being until I have time to figure that out.

It compiles, and runs, but local games still default to using he/him/his

**Comment by ctrlaltca** [comment]
The symbol lookup error is probably due to having more than one Qt version installed at the same time: Cockatrice has been compiled with a version but when running it it loads the libraries of the other version.

**Comment by ctrlaltca** [comment]
We ended up dropping the entire handling of the "gender" concept in #1955.
