### ISSUE TITLE
cant download cockatrice on windows 11

### ISSUE THREAD

**Issue by Eric09000** [Cockatrice/Cockatrice#4894]
**System Information:**

_______________________________________________________________________________________

when i click on download for windows 7+ it brings me straight to the "Cockatrice 2.9.0 - Rings of the Wild" page instead of the download screen popping up 

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A - click on cockatrice on google 
 - Do B - click on the side bar
 - Do C - brings me to rings of the wild page instead of downloading

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/releases/tag/2023-09-14-Release-2.9.0 scroll down for download links, select the one that matches your os, we have win7 and win10 builds, both are compatible with any later version.

**Comment by tooomm** [comment]
That's due to the [script](https://github.com/Cockatrice/cockatrice.github.io/blob/master/javascript/githubAPI.js) on the webpage being outdated and no longer providing the links to the binaries directly.

Fallback is to open the release page which has all the downloads available. So everything working as expected.
Users just need to scroll down and pick their own OS from the list. 👍 
<img width="711" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/380373d7-3411-4c89-817d-a6e31b73f988">
