### ISSUE TITLE
Option to sort/search/filter cards by rarity?

### ISSUE THREAD

**Issue by drewcoaustralia** [Cockatrice/Cockatrice#492]
Can you PLEASE add a function to sort/search by rarity? It would be really useful for pauper and pauper edh and other formats of that nature. It would be really simple to do too I'd imagine, unless it relies on MTGJson and they don't have rarities

**Comment by MagnusD20XX** [comment]
i don't know why you're complaining about how hard it would be to implement a search by rarity function. MWS has it and it works great. it also has, generally, a better interface. the only thing keep cockatrice ahead is the fact that it has a much more stable and large userbase and it's easy to get set up from scratch. otherwise i would NEVER use it.

**Comment by MagnusD20XX** [comment]
what it does is when you search any card's name it gives you each version of the card with the same name across all expansions you have it set to search across. if you have ten sets selected and you search mountain you get each individual mountain available in all the sets. if you search a card with multiple rarities you get a result for each card, etc. it's not hard, just bigger. and very useful.

**Comment by Nightfirecat** [comment]
@MagnusD20XX If it's so easy, feel free to implement it and submit a pull request. Otherwise, if you don't have something constructive to add, why comment?

**Comment by Daenyth** [comment]
I don't think anyone is complaining about it being difficult, we're just talking about what changes to the application would be required. And @MagnusD20XX we're always open to constructive feedback, so if you have ideas about how we can make the app better, please open new issue tickets for your suggestions.
