### ISSUE TITLE
Hide hidden inflrmation of yourself in the log

### ISSUE THREAD

**Issue by quikecosta** [Cockatrice/Cockatrice#4972]
I would like to have an option for the log to hide information that should be hidden to my opponents.

The goal of this improvement is to be able to record the cockatrice screen to play by spelltable without revealing information to the opponents that they should not see but at the same time showing my actions in the log as if they were my opponents in the program itself.

Many people use moxfield to play by spelltable but I honestly believe that cockatrice is a better tool for this same purpose, with a log of all game actions, many more options and better shortcuts.

**Comment by ebbit1q** [comment]
cockatrice itself is designed to play directly with other players using cockatrice as well, streaming cockatrice through spelltable is not a usecase we aim to support, neither do I think spelltable does. (instead I think wizards would rather push something like modo or arena on you)

on the other hand I see how it might be convenient for you to use cockatrice over spelltable with other people that do want to shuffle physical cardboard.

the log however doesn't seem like it'd stop you, it is easily hidden (just click the x on the widget).

what I imagine the real issue is is the fact that cockatrice will display your cards in hand to you at any time and with streaming the application through spelltable also to your opponents.

if cropping out parts of the screen isn't an option to fix this, perhaps you could create a local server and connect a second instance of cockatrice as a spectator, then you can stream the window of the second instance which will include all actions as seen by an opponent on cockatrice. (they won't be able to interact with the log in the way they can on cockatrice of course)

to start a local server open a terminal/command prompt and run servatrice, to connect to this server you add a new server in the cockatrice connection dialog, the address will be 127.0.0.1 and the port 4748, by default you can log in with any username without password.

simply log in on both instances of cockatrice and start a game for one player on one account, make sure the game allows spectators but not the viewing of hands, then join it as spectator with the other client.

spelltable sort of awkwardly has to do its own card recognition not to mention it'll use much more bandwidth and resources than the small kilobytes needed for a cockatrice game, it's possible spelltable could branch out and somehow include its own tabletop simulator but a more direct combination with cockatrice is unthinkable.

I will close this ticket as it is not planned or actionable (clients are actually completely unaware of what is hidden information to other players) within cockatrice, feel free to continue discussing workarounds.

**Comment by Esnos33** [comment]
I just did it for fun and its easier than I thought. Thanks for brilliant solution ebbit

**Comment by ebbit1q** [comment]
you're welcome, it's not originally my idea though, I saw a streamer use this to share on twitch

**Comment by Esnos33** [comment]
Do you remember which streamer did it? I don't see a lot of people stream cockatrice and I would like to see cockatrice on stream

**Comment by ebbit1q** [comment]
something like mtg420 however I checked a while ago and they don't seem to go online anymore.

**Comment by ebbit1q** [comment]
there might be other streamers though, maybe you could ask around on the cockatrice discord
