### ISSUE TITLE
Crash on dialogue menu related to owned/attached cards

### ISSUE THREAD

**Issue by FROG-TM** [Cockatrice/Cockatrice#5019]
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_GB
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
Attempting auto-connect...
PictureLoader: cache fail for "_trice_card_back_226396"
PictureLoader: cache fail for "_trice_card_back_226295"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/User/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/User/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 29170 Sets= 747
[CockatriceXml4Parser] Trying to parse:  "C:/Users/User/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/User/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 29963 Sets= 747
[CardDatabase] loadCardDatabase(): Path = "C:/Users/User/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 29963 Sets= 747
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

Issue description

Encounted an issue first in a game in which a card owned by myself was given to another players field, with another card owned by myself subesquently attached too that card. When other player attemped to click and drag the attached card Trice hung breifly and then crashed. The issue occured again on restart.

Both cards in question had dialogue options for a token attach (double face card)

_______________________________________________________________________________________

Recreation process

- Have player A give player B a card.
- Have player A attach a card to the given card.
- Have player B attempt to move, or open a dialogue box for the attached card

I was able to recreate the issue but not consistently, issue was present regardless of who acted as player A or B.

**Comment by tooomm** [comment]
Can you please update your outdated client and see if your issue is still persistent in the newest release (v2.9.0)?

Use the build in updater under 'Help'.

**Comment by http404error** [comment]
I had an issue resembling this one in v2.9.0, at least it seemed to be related to the Attach feature.

I right-clicked the foe's Blanchwood Armor to see if I could try to helpfully attach it to their Ornithopter. I didn't expect this to work, since both were on their side of the field, but the Attach card option was unexpectedly available anyways. However, my Demolition Field attached to the Ornithopter instead, which was the last card I had clicked previously. I unattached to get my Demolition Field back and tried a few more times to make sure I was selecting the Blanchwood Armor correctly. I noticed that the Ornithopter had moved all the way to the left side and the Blanchwood Armor was floating as if it was still stacked. The opponent reported being unable to move the Ornithopter at all.

Then, the client disconnected from the server for both of us, and we couldn't reconnect for a while.

![image](https://github.com/Cockatrice/Cockatrice/assets/2876044/4ad71d7e-21b1-4b7e-a460-4a09a0640140)
[debug log.txt](https://github.com/Cockatrice/Cockatrice/files/14965593/debug.log.txt)
