### ISSUE TITLE
Segfault on saving in Deck Editor

### ISSUE THREAD

**Issue by greg-mitchell** [Cockatrice/Cockatrice#505]
I followed the instructions for compiling Cockatrice using Qt5. When I try to save in the Deck Editor window, Cockatrice crashes and stdout prints "Segmentation fault".

The result is the same using either of the menu options or the hotkey, with none, one, or many cards in the deck, and with one or many deck editor tabs open.

I tried installing the Qt4 development tools as well just to be sure it wasn't a dependency issue, but there was no difference.

 * Commit: f52935791cbf985ca532071185cd5e7f5cf86624
 * uname -a: Linux <hostname omitted> 3.13.0-43-generic #72~precise1-Ubuntu SMP Tue Dec 9 12:14:18 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dhhxu** [comment]
Has there been progress on this front? I'm also having segfaults too.

**Comment by ctrlaltca** [comment]
After some investigation it seems that the segfault is due to Qt failing to draw the icon for the file dialog in the WM's taskbar. The most probable cause could be the really old version of Qt 5.0.2 that's shipping with ubuntu 12, and probably didn't fully work with unity.
I suppose that compiling cockatrice against a newer qt version could fix the issue, but unfortunately the testing packages for qt 5.2.1 never made an official appearance on the ubuntu repos.

**Comment by dhhxu** [comment]
I found a workaround of sorts:

If I open Cockatrice and am not logged in, attempting to create, load, or do anything that requires the file dialog, gives a segfault.

But if I open Cockatrice and log in first, then there are no issues and the file dialog works. Creating, loading, saving decks works without an issue.

Note that I have compiled Cockatrice with the QT4 flag set to on on Ubuntu 12.04

**Comment by Daenyth** [comment]
Can you try compiling with Qt5?
