### ISSUE TITLE
Moderators Can Be Ignored?

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#536]
I'm not certain why this is, but there should be a block to this

**Comment by woogerboy21** [comment]
I ignore them all the time..... sometimes multiple times a day.

**Comment by ZeldaZach** [comment]
Hence why I ban you from the server on a daily basis  @woogerboy21

**Comment by anoda9** [comment]
I have a moderator on my ignore list. It's not out of defiance or anything like that, it's just that I find them obnoxious/annoying and it detracts from my experience to have to read their messages in the chat. 

The biggest issue I can think of is that a user with a moderator on ignore won't be able to see that moderator warning them in the main chat or through pm. Implementing a formal warning system (a popup that can't be ignored, or a pop-up + 2 minute chat muting) or making it so users can't ignore moderator PMs would solve this. Alternatively, it could just be a risk a user takes by ignoring a mod - if you have them on ignore, you might find yourself banned without warning because you couldn't read their verbal warnings in the chat. For most (non-troll) users this will never be a issue though.

**Comment by Psithief** [comment]
I also have an obnoxious, insulting, unbearable moderator on my ignore list. (No, it's not you Zach. :stuck_out_tongue:) I must agree with everyone except Zach.

**Comment by Daenyth** [comment]
I think there's decent consensus on this

**Comment by ZeldaZach** [comment]
Oh well, worth a shot
