### ISSUE TITLE
Default set selection for Oracle doesn't encompass all printed cards

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#539]
In the sets selection step in Oracle, the default set selection is all the core sets + expansion sets. However, this selection ***does not*** encompass all the cards printed in magic, so a user going with the default selection will be missing unique cards from the commander, planechase, and conspiracy sets, which can often show up in legacy, cube or EDH. (e.g. True-Name Nemesis, Shardless Agent, Grim Tutor). The fact that the default set selection does not include data for True-Name Nemesis (a card that appears fairly often in legacy) is pretty poor. All the portal sets also seem to be excluded. 

Fix: Add the the non-standard legal sets (planechase, commander, conspiracy) and portal to the default set selection in oracle.

sets to be added:
http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets#Non-standard-legal_sets
http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets#Introductory_sets

![set selection](https://cloud.githubusercontent.com/assets/3486897/5694544/a1ef49b4-9919-11e4-848d-39adcbebf137.png)

**Comment by ZeldaZach** [comment]
I still don't know why it has default checkboxes. It seems so random to me on what sets are selected.

**Comment by tooomm** [comment]
For me it looked very random, too.

@anoda9I like your point  of increasing the user experience of most common users.

To round it up there should be additional text to clarify?
"The preselection of sets contains all printed magic cards"

**Comment by ctrlaltca** [comment]
I assume it's fine to enable by default all sets: opened PR #540

**Comment by anoda9** [comment]
Personally, I'd prefer not to have all the sets imported - I dislike the art for the reprint sets and don't want to have to deal with moving them to the bottom in the set order window later. That might be just me though. 

The real issue with defaulting to all sets is that it decreases options for the user - if someone wants to have all the sets, the "check all" button exists already, but there's no button for "select all non-reprint sets". So by making the selection default to all sets, you're giving people fewer options.

**Comment by anoda9** [comment]
Maybe if would be better if rather than being ordered alphabetically, the sets were grouped into categories, then sorted chronologically. This would make it easy to put "category checkboxes" at the beginning of each group of sets, which would make it very easy to select which group of sets you want to import. 

Something like:
[x] Expansions and core sets:
     [x] Alpha
     [x] Beta
     [x] (etc.)
[x] Non-standard legal expansions:
    [x] Commander
    [x] Planechase
[x] Introductory sets:
    [x] Portal
    [x] Starter 1999

clicking the "x" for one the broad categories would select all expansions under that category. The list of expansions under each category would be hidden by default but would be displayed if you click an arrow next to the category. I'm envisioning something like this:
![vvfm2](https://cloud.githubusercontent.com/assets/3486897/5696207/89d523ec-997a-11e4-9835-5cdb195ecd93.png)

**Comment by aeosynth** [comment]
related: #133

**Comment by tooomm** [comment]
The set selection screen from Oracle is weird.
I'm just playing limited and every time I run Oracle it's a pain to scroll and search through all the list...
I don't need and want all the cards ever there, just the few I really play/come across.

So I find myself searching for the last set(s) I need. Every few weeks or at least every time a new set appears.
(Maybe it's not necessary... but when I install a new weekly build I always re-run Oracle, too)

I like @anoda9 's thinking. Grouped sets by category (standard expansions, non-standard legal expansions, ...), maybe with subgroups by block sets would be very nice. (THS --> THS+BNG+JOU)

Here are some thoughts:
- a check box for chronological or alphabetical sorting
- some sort of grouping by set blocks at least
(with check box or obvious names of the subgroups like "THS (THS/BNG/JOU)", if someone doesn't know the corresponding block)
- a button which provides the selection of all printed cards (--> anoda9)
- a button which restores the sets I marked the last time I ran Oracle to easily expand my cards.xml to contain the newest sets (e.g. add frf to ktk in my case). Like the one in the card database editor restores your ordering, this one will restore last checked/actually stored sets in cards.xml.
- explorer-like jumping to items if you click the list and type a letter + space to mark/unmark

I know that some points interfere with each other, so with alphabetical ordering a keystroke search (jumping to the start letter - like in explorer if you type e it will jump to the first file starting with "e") is very useful. But when the sets are ordered chronological it will jump around in the list.
If there are groups/subgroups it might don't work at all etc.

I guess a real search, which filters as I type and understands short forms ("ktk") is a bit too much?
But anyway search and displaying of the list should be two different things...

Any thoughts? Especially from the technical site...

**Comment by anoda9** [comment]
@tooomm Those would be useful features but they might go beyond the scope of what Oracle really needs right now - it doesn't get used very often (most of the time people will run it once on install and again every time a new set is released) so adding a lot of different options might not be worth the work when the average user only touches it once or twice. 

To be fair maybe my (and aeos's) proposed changes goes beyond what is needed, but it seems like the most improvement for the least effort.

**Comment by tooomm** [comment]
It was just a list of thoughts to help players use that program ...

**Just chronological ordering with newest sets on top**
OR
**searching the (alphabetical?) list with explorer-like jumping to start letters of sets**
OR
**some kind of grouping with easy block sets selection**
....
will make the trick.

They all improve the program in my opinion. But we don't need it to be a perfect search, true. :)
That's why I was asking for technical background - which one(s) offer the most benefit while being implementable with reasonable effort.


I still don't know what the preselection right now is about. Never took the time to check all marked sets and try to find out. So your suggestion about improving that is nice, too. Making it all printed cards is reasonable.
And explain the user what is selected by default is also very important I think.

**Comment by ZeldaZach** [comment]
It seems like we'd need an entire rewrite of the oracle tool to accomplish most of these things...

**Comment by woogerboy21** [comment]
The question I would have is, does the mtgjson file have categories?  I don't think anyone has any interest in manually maintaining a list of category type information.

**Comment by tooomm** [comment]
source: http://mtgjson.com/#sets, http://mtgjson.com/#cards

Interesting fields that can be helpful:
**type** : "expansion", 
**block** : "Masques",  
**onlineOnly** : false,  
**legalities** : { "Legacy" : "Banned", "Vintage" : "Restricted", "Commander" : "Legal" } 

(just example data)

**Comment by Cerxi** [comment]
I'm no JSON master, but categories for each set are in the file Oracle /outputs/, as <settype>, so MTGJSON must have them (as previously mentioned by tooomm).

Speaking of which, legality's in there too? Interesting.. That doesn't make it to cards.xml, and maybe that could be a useful future feature. Cockatrice could show your deck legality by just displaying only displaying formats that every card has "Legal" in. There'd be no need to keep a list of formats in the program, it would just have to display every X pulled from "X" : "Legal" that matches on every card.

**Comment by Daenyth** [comment]
I think the current consensus is that we should not check all by default?

**Comment by tooomm** [comment]
Check *All entries* by default doesn't make much sense I think. Especially since we have a button for this.

@anoda9 wanted the default to be *all printed* cards. That's still a difference because there are some online only sets: http://mtgsalvation.gamepedia.com/Magic_Online#Online-only
So his idea is that people who don't change Oracle's default selection still have like 99% of the cards their opponents are going to play.
With our default right now it is more like ~95% depending on the format.

The "All" button's could say something like "All printed and online only sets" instead, if we go for anoda9's idea.

**Comment by Daenyth** [comment]
Unless I'm mistaken there's no legal cards that have been printed online but not printed offline.

Honestly I'm not sure why anyone would want to not check all with a few exceptions - those being alternate formats like vanguard, planechase, archenemy, conspiracy. My preference would be all cards used in regular constructed magic

**Comment by tooomm** [comment]
I'm the wrong person to answer the legality thing. Does the explanation/example in the starting post help you Daenyth?
@anoda9 you know about the legality issue since you filed this?

For myself, I definitely don't want to download all cards! I just want the most recent 1-3 sets.
I can imagine that to be the most recent ~6 or something for the standard only players.

So there is demand I guess. That's why I keep asking for the chronological ordering with the newest sets on top. ;) (optional is fine too)

**Comment by Cerxi** [comment]
@Daenyth "all cards in regular constructed magic" would in fact include sets like Planechase and Conspiracy; those cards (not the planes or the conspiracies themselves, but unique cards from those sets) are legal in Legacy.

**Comment by Daenyth** [comment]
Woops.

**Comment by ctrlaltca** [comment]
I think that adding filter and sort functionality in oracle is a step in the wrong direction.
We should just let oracle import as much cards as possible as better as it can, and move all the logic inside cockatrice.
Reading all the comments, i think that adding an "enabled/disabled" option to each set in cockatrice is a good starting point.
Cockatrice will save/load the list of enabled sets in its config, so every time you'll run oracle again you'll automatically have available only the sets you want (oracle will import them all, but cockatrice will only show the enabled ones in deck editor).
Adding an additional "known/unknown" option to each set would let cockatrice ask you "hey, i've found a new set since the last run, i suppose that you just ran oracle and imported a new set, do you want me to enable it now?".
Plus, if you're spectating a game where players are using cards from sets you don't commonly use, cockatrice will know and show the cards correctly.

**Comment by ZeldaZach** [comment]
On reddit a user suggested the following sets to "default" to: https://www.reddit.com/r/Cockatrice/comments/2zaduv/had_this_problem_since_forever_cards_with/

**Comment by Cerxi** [comment]
A lot of those sets are all reprint sets, which is really no better than having it set to "Check All" by default. The list of sets that would need to be added to the current default to cover constructed magic without having promotional or reprint sets is:

* Commander 2013 Edition
* Commander 2014
* Magic: The Gathering-Commander
* Magic: The Gathering--Conspiracy
* Planechase 2012 edition
* Portal
* Portal Second Age
* Portal Three Kingdoms
* Starter 1999

Optional, for unique cards not used in regular magic:

* Archenemy (for the scheme cards)
* Happy Holidays
* Planechase (for the plane cards)
* Unglued
* Unhinged
* Vanguard

**Comment by ctrlaltca** [comment]
Everyone has a different list of preferred sets.
Hardcoding in oracle the list of my preferred sets or of your preferred sets is a mistake, because it won't fit everybody else's needs, and they won't enjoy having to scroll the sets list in oracle in order to enable their preferred sets and disable the others.

**Comment by Cerxi** [comment]
This isn't about a list of "preferred" sets, this is about the minimum number of sets to have every constructed-legal card in Magic.

**Comment by ctrlaltca** [comment]
Sounds like a matter of wording: if it's not a list of preferred sets, it's the minimum number of sets to have all the legal cards of a preferred format (constructed).

**Comment by Cerxi** [comment]
Constructed isn't a format. Constructed is all legal formats.

**Comment by ctrlaltca** [comment]
I could just answer "is limited illegal?" or "why couldn't i play my_own_illegal_format?" but this is getting too childish.
Again, i don't think we should force people into a default list of sets every time they run oracle, even if it's the best list ever. Users should be able to configure their preferred sets once, and cockatrice must follow the user-chosen configuration, not overriding it every time cards gets updated.

**Comment by Cerxi** [comment]
I'm not sure why you think this is childish? I'm presenting my opinion calmly and rationally.

Cockatrice can't play limited, that's why external tools for that exist. Unless your illegal format uses Un- cards, you could certainly play it with that default list. That's all I'm saying. That list, the list I wrote out, downloads, by default, every black-bordered card in magic, without downloading silver-bordered cards or all-reprint side sets.

And yes, I would love to have a customizable list of default sets. But they said they'd need a complete rewrite of the oracle tool to accomplish this. For the interim, I'm trying to offer a better default list, because since there IS a default list, it can probably be CHANGED. It's, at least to me, important to make sure that by default, you can see every card people play.

**Comment by ctrlaltca** [comment]
Thank you for providing your list, i didn't want to attack you and i appreciate your effort in trying to contribute something useful to the cockatrice community.
Anyway, i proposed some changes in #891 that should work this out. Basically removing the sets selection at all from oracle, and adding the ability to enable/disable sets inside cockatrice, that will remember the user preference. When a new set is added by oracle to the card database, cockatrice will notice and ask the user if he wants to enable it.
