### ISSUE TITLE
Confirmation dialogs for some hard-to-reverse actions

### ISSUE THREAD

**Issue by ideocl4st** [Cockatrice/Cockatrice#584]
Actions that are difficult to reverse such as mulligan and putting all cards in hand to bottom of library (or anything that affects multiple cards in a player's hand) should have a confirmation dialog.

In fact, is there a way to prevent players from doing mulligan in the middle of their games?

**Comment by Daenyth** [comment]
The only thing that's hard to undo is shuffling. I don't see us adding a confirmation to that action any time soon.

Has this really been a widespread problem for people?

**Comment by ZeldaZach** [comment]
I don't see a way we can properly do this based on the # of cards in a deck or such because of things like serum powder and try and calc the # of permanents currently on the battlefield...

**Comment by anoda9** [comment]
Confirmation dialogs would be really annoying imo. Making all actions undo-able seems like the better solution.

Putting cards onto the bottom of the library doesn't seem like a huge deal - you can crtl-drag on your library to play the bottom card to the stack (not a good fix if the card came from a hidden zone/was not known to your opponent, but for other cases it works).

The midgame mulligan is certainly a problem, as it's very disruptive and impossible to undo, even though it doesn't come up very often. The underlying issue is that the undo function doesn't work for all actions. If you could implement a way to undo mulligans, that would help. 

The simplest solution would just be to change the mulligan shortcut to something harder to press accidentally. i.e. crtl-shift-M - adding the extra keypress makes it harder to hit accidentally. Alternatively, there could be a shortcut for "keep" that writes a message to the chat and automatically disables the mulligan function for the rest of the game. (crtl-K --> "anoda9 keeps his hand", crtl-M disabled)

**Comment by Daenyth** [comment]
Having undo work for more actions would be good for sure, but it's still tricky because you start to need to maintain a history. It's an option for the future

**Comment by ideocl4st** [comment]
I didn't know that you can play card from the bottom with Ctrl+Drag, so I guess that is reversible.
I still think there should be a way to prevent people from making mistakes with mulligan though.

While we are on this matter, perhaps this is why people are making mistakes with mulligan/putting cards to wherever. Right-clicking on hand zone (to reveal cards) may let players to click on any of the actions that we have discussed. 
![untitled](https://cloud.githubusercontent.com/assets/2484055/5885042/3659eda4-a3a9-11e4-9c51-63f101619001.jpg)

Maybe putting these into a sub-menu like this:
![untitled2](https://cloud.githubusercontent.com/assets/2484055/5885066/873fce1e-a3a9-11e4-966e-b9743a6a5acd.jpg)
can work better? It is already that way when you select one or more cards in your hand.

**Comment by poixen** [comment]
I think this will slow down play. Also is this highly requested enough to spend [our rather limited] development time on?

**Comment by ideocl4st** [comment]
Well...Now I'm convinced that confirmation dialog isn't such a good idea.
But I still think the right-click context menu needs some changes.

**Comment by Daenyth** [comment]
We can move the Mulligan action further doesn the list to help avoid accidental activations

**Comment by ideocl4st** [comment]
![contextfromtop](https://cloud.githubusercontent.com/assets/2484055/5889775/8227448e-a47b-11e4-9e7e-f74da202c3b0.png)
![contextfrombottom](https://cloud.githubusercontent.com/assets/2484055/5889776/822a7aaa-a47b-11e4-9f63-40da40715fb2.png)

Depending on cursor and Cockatrice's position in the screen, the bottom menu can be the closest option to the cursor.

**Comment by Daenyth** [comment]
Can you PR your change?

**Comment by ideocl4st** [comment]
Done, I took some initiatives though.
