### ISSUE TITLE
Add user-creatable rooms

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#622]
# Brief:

Users can create their own rooms so that they can form micro-communities within a cockatrice server. This will allow them to create a more trustworthy play experience since they can control users themselves.
# Main ideas
- Room creators can add other users as room operators who can help manage the room.
- Creators (and possibly operators) can manage access lists - whitelist & blacklist for room joining.
- Room creator can have user level restrictions - permit only registered users, only mods, only admins, etc
- Room creator can set a password on the room

**Comment by Daenyth** [comment]
- modify existing rooms table for password field, user level restriction, channel owner
- decide whether any rooms should be special - possibly add a force-autojoin flag for main room
- add a table for white/black lists referencing a room
- add a table for channel operators referencing a room
- add a command to create room
- add a command to delete room
- figure out how to handle games from deleted rooms
- figure out how to handle client display when they are in a room being deleted
- add servatrice option to control whether room creation is for reg user or mods or admins
- add proto for room creation event
- figure out how to inform people about rooms.

**Comment by woogerboy21** [comment]
Does this lead into a roles based permission system for the client/server?

**Comment by Daenyth** [comment]
That's an interesting idea but I don't know that we have enough permissions right now to make it sensible. We could explore it in the future

**Comment by woogerboy21** [comment]
Seems like this is a good place that starts the concept.  Having the ability to perform actions like the various requirements for just a simple room may provide a skeleton for the concept.

**Comment by MassCraziness** [comment]
I definitely think something like this would be a good stepping stone to getting towards multiple roles and additional permission settings for various user levels. The only thing I sort of worry of is user-created rooms causing sort of "exclusive clubs" and thus using it to be "above" others. Also, it would spread moderators out a good bit (and I'm not so sure that's such a great idea).

The concept is good, but perhaps some more clarifying would not be so bad (that is, what levels can do these different things (such as create a room or delete a room).

**Comment by Daenyth** [comment]
> exclusive clubs

I think that actually would be really good - people who like one play experience can self moderate and keep trolls out of their own community

> spread moderators out

The creator of a channel would have the ability to appoint channel operators who op-like powers within their room

> What levels can do what

The ability to create or destroy rooms should be configurable to user levels - admin / mod / reg. The server owner should be able to say "moderators and higher can create and destroy rooms" or "registered users can create rooms". The creator of a room should always be able to destroy it.

Something like

```
# servatrice.ini
userLevelCanCreateRoom = mod # [mod, admin, reg]
userLevelCanDestroyRoom = mod # [mod, admin]
```

**Comment by MassCraziness** [comment]
Okay, I can see some good points, but

1. Would these channel operators negate the necessity for server moderators? That is, now that they can self-moderate their "community", do server guidelines go out the window (and, as well, moderators).
2. If not, then how do we decide when server-level punishment is needed? 
3. How would this affect a Code of Conduct (given, we now have separate rooms made by separate people who don't feel the same things). Would it just be destroyed, or how would that work if we now no longer really need moderators for anything?

**Comment by Daenyth** [comment]
> 1 

Partially. I don't expect mods to stay in every room. Overall server rules would still apply. But operators could do basic level control without requiring a mod

> 2

The same way we do now - either direct observation or reports/screenshots from other users

> 3

I don't think it's impacted - I'd suggest we keep the wooger CoC the same

**Comment by MassCraziness** [comment]
Okay. I'm definitely fine with a more IRC-like system (especially to the point of several elevated moderator/admin roles and permission levels).

**Comment by MassCraziness** [comment]
Easy to hard (IMO):
•	Add icon for channel operator (does not necessarily have to be usable when added, just there to make it easier when it is implemented)
•	Add kick function for moderators & operators (does not have to be used, just functional and within the code to enable it)
•	Add a command to create room (there is a function in the admin panel, just see if we can make it work then add to client)
•	Add a command to delete room (this is in the admin panel, just need to make it work and add to client)
•	Figure out how to handle client display when they are in a room being deleted (just a popup box?)
•	Creators (and possibly operators) can manage access lists - whitelist & blacklist for room joining. (Creating a list of people not allowed in the main room would allow it to be tested. Does not have to necessarily be used or seen until completed)
•	Rooms can have user level restrictions - permit only registered users, only mods, only admins, etc.
•	Decide whether any rooms should be special - possibly add a force-autojoin flag for main room (the main chat room already auto-joins us, and can’t be deleted. Just a matter of making it flagged)
•	Room creator can set a password on the room (see if we can somehow make the main room have a password when it tries to auto-join us, for now)
•	Room creators can add other users as room operators who can help manage the room. (Add some sort of mod-up function for admin-levels in the main room, for now, and have it automatically elevate them)
•	Modify existing rooms table for password field, user level restriction, channel owner (after we get the main room having these, just a matter of making them configurable)
•	Figure out how to handle games from deleted rooms (not sure how hard it is to have it destroy the games)
•	Add servatrice option to control whether room creation is for reg user or mods or admins

Unsorted Stuff:
•	Figure out how to inform people about rooms. (not in list because it’s more a decision of if you want it to be a main-chat message, its own tab, a popup, or what)
•	Add a table for white/black lists referencing a room (not sure what this means)
•	Add a table for channel operators referencing a room (not sure what this means)
•	Add proto for room creation event (not sure what this means)

**Comment by woogerboy21** [comment]
As mentioned in gitter.  2 things you will want to make sure to add is 1) the ability to allow/disallow user created rooms in the server configuration file and 2) the abillity to limit the number of rooms a user can create.  We don't want some player creating 1000 rooms.

**Comment by Daenyth** [comment]
I think your "disable" request is adequately served by setting "required level" to admin.

We should definitely add a reasonable default room limit.

**Comment by ZeldaZach** [comment]
Unfortunately, this isn't something I plan on bringing to the program
