### ISSUE TITLE
pixmap cache able to show wrong values in settings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#631]
Settings --> General --> "Picture cache size:"

Tested this by random and was confused that I could store a value of like 3008 MB.
No error, no nothing. It just showed this value, even after reopening settings.
That's very confusing. Show something that is not working like it is displayed.

Can we make the number go down to the highest possible value after saving?
Plus add a short info next to the field? (like "Max. xxxx MB")

Reopening the program changes the value back to my previous value (--> 256MB), not the highest possible value, which would have been 2047MB and maybe more logical.

Someone can change the value and decide to go for a not supported one. He will likely never realize, that his change never got applied.

CC: @ctrlaltca #558

**Comment by ZeldaZach** [comment]
I swear @ctrlaltca put a block to prevent > 2047...

**Comment by Psithief** [comment]
It's worse than that, if you put in an invalid value it appears to be effectively zero, or as close to zero so it doesn't matter.

Even stranger, the cache size changes on the fly with the settings menu open. You don't have to click `OK`, so you also can't cancel by clicking the `X` button either.

### To reproduce:
1. Open settings, set Picture Cache to `2048 MB` (I used the up arrow). Close settings.
2. Start a local game, load a deck. No images will display.
3. Open settings, press the down-arrow to drop the size to `1984 MB`. The cards behind the Settings window instantly start loading from disk.

**Comment by ZeldaZach** [comment]
If you go above 2047 it stops working @Psithief ... we're trying to figure out why though

**Comment by Psithief** [comment]
From an end-user point of view;
  It doesn't really matter why 2047 is the working limit, that number first needs to be reflected in the user interface. `64 MB` to `2047 MB`.

**Comment by ctrlaltca** [comment]
That should be how it's working after #558:
 1) the spinbox won't let you choose a value > 2047 or < 64 using the arrows or writing it in the field
 2) the field won't accept gibberish (not-numeric characters, etc..)
 3) if you delete the whole field, it will be reset to its previous value on exit
 4) When cockatrice starts, if it detects a wrong value is written in the config, it will reset to the default (256MB).
@tooomm how did you manage to put a value of 3008 in the field? does your build contain the fix #558?

About the fact that the change is applied on the fly when editing the value, that's true for all the options in cockatrice's preferences (eg. language change gets applied on the fly). That's why there's no "cancel" button in that dialog.

**Comment by Psithief** [comment]
I'm using 739ca6a, that should include #558.

### Working
* Reset to 256 MB on load with invalid value
* Spinbox only accepts numeric characters

### Not Working
* Spinbox's upper limit is `8192 MB`, not `2047 MB`.

**Comment by ctrlaltca** [comment]
Ouch, it sounds like the commit was partly reverted by accident with the refactoring made in 931b4203235da88450ec9ab80a0fdd36a804b933 .
