### ISSUE TITLE
Implement "Tip of the day" style feature

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#652]
One of the big UI problems we have is that we have a lot of features that aren't very discoverable. Something like intellij's tip of the day feature would help people find out about them
- Card arrows
- Buddy list
- `[[card]]`, `[card]`, and `[url]`
- Handling bottom deck cards
- How to play face down
- Confusion about when other player can see cardnames - drawing card, etc
- What the user shirts mean

Example: http://www.javaspecialists.eu/courses/concurrency/setup/idea12.png

**Comment by Daenyth** [comment]
We can have a list of tips, a seen flag in the config (tips/seenCardArrowTip -> true) and cycle through them. Most useful/important tips first

**Comment by poixen** [comment]
I like this. Especially since we are adding a lot of features now.

**Comment by ZeldaZach** [comment]
I'm a fan, and users can opt out of if they'd like (at which points mods should just refuse their dumb questions relating to something we explain)

**Comment by woogerboy21** [comment]
Were would the list of items to display to the user be pulled from?

**Comment by ZeldaZach** [comment]
Server operator's Database

**Comment by woogerboy21** [comment]
And pulled down to the client?  Or is it something presented to the user on connect?

**Comment by ZeldaZach** [comment]
Pulled and presented after the user logs into the server

**Comment by poixen** [comment]
You mean like a popup? That would get annoying real fast.

**Comment by ZeldaZach** [comment]
Disable-able at any point with a little checkbox on the physical popup

**Comment by poixen** [comment]
I would still want to get message of the day. Maybe it would be better built into the client. Maybe under the user list in each room? Or in the server tab.

**Comment by Daenyth** [comment]
They would be hard coded in the client. That way we can use it to message
about new features. This doesn't need to have any server side knowledge

**Comment by Daenyth** [comment]
I'll grab some screenshots of a version other software uses

**Comment by woogerboy21** [comment]
I was thinking you wanted something client side, but the problem with that idea is the list of items would never change to display to the user till they upgraded there client.

**Comment by Daenyth** [comment]
That's kind of the point though. It should inform them about what they can
do. The update alerting is a separate thing.

**Comment by Daenyth** [comment]
<img width="558" alt="screen shot 2015-09-15 at 7 59 14 am" src="https://cloud.githubusercontent.com/assets/14644/9875869/b28681f6-5b7f-11e5-9f6f-65752d641fec.png">

So this covers the key points for me; checkbox to disable it, scroll buttons for when the user wants to see more.

Embedded screenshots are pretty nice but not needed for MVP.

**Comment by tooomm** [comment]
Another idea coming to my mind is...

I know these kind of "Tip of the day" dialog popups at app start. Well, most of the time you are kinda annoyed by them because you open the app to quickly do something and often don't have the time to or just don't want to read about things that don't help you with your particular problem at the moment. Especially if you happen to know/use the app for some time. (you still haven't mastered it yet for sure... but anyway)
A bit like a manual, not as worse for sure. :)

I know from another game, that they have something like changing tips of the day as well, but they are implemented into the loading screen, so you're actually happy getting entertained and read them. This way you learn new stuff and are not annoyed at all.
While we don't have a particular loading screen... we could place our tips here for example:
![totd](https://cloud.githubusercontent.com/assets/9874850/16714367/fb819b70-46c0-11e6-9290-ce695d062585.png)

**Comment by Daenyth** [comment]
@tooomm that's reasonable, but I'd like to start with just on-launch tips

**Comment by Beat1823** [comment]
I'd like to help out on this if possible :D.

**Comment by Daenyth** [comment]
@Beat1823 poke me on gitter tomorrow and I'll walk you through where we are now and what's left.

**Comment by Beat1823** [comment]
(Sorry, I don't know why i didn't get this notification.)
I realize this is a month after but I would still like to walk thru how i can help!
I poked you on gitter.

**Comment by ZeldaZach** [comment]
Hey @Beat1823 We'll try to help you out. Weird how you didn't get a notification...

**Comment by ZeldaZach** [comment]
So my idea of where to get the Tips from will be the GitHub wiki, we can create a table on a page and as long as you follow the table the tips can be properly parsed.

ID | ADD_DATE | TIP
--- | --- | ---
0 | 2018-02-16 | There is now a loyalty filter in the deck editor!
1 | 2018-02-16 | You can check for new client updates by going to ...

**Comment by skwerlman** [comment]
i think this should be in a normal repo instead of the wiki (this one or another; i have no preference). my 2 reasons for this are 1) the wiki should be reserved for information about the client/server/project, not used for storing metadata files, and 2) the wiki is potentially susceptible to vandalism, since it is community-editable without approval (good for documentation, bad for resources that will be automatically download by every client and then parsed)

**Comment by Daenyth** [comment]
Not a bad idea!
