### ISSUE TITLE
switching to full screen causes card images to reload

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#699]
On the newer version of the client (at least on Version 8e396ca), switching from normal view to full screen and back causes the card images to reload momentarily. Also, there is a weird tic where mousing over a card will cause it to briefly display the "proxy version" of the card (blank card with its color and name text) then reload and show the image. Both of these things are visually jarring and very annoying, and didn't exist in the earlier versions of the client.

**Comment by Psithief** [comment]
Whenever that happens it means the card images have been deallocated from memory, I think. I find it always happens if I leave the program alone for a while and come back; all the images need to be reloaded from disk.

The *alternative* is Cockatrice having a great big memory leak like it had before. I don't know the exact details on that, however.

Cockatrice *could* be prompted to refill its heap of images before it repaints the interface, but that would appear to be laggy because Cockatrice would take a while to react.

**Summary:** There is no solution to all of these apparent visual blips without making another aspect of Cockatrice worse.

**Comment by ZeldaZach** [comment]
I'm fine with it quickly reloading the image every so often. It's a minor thing

**Comment by ctrlaltca** [comment]
Image "flickering" is probably related to them being reloaded from disk. This can happen in two occasions:
 * images size has changed: card thumbnails are cached at the very exact size they appear on the screen. I suppose that going fullscreen their size slightly change, so they need to be re-rendered at the new size;
 * cockatrice's images cache is full, so there's no space to hold all the images of the new cards. If you have enough free RAM, you can tune up the "pixmap cache size" from the settings menu. The default of 256MB should be enough for some standard games, but if you're playing a game with a lot of cards (like a 4 players commander) it will probably perform better with 2x or 4x the default value.
