### ISSUE TITLE
Private messages history

### ISSUE THREAD

**Issue by dsolstad** [Cockatrice/Cockatrice#700]
After a quit, client crash or disconnect it is really annoying to not have the opportunity to see what users have written to you. It's also nice to just scroll up and see the complete history.

**Comment by Daenyth** [comment]
Would you want it persistent across client resets or manual tab closes, or would it be enough if the tab doesn't get closed when you disconnect?

**Comment by dsolstad** [comment]
If I message a user I have been messaging with before, it would be nice to see the whole chat history, even after I have relaunced trice.

**Comment by tooomm** [comment]
I just experienced a Server timeout today. Happens quite often to me. For this kind of stuff it would be sufficient to just keep the message tabs. Then I can see if I got that one reply while being away. 

Maybe that's a first step?

That would still be very helpful if we get private message history later:
Imagine you are away and receive a pm (somebody starts a new chat with you). Server timeout/Server down... disconnect and all message tabs are closed. You still have the message history to read that reply of your friend you've been chatting to. But since all tabs are gone you still won't recognize new chats in between and miss them!
If the tabs are persistent on disconnect you will recognize them. So it's a useful feature now and later with history!

**Comment by Daenyth** [comment]
I already have a ticket about this.

**Comment by tooomm** [comment]
found it --> #666

**Comment by ZeldaZach** [comment]
I believe this was solved by #1474
