### ISSUE TITLE
Cockatrice loads each image several times

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#745]
When I load a deck before a game, cockatrice loads each card's image once per instance of that card instead of loading it once and reusing the image.
For instance, if I have a deck consisting of 60 Plains, Cockatrice will load the image for Plains 60 times instead of once.

I'm using cockatrice ef65434, and my image cache is set to 2047 MB.

**Comment by poixen** [comment]
Are you debugging to see this? Images should be loaded from cache rather than source location.

**Comment by skwerlman** [comment]
Well, since the debug instructions for linux users are 'run from console', yes?
Here's the [log](http://paste.ubuntu.com/10237029/). Unless the log message is really misleading, the image for Plains is loaded 60 times. (lines 14~135)

**Comment by skwerlman** [comment]
Also, this doesn't seem to happen anywhere else, only when loading a deck before a game.

**Comment by ctrlaltca** [comment]
Your interpretation of the log is correct. I've been able to reproduce the issue with a 60-plains deck from the UNH set, but only when the card picture was not already present in memory.
I suppose that the forced pictures preload that happens when loading a deck is not merging picture requests for cards with the same name. I'll look into this.
