### ISSUE TITLE
Feature Request: Macros to put abilites on the stack

### ISSUE THREAD

**Issue by jjo2997** [Cockatrice/Cockatrice#810]
When you right click a permanent, you get a dropdown menu.

![screen shot 2015-03-09 at 11 09 43 am](https://cloud.githubusercontent.com/assets/7950979/6557884/ea7e7756-c64e-11e4-8157-d17140f3aef0.png)

Would it be possible to add to this menu with additional options 'Put activated ability on stack...' and 'Put triggered ability on stack...'? These options would print in chat 

[PLAYERNAME] puts activated ability of [CARDNAME] on stack or [PLAYERNAME] puts triggered ability of [CARDNAME] on stack. It would help with indicating abilities that aren't immediately obvious (such as Tasigur, apparently) and provide a more organic way to query your opponent(s) for responses.

**Comment by ZeldaZach** [comment]
Usually players just type into chat "Trigger" or "activating"

**Comment by Daenyth** [comment]
I tend to use arrows for this.

I'm not sure how to handle this in a game-agnostic way.

**Comment by jjo2997** [comment]
@Daenyth Game-agnostic?

Also, arrows are obtrusive and tedious. I'd prefer to simply right-click Rhystic Study rather than draw an arrow to every single spell an opponent cast for the rest of the game.

**Comment by tooomm** [comment]
Arrow drawing is not that great since if you change a phase (by fault e.g.) all arrows are gone.

You could parse the card text for activated abilities (always with ":") if you right click a card and put a option to the right click menu that creates a copy of the card to the stack with an annotation of the activated ability you choose. (in case there are several ones to distinguish between them)

**Comment by Daenyth** [comment]
Hmm, that's rather clever. It does have the issue in that the only way to get a token on the stack is to mark it as not being deleted when it leaves play, but we could probably just change the server to consider the stack an in play zone for token destruction purposes

**Comment by suroh1994** [comment]
Has there been any update to this? I recently had a game with multiple players trying out landfall cards from Zendikar Rising in EDH and the amount of triggers happening (sometimes lands entered the battlefield in the middle of resolving all landfall triggers) just couldn't be handled by drawing arrows. For example: how would you solve a card having a trigger on the stack and triggering a second time?
Any improvement on this front would be greatly appreciated!

**Comment by ebbit1q** [comment]
Well how would you represent the ability on the stack? You want it to make a token in the stack zone? Don't forget that in paper games you don't get any of these, you have to just agree with your opponents what is happening then.

**Comment by suroh1994** [comment]
A token would be a simple solution, in my opinion. 
But I don't understand your argument with in paper games. Do we have to stick to what would be possible in the paper world? Even then, it would be possible to write a list of triggers visible to everyone and then go back and tick them off, one by one. Using the chat to make a list, would get super messy because of all the actions being reported in the chat.

So if you don't want to use tokens, maybe a shared notepad would be an option? Or a notepad for every single player (so that others can't mess around with your notes) and have the option to share your notepad with others?

**Comment by ZeldaZach** [comment]
Related #1740 imo
