### ISSUE TITLE
New Token Cheat (atleast to me)

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#826]
Here's a new one that I had never seen.  Players are creating tokens with real card names and claiming to cast them.  If you don't pay close enough attention to the chat box you dont realize its a token being created.

Maybe we should add a token annotation to the object created in the play area in some way?

**Comment by poixen** [comment]
I have seen this and had to deal with this issue too. I think adding "token" to the bottom left of the card will help.

**Comment by tooomm** [comment]
Some suggestions to visually differentiate them better:
- tokens having a bold white boarder
- card size like 80%
- mouse over text label "Token"

but @poixen's idea is nice. instead of the "token" label in the bottem left I like a beautiful T in the bottom left corner of token cards like the new "information **I** logo" in tabs even more: (in grey)
![token t](http://cdns2.freepik.com/free-photo/_427483.jpg)

**Comment by ZeldaZach** [comment]
I know MTGO uses a special symbol on the card to indicate it's a token (as seen [here](https://i.ytimg.com/vi/mJuuu2XsP2c/maxresdefault.jpg))

Maybe we can do something similar that's non intrusive?

**Comment by tooomm** [comment]
Or more of an rectangular card shape instead of the circle I posted first...

I prefer to highlight special cases (tokens here) instead of having this on every single normal card on the battlefield (like modo).

**Comment by Daenyth** [comment]
I actually really don't want to label the tokens so much in game. It's useful to be able to make real copies.

We could make the chat message more obvious though

**Comment by tooomm** [comment]
@Daenyth You really care that much about a small "(T)" in the bottom left corner for example?

If the chat message is better, ok. That's geat!
But you might loose track 3min later when the chat message is gone between many other messages and just the token is left between other cards and there are many action on the battlefield + rearranging. Especially if people play new unreleased cards without pictures next to self created tokens without pictures because they don't use the token file.

**Comment by woogerboy21** [comment]
My $0.02 is to mark the tokens as tokens in some fashion.  That way when some one plays a card that has a restriction as to not being able to target a token yet its been in play long enough for players to forget that its a token there wont be a mistake made.

**Comment by tooomm** [comment]
Example mockup of the (T): I like it!
![token2](https://cloud.githubusercontent.com/assets/9874850/6788132/cf2e1cdc-d197-11e4-8db7-c9a6d09bba08.png)

Could be any other indication as well.

**Comment by poixen** [comment]
I forgot to mention I have done some work on this. I was able to create tokens with a label in the lower left "TOKEN", pretty sure that it can be changed to an svg though. The issue I came upon was rejoining a room. 

When you rejoin a room all the cards are initialized. The thing is that the server doesnt know what is a token. So all the cards appear as they normally do. We would need to change the server to know the difference between a card and a token.

**Comment by Daenyth** [comment]
I guess I don't care that much. And I'm ok with the rejoin issue, we can ticket it for later

**Comment by tooomm** [comment]
Just experienced with a newer player:

```
[19:10:52] ￼ a: how come theres no card image for that
[19:10:54] ￼ me: for what?
[19:10:55] ￼ a: Mantis Rider looks like a token
[19:10:57] ￼ me: oh yes, wait a bit

[19:10:57] It is now a's turn.

[19:10:58] It is now the untap step.
a untaps his permanents.
a untaps his permanents.
[19:10:58] ￼ me: you don't downloaded it before i guess
[19:10:59] It is now the upkeep step.
[19:10:59] It is now the draw step.
a draws 1 card(s).
[19:11:02] ￼ me: new cards gets fetched when needed (because you clicked them in deck editor or saw them in a match)
```

**Comment by JineteDV** [comment]
I don't feel like this is a necessary addition. This isn't a new problem at all, people have been trying to cheat like this since Cockatrice was a thing, no one gets to 'pull a fast one' on their opponent unless the other player was just not paying attention to the game log what so ever. There are a few tokens that have a lot of text on them and I wouldn't enjoy cluttering those up even more.

**Comment by tooomm** [comment]
It should help players in general (new ones in particular) and is an improvement overall.
Sure it's the players responsibility to check plays and logs, but we don't need to make it unnecessarily difficult to discover cheating or even "support" cheating...

The tokens showing text (annotation) is not really intended I think and reported already in #241.
It kinda destroys the beautiful tokens with art... It should just be a fallback when no pictures are available in my opinion. :)
Anyway, The indicator for tokens could be layered beneath the annotations to not interfere with their readability until 241 is worked out.

I'm still a fan of this!
