### ISSUE TITLE
changes with translation files doesn't delte old ones

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#830]
![translations](https://cloud.githubusercontent.com/assets/9874850/6653219/180ee9e2-ca89-11e4-829c-dc8bb210f1aa.png)

We renamed Brazilian Portuguese and deleted Chinese. They still show up because they didn't get removed during a new cockatrice installation. The new ones just got added into the folder "Translations".

"cockatrice_zh_CN" (old+empty chinese file) & "cockatrice_pt-br" (misprint) needs to be removed at installation. They are already gone on github but are still present if people overwrite their installations with new builds. (not sure about uninstalling first)
Some kind of general check at installation to prevent this for future language changes as well would be great!

**Comment by ZeldaZach** [comment]
This does seem to be a problem... Maybe on install we can trash the old translation files?
cc: @poixen @ctrlaltca

**Comment by ctrlaltca** [comment]
I think this is a windows-only problem, because:
 * a linux package (.deb, .rpm ,..) will automatically clean up its junk when updated;
 * under osx, an update removes the whole old application bundle, and translations are kept inside it;

So, this is basically a problem of the NSIS installer script not uninstalling old cockatrice versions before installing the new one.

**Comment by ctrlaltca** [comment]
This has been fixed since the windows NSIS installer now requires an uninstall before installing the new version.
