### ISSUE TITLE
Moving Face down cards to library from play reveals it to opponents

### ISSUE THREAD

**Issue by Fizztastic** [Cockatrice/Cockatrice#884]
It happens regardless if you're holding shift or moving them to bottom/top from right click menu.

**Comment by woogerboy21** [comment]
I think there needs to be more context here.  As far as I understand the rules state that if a face down card moves to any zone (other than exile) it gets revealed.

**Comment by Fizztastic** [comment]
What if you want to play a card like [Unexpectedly Absent](http://magiccards.info/c13/en/25.html)? Because the way it is right now, you would reveal the top X cards as well.

**Comment by woogerboy21** [comment]
That would be a bug for cards that you should be able to place or manipulate the library with out revealing the cards.  No were does the card say put the card into play and then move it to the library.  Probably need some type of other zone in cockatrice for this type of function.

@Daenyth @ctrlaltca @poixen   Thoughts?

**Comment by Fizztastic** [comment]
[Picture1](https://dl.dropboxusercontent.com/u/7304112/FromLib1.jpg)
[Picture2](https://dl.dropboxusercontent.com/u/7304112/FromLib2.jpg)

**Comment by woogerboy21** [comment]
707.9. If a face-down permanent moves from the battlefield to any other zone, its owner must reveal it to all players as he or she moves it. If a face-down spell moves from the stack to any zone other than the battlefield, its owner must reveal it to all players as he or she moves it. At the end of each game, all face-down permanents and spells must be revealed to all players.

The server / client is following the rules  The problem is there either needs to be a new zone that allows for movement with out reveal or a combination of keyboard / mouse that allows the movement without reveal. 

Players that are putting the cards into the battlefield and then moving them are simply playing them wrong.  But I would also like to point out there isn't a way currently to "play them right".

**Comment by ZeldaZach** [comment]
Potentially related to #775

**Comment by JineteDV** [comment]
This problem happens both ways. The most obvious way to cast Vampiric Tutor is to put the card facedown on the field, shuffle then put the tutored card on top, but doing so revealed the name of the card to the other players. i.e. Stop trying to hold our hands, people forget triggers and the like all the time, yall can't idiot proof everything.

**Comment by woogerboy21** [comment]
@Fizztastic :+1: to your user pic.  I miss bloom decks...

**Comment by Fizztastic** [comment]
@woogerboy21 I still play the deck at my local card store legacy nights ;)

**Comment by poixen** [comment]
We need to be able to exile face down.

**Comment by tooomm** [comment]
All these (and maybe many more) would benefit from an exile face down option, which doesn't reveals them by rule when moved:
- Necropotence
- Scroll Rack
- Unexpectedly Absent (need this as workaround / there could also be an option to "put on top -x")
- Vampiric Tutor (need this as workaround / there could also be an option to "put on top of library" in library view --> close view, shuffle + put choosen card on top)

Is it possible to mix normal exile and face down exiled cards together in the one exile pile we have right now? oO

@Fizztastic Is that a new behavior or has it been around for longer?

**Comment by Daenyth** [comment]
This behavior is new. It's almost certainly from #775

**Comment by Fizztastic** [comment]
@tooomm AFAIK yes this is new because this used to work in the past year and a half that I've been playing on the server.

**Comment by woogerboy21** [comment]
Would it break anything to simply make the shift+drag of a face down card not show it regardless of zone being moved from/to?

@ctrlaltca

**Comment by Daenyth** [comment]
No, people have learned to do the table. We'll have to make it work like
before and provide some options to reveal while moving

**Comment by anoda9** [comment]
Trying to make the client enforce 707.9 (e.g. by creating two options for playing cards face down - as a morph (identity revealed on zone change) and as a secret card (identity never revealed on zone change)) doesn't seem like a good direction to go in, for a few reasons: 

1.) it's game specific (applies to magic only, which is an issue if we want the client to be universal/game-agnostic). 
2.) It's a lot of work for very little gain, when there are other issues that could use attention (keyboard shortcuts, replay functionality, etc.). The current solution to the issue (just remember to reveal your morphs when they change zones) works well enough IRL, and is sufficient on cockatrice also. Generally, implementing specific rules knowledge for specific situations doesn't seem worth it, unless the fix is very simple relative to the gain in functionality (etb tapped permanents automatically entering tapped is a great example of where it *is* worth it). 

Overall, I'd prefer to see a return to the old functionality - the identities of cards played face-down are always hidden, regardless of zone changes, and the onus is on the players to make sure cards are revealed when they should be.

**Comment by woogerboy21** [comment]
Yeah, i guess you could always just reveal the card if you are supposed to.
